Repository su2code/SU2, pull requests merged in 2019-09, with the labels that each got.

#785 Bug fix for vertex traction computation (new method) in incompressible flows.
  SU2_CFD/src/python_wrapper_structure.cpp
  SU2_CFD/src/solver_structure.cpp
Labels: PR: reviewed-approved

#778 Mesh Quality Metrics
  Common/include/config_structure.hpp
  Common/include/config_structure.inl
  Common/include/geometry_structure.hpp
  Common/include/geometry_structure.inl
  Common/src/config_structure.cpp
  Common/src/geometry_structure.cpp
  SU2_CFD/include/SU2_CFD.hpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/numerics_direct_mean.cpp
  SU2_CFD/src/output_structure.cpp
  SU2_IDE/Xcode/SU2_CFD.xcodeproj/project.pbxproj
Labels: PR: unreviewed

#767 Feature incompressible ale
  Common/src/config_structure.cpp
  SU2_CFD/include/numerics_structure.hpp
  SU2_CFD/include/solver_structure.hpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/numerics_direct_mean_inc.cpp
  SU2_CFD/src/solver_direct_mean_inc.cpp
  TestCases/parallel_regression.py
  TestCases/serial_regression.py
  TestCases/unsteady/pitching_naca0015_rans_inc/config_incomp_turb_sa.cfg
Labels: PR: reviewed-approved

#771 Feature PaStiX wrapper (external direct sparse solver)
  Common/include/config_structure.hpp
  Common/include/config_structure.inl
  Common/include/linear_algebra/CPastixWrapper.hpp
  Common/include/linear_algebra/CPreconditioner.hpp
  Common/include/linear_algebra/CSysMatrix.hpp
  Common/include/mpi_structure.hpp
  Common/include/option_structure.hpp
  Common/lib/Makefile.am
  Common/src/config_structure.cpp
  Common/src/linear_algebra/CPastixWrapper.cpp
  Common/src/linear_algebra/CSysMatrix.cpp
  Common/src/linear_algebra/CSysSolve.cpp
  Common/src/linear_algebra/CSysVector.cpp
  Common/src/linear_algebra/meson.build
  SU2_CFD/src/drivers/CDummyDriver.cpp
  TestCases/pastix_support/config.cfg
  TestCases/pastix_support/readme.txt
  meson.build
  meson_options.txt
Labels: PR: unreviewed

#766 Feature dynamic mesh discrete adjoint
  Common/include/dual_grid_structure.hpp
  Common/include/dual_grid_structure.inl
  Common/src/config_structure.cpp
  Common/src/dual_grid_structure.cpp
  Common/src/geometry_structure.cpp
  Common/src/grid_movement_structure.cpp
  SU2_CFD/src/drivers/CDiscAdjSinglezoneDriver.cpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/drivers/CSinglezoneDriver.cpp
  SU2_CFD/src/iteration_structure.cpp
  SU2_CFD/src/solver_direct_mean.cpp
  TestCases/disc_adj_euler/naca0012_pitching/inv_NACA0012_pitching.cfg
  TestCases/parallel_regression_AD.py
  TestCases/serial_regression_AD.py
Labels: PR: unreviewed, dependent

#781 Enhancement multipoint opt
  Common/src/config_structure.cpp
  Common/src/grid_movement_structure.cpp
  SU2_IDE/Wing/SU2_Wing.wpr
  SU2_PY/Makefile.am
  SU2_PY/SU2/eval/functions.py
  SU2_PY/SU2/eval/gradients.py
  SU2_PY/SU2/io/config.py
  SU2_PY/SU2/io/state.py
  SU2_PY/SU2/io/tools.py
  SU2_PY/SU2/opt/project.py
  SU2_PY/SU2/opt/server.py
  SU2_PY/SU2/util/polarSweepLib.py
  SU2_PY/SU2/util/pyCppTap.py
  SU2_PY/compute_polar.py
  SU2_PY/compute_uncertainty.py
  SU2_PY/meson.build
  SU2_PY/package_tests.py
  SU2_PY/patient_designspace.py
  SU2_PY/shape_optimization.py
  config_template.cfg
Labels: PR: unreviewed
