Repository su2code/SU2, pull requests merged in 2019-11, with the labels that each got.

#810 Adding caching to Github Actions Regression Workflow
  .github/workflows/regression.yml
  docker/build/Dockerfile
  docker/build/compileSU2.sh
Labels: PR: merged

#807 Various fixes II
  Common/include/config_structure.hpp
  Common/include/config_structure.inl
  Common/src/config_structure.cpp
  QuickStart/inv_NACA0012.cfg
  SU2_CFD/include/drivers/CDriver.hpp
  SU2_CFD/include/output/filewriter/CFileWriter.hpp
  SU2_CFD/include/output/filewriter/CParallelDataSorter.hpp
  SU2_CFD/include/solver_structure.hpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/interfaces/cht/CConjugateHeatInterface.cpp
  SU2_CFD/src/iteration_structure.cpp
  SU2_CFD/src/output/CAdjElasticityOutput.cpp
  SU2_CFD/src/output/CFlowCompOutput.cpp
  SU2_CFD/src/output/filewriter/CFEMDataSorter.cpp
  SU2_CFD/src/output/filewriter/CFVMDataSorter.cpp
  SU2_CFD/src/output/filewriter/CSU2MeshFileWriter.cpp
  SU2_CFD/src/output/filewriter/CSurfaceFEMDataSorter.cpp
  SU2_CFD/src/output/filewriter/CSurfaceFVMDataSorter.cpp
  SU2_CFD/src/python_wrapper_structure.cpp
  SU2_CFD/src/solver_adjoint_elasticity.cpp
  SU2_CFD/src/solver_direct_heat.cpp
  SU2_IDE/Xcode/SU2_CFD.xcodeproj/project.pbxproj
  TestCases/coupled_cht/disc_adj_incomp_2d/solid_cylinder1.cfg
  TestCases/coupled_cht/disc_adj_incomp_2d/solid_cylinder2.cfg
  TestCases/coupled_cht/disc_adj_incomp_2d/solid_cylinder3.cfg
  TestCases/coupled_cht/incomp_2d/solid_cylinder1.cfg
  TestCases/coupled_cht/incomp_2d/solid_cylinder2.cfg
  TestCases/coupled_cht/incomp_2d/solid_cylinder3.cfg
  TestCases/coupled_cht/incompressible/configFlow.cfg
  TestCases/coupled_cht/incompressible/configSolid.cfg
  TestCases/coupled_cht/incompressible/coupled_cht_incompressible.cfg
  TestCases/parallel_regression_AD.py
  TestCases/serial_regression_AD.py
Labels: PR: unreviewed

#811 Testing Release Crafter (can be ignored)
  .github/workflows/regression.yml
  CPPLINT.cfg
  Common/include/config_structure.hpp
  Common/include/config_structure.inl
  Common/src/config_structure.cpp
  QuickStart/inv_NACA0012.cfg
  SU2_CFD/include/drivers/CDriver.hpp
  SU2_CFD/include/output/filewriter/CFileWriter.hpp
  SU2_CFD/include/output/filewriter/CParallelDataSorter.hpp
  SU2_CFD/include/solver_structure.hpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/interfaces/cht/CConjugateHeatInterface.cpp
  SU2_CFD/src/iteration_structure.cpp
  SU2_CFD/src/output/CAdjElasticityOutput.cpp
  SU2_CFD/src/output/CFlowCompOutput.cpp
  SU2_CFD/src/output/filewriter/CFEMDataSorter.cpp
  SU2_CFD/src/output/filewriter/CFVMDataSorter.cpp
  SU2_CFD/src/output/filewriter/CSU2MeshFileWriter.cpp
  SU2_CFD/src/output/filewriter/CSurfaceFEMDataSorter.cpp
  SU2_CFD/src/output/filewriter/CSurfaceFVMDataSorter.cpp
  SU2_CFD/src/python_wrapper_structure.cpp
  SU2_CFD/src/solver_adjoint_elasticity.cpp
  SU2_CFD/src/solver_direct_heat.cpp
  SU2_IDE/Xcode/SU2_CFD.xcodeproj/project.pbxproj
  TestCases/coupled_cht/disc_adj_incomp_2d/solid_cylinder1.cfg
  TestCases/coupled_cht/disc_adj_incomp_2d/solid_cylinder2.cfg
  TestCases/coupled_cht/disc_adj_incomp_2d/solid_cylinder3.cfg
  TestCases/coupled_cht/incomp_2d/solid_cylinder1.cfg
  TestCases/coupled_cht/incomp_2d/solid_cylinder2.cfg
  TestCases/coupled_cht/incomp_2d/solid_cylinder3.cfg
  TestCases/coupled_cht/incompressible/configFlow.cfg
  TestCases/coupled_cht/incompressible/configSolid.cfg
  TestCases/coupled_cht/incompressible/coupled_cht_incompressible.cfg
  TestCases/parallel_regression_AD.py
  TestCases/serial_regression_AD.py
  docker/build/Dockerfile
  docker/build/compileSU2.sh
  externals/CPPLINT.cfg
Labels: PR: unreviewed, chore

#816 Various Fixes III
  Common/src/grid_movement_structure.cpp
  SU2_CFD/src/output/CAdjFlowCompOutput.cpp
  SU2_CFD/src/solver_direct_mean.cpp
  SU2_CFD/src/solver_structure.cpp
Labels: PR: reviewed-approved, no_changelog

#818 stylistic+comment changes
  Common/include/config_structure.hpp
  Common/include/element_structure.hpp
  Common/include/element_structure.inl
  Common/include/gauss_structure.hpp
  Common/include/gauss_structure.inl
  Common/include/geometry/elements/CElement.hpp
  Common/include/geometry/elements/CElementProperty.hpp
  Common/include/geometry/elements/CGaussVariable.hpp
  Common/include/geometry_structure.hpp
  Common/include/grid_adaptation_structure.hpp
  Common/include/grid_movement_structure.hpp
  Common/include/interpolation_structure.hpp
  Common/include/linear_algebra/CMatrixVectorProduct.hpp
  Common/include/linear_algebra/CPreconditioner.hpp
  Common/include/option_structure.hpp
  Common/include/primal_grid_structure.hpp
  Common/include/toolboxes/C2DContainer.hpp
  Common/lib/Makefile.am
  Common/src/element_linear.cpp
  Common/src/element_structure.cpp
  Common/src/gauss_structure.cpp
  Common/src/geometry/elements/CElement.cpp
  Common/src/geometry/elements/CHEXA8.cpp
  Common/src/geometry/elements/CPRISM6.cpp
  Common/src/geometry/elements/CPYRAM5.cpp
  Common/src/geometry/elements/CQUAD4.cpp
  Common/src/geometry/elements/CTETRA1.cpp
  Common/src/geometry/elements/CTRIA1.cpp
  Common/src/geometry/elements/meson.build
  Common/src/geometry_structure.cpp
  Common/src/grid_movement_structure.cpp
  Common/src/meson.build
  SU2_CFD/include/drivers/CDriver.hpp
  SU2_CFD/include/fluid_model.hpp
  SU2_CFD/include/integration_structure.hpp
  SU2_CFD/include/iteration_structure.hpp
  SU2_CFD/include/numerics_structure.hpp
  SU2_CFD/include/output/CAdjFlowIncOutput.hpp
  SU2_CFD/include/output/CAdjFlowOutput.hpp
  SU2_CFD/include/output/CFlowIncOutput.hpp
  SU2_CFD/include/output/COutput.hpp
  SU2_CFD/include/output/COutputLegacy.hpp
  SU2_CFD/include/sgs_model.hpp
  SU2_CFD/include/solver_structure.hpp
  SU2_CFD/include/transport_model.hpp
  SU2_CFD/include/variables/CDiscAdjFEABoundVariable.hpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/integration_structure.cpp
  SU2_CFD/src/numerics_direct_elasticity.cpp
  SU2_CFD/src/numerics_direct_elasticity_linear.cpp
  SU2_CFD/src/numerics_direct_elasticity_nonlinear.cpp
  SU2_CFD/src/solver_direct_elasticity.cpp
  SU2_CFD/src/solver_structure.cpp
  SU2_CFD/src/solvers/CMeshSolver.cpp
Labels: PR: reviewed-approved, no_changelog

#821 Restructure Elasticity numerics files
  SU2_CFD/include/drivers/CDriver.hpp
  SU2_CFD/include/numerics/elasticity/CFEAElasticity.hpp
  SU2_CFD/include/numerics/elasticity/CFEALinearElasticity.hpp
  SU2_CFD/include/numerics/elasticity/CFEAMeshElasticity.hpp
  SU2_CFD/include/numerics/elasticity/CFEANonlinearElasticity.hpp
  SU2_CFD/include/numerics/elasticity/CFEM_DielectricElastomer.hpp
  SU2_CFD/include/numerics/elasticity/CFEM_IdealDE.hpp
  SU2_CFD/include/numerics/elasticity/CFEM_Knowles_NearInc.hpp
  SU2_CFD/include/numerics/elasticity/CFEM_NeoHookean_Comp.hpp
  SU2_CFD/include/numerics_structure.hpp
  SU2_CFD/include/numerics_structure.inl
  SU2_CFD/obj/Makefile.am
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/meson.build
  SU2_CFD/src/numerics/elasticity/CFEAElasticity.cpp
  SU2_CFD/src/numerics/elasticity/CFEALinearElasticity.cpp
  SU2_CFD/src/numerics/elasticity/CFEAMeshElasticity.cpp
  SU2_CFD/src/numerics/elasticity/CFEANonlinearElasticity.cpp
  SU2_CFD/src/numerics/elasticity/CFEM_DielectricElastomer.cpp
  SU2_CFD/src/numerics/elasticity/CFEM_IdealDE.cpp
  SU2_CFD/src/numerics/elasticity/CFEM_Knowles_NearInc.cpp
  SU2_CFD/src/numerics/elasticity/CFEM_NeoHookean_Comp.cpp
Labels: PR: reviewed-approved, no_changelog

#809 Multi-physics and FEA discrete adjoint tweaks
  Common/include/geometry/elements/CElement.hpp
  Common/include/geometry/elements/CElementProperty.hpp
  Common/src/config_structure.cpp
  Common/src/geometry_structure.cpp
  Common/src/grid_movement_structure.cpp
  SU2_CFD/include/drivers/CDiscAdjMultizoneDriver.hpp
  SU2_CFD/include/iteration_structure.hpp
  SU2_CFD/include/solver_structure.hpp
  SU2_CFD/include/variables/CVariable.hpp
  SU2_CFD/obj/Makefile.am
  SU2_CFD/src/SU2_CFD.cpp
  SU2_CFD/src/drivers/CDiscAdjMultizoneDriver.cpp
  SU2_CFD/src/drivers/CDiscAdjSinglezoneDriver.cpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/drivers/CMultizoneDriver.cpp
  SU2_CFD/src/drivers/CSinglezoneDriver.cpp
  SU2_CFD/src/iteration_structure.cpp
  SU2_CFD/src/numerics/elasticity/CFEALinearElasticity.cpp
  SU2_CFD/src/numerics/elasticity/CFEAMeshElasticity.cpp
  SU2_CFD/src/output/CAdjElasticityOutput.cpp
  SU2_CFD/src/output/COutput.cpp
  SU2_CFD/src/solver_adjoint_discrete.cpp
  SU2_CFD/src/solver_adjoint_elasticity.cpp
  SU2_CFD/src/solver_direct_elasticity.cpp
  SU2_CFD/src/solver_direct_mean.cpp
  SU2_CFD/src/solver_structure.cpp
  SU2_CFD/src/solvers/CMeshSolver.cpp
  SU2_CFD/src/variables/CDiscAdjFEAVariable.cpp
  SU2_CFD/src/variables/CDiscAdjVariable.cpp
  SU2_CFD/src/variables/CFEAVariable.cpp
  SU2_CFD/src/variables/CVariable.cpp
  SU2_DOT/src/SU2_DOT.cpp
  TestCases/disc_adj_fsi/Airfoil_2d/config.cfg
  TestCases/disc_adj_fsi/Airfoil_2d/configFEA.cfg
  TestCases/disc_adj_fsi/Airfoil_2d/configFlow.cfg
  TestCases/disc_adj_fsi/Airfoil_2d/grad_young.opt.ref
  TestCases/fea_fsi/StatBeam_3d/configBeam_3d.cfg
  TestCases/parallel_regression_AD.py
  TestCases/serial_regression_AD.py
Labels: PR: unreviewed, no_changelog

#827 improve mkl and mpi4py search
  SU2_PY/pySU2/meson.build
  meson.build
Labels: PR: unreviewed
