Repository su2code/SU2, pull requests merged in 2020-07, with the labels that each got.

#1008 Radial Equilibrium equation fix for Turbo solver
  SU2_CFD/src/solvers/CEulerSolver.cpp
Labels: PR: unreviewed

#1012 Adding Basic Test Case and CGeometry Unit Tests
  UnitTests/Common/geometry/CGeometry_test.cpp
  UnitTests/UnitQuadTestCase.hpp
  UnitTests/meson.build
Labels: PR: unreviewed

#1041 Fix valgrind warning
  Common/src/CConfig.cpp
Labels: PR: reviewed-approved

#1038 Improving and cleaning element orientation checks
  Common/include/geometry/CGeometry.hpp
  Common/include/geometry/CPhysicalGeometry.hpp
  Common/include/geometry/primal_grid/CLine.hpp
  Common/include/geometry/primal_grid/CTriangle.hpp
  Common/src/geometry/CPhysicalGeometry.cpp
  Common/src/geometry/primal_grid/CHexahedron.cpp
  Common/src/geometry/primal_grid/CPrism.cpp
  Common/src/geometry/primal_grid/CPyramid.cpp
  Common/src/geometry/primal_grid/CQuadrilateral.cpp
  Common/src/geometry/primal_grid/CTetrahedron.cpp
  TestCases/hybrid_regression.py
  TestCases/parallel_regression.py
  TestCases/serial_regression.py
  TestCases/tutorials.py
Labels: PR: unreviewed

#1027 Feature actuator disk with variable load
  Common/include/CConfig.hpp
  Common/include/option_structure.hpp
  Common/src/CConfig.cpp
  SU2_CFD/include/solvers/CEulerSolver.hpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  TestCases/hybrid_regression.py
  TestCases/parallel_regression.py
  TestCases/rans/actuatordisk_variable_load/ActuatorDisk.dat
  TestCases/rans/actuatordisk_variable_load/propeller_variable_load.cfg
  TestCases/serial_regression.py
  config_template.cfg
Labels: PR: unreviewed

#983 SU2_PY: Fix multiple TabError and SyntaxError in python scripts
  SU2_PY/SU2/util/filter_adjoint.py
  SU2_PY/compute_uncertainty.py
  SU2_PY/fsi_computation.py
Labels: PR: unreviewed, changelog:fix

#1044 Intermediate base class for flow solvers to avoid duplication.
  Common/include/CConfig.hpp
  Common/include/blas_structure.hpp
  Common/include/omp_structure.hpp
  Common/include/toolboxes/geometry_toolbox.hpp
  Common/src/CConfig.cpp
  Common/src/blas_structure.cpp
  SU2_CFD/include/solvers/CAdjEulerSolver.hpp
  SU2_CFD/include/solvers/CBaselineSolver.hpp
  SU2_CFD/include/solvers/CEulerSolver.hpp
  SU2_CFD/include/solvers/CFEM_DG_EulerSolver.hpp
  SU2_CFD/include/solvers/CFEM_DG_NSSolver.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/include/solvers/CIncEulerSolver.hpp
  SU2_CFD/include/solvers/CIncNSSolver.hpp
  SU2_CFD/include/solvers/CNSSolver.hpp
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/include/solvers/CTurbSASolver.hpp
  SU2_CFD/include/solvers/CTurbSSTSolver.hpp
  SU2_CFD/include/solvers/CTurbSolver.hpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/output/output_structure_legacy.cpp
  SU2_CFD/src/solvers/CAdjEulerSolver.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_CFD/src/solvers/CFEM_DG_EulerSolver.cpp
  SU2_CFD/src/solvers/CFEM_DG_NSSolver.cpp
  SU2_CFD/src/solvers/CHeatSolver.cpp
  SU2_CFD/src/solvers/CIncEulerSolver.cpp
  SU2_CFD/src/solvers/CIncNSSolver.cpp
  SU2_CFD/src/solvers/CNSSolver.cpp
  SU2_CFD/src/solvers/CSolver.cpp
  SU2_CFD/src/solvers/CTurbSASolver.cpp
  SU2_CFD/src/solvers/CTurbSSTSolver.cpp
  SU2_CFD/src/solvers/CTurbSolver.cpp
Labels: PR: reviewed-approved, changelog:chore

#1052 Fix JST-KE
  SU2_CFD/include/solvers/CEulerSolver.hpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
Labels: PR: unreviewed, changelog:fix
