Repository su2code/SU2, pull requests merged in 2020-06, with the labels that each got.

#1016 Fixed a bug for the interpolation weights of a tet
  Common/src/adt_structure.cpp
  SU2_CFD/src/output/filewriter/CParaviewXMLFileWriter.cpp
Labels: PR: unreviewed, changelog:fix

#1009 Hybrid parallel MPI
  Common/include/CConfig.hpp
  Common/include/basic_types/ad_structure.hpp
  Common/include/fem/fem_geometry_structure.hpp
  Common/include/geometry/CDummyGeometry.hpp
  Common/include/geometry/CGeometry.hpp
  Common/include/geometry/CMultiGridGeometry.hpp
  Common/include/geometry/CPhysicalGeometry.hpp
  Common/include/linear_algebra/CMatrixVectorProduct.hpp
  Common/include/linear_algebra/CPastixWrapper.hpp
  Common/include/linear_algebra/CPreconditioner.hpp
  Common/include/linear_algebra/CSysMatrix.hpp
  Common/include/linear_algebra/CSysMatrix.inl
  Common/include/linear_algebra/CSysSolve.hpp
  Common/include/linear_algebra/CSysSolve_b.hpp
  Common/include/mpi_structure.inl
  Common/include/omp_structure.hpp
  Common/src/CConfig.cpp
  Common/src/adt_structure.cpp
  Common/src/basic_types/ad_structure.cpp
  Common/src/fem/fem_geometry_structure.cpp
  Common/src/fem/geometry_structure_fem_part.cpp
  Common/src/geometry/CDummyGeometry.cpp
  Common/src/geometry/CGeometry.cpp
  Common/src/geometry/CMultiGridGeometry.cpp
  Common/src/geometry/CPhysicalGeometry.cpp
  Common/src/interface_interpolation/CIsoparametric.cpp
  Common/src/linear_algebra/CPastixWrapper.cpp
  Common/src/linear_algebra/CSysMatrix.cpp
  Common/src/linear_algebra/CSysSolve.cpp
  Common/src/linear_algebra/CSysSolve_b.cpp
  Common/src/linear_algebra/CSysVector.cpp
  SU2_CFD/include/gradients/computeGradientsGreenGauss.hpp
  SU2_CFD/include/gradients/computeGradientsLeastSquares.hpp
  SU2_CFD/include/limiters/CLimiterDetails.hpp
  SU2_CFD/include/limiters/computeLimiters.hpp
  SU2_CFD/include/limiters/computeLimiters_impl.hpp
  SU2_CFD/include/output/CMultizoneOutput.hpp
  SU2_CFD/include/output/COutput.hpp
  SU2_CFD/include/output/COutputLegacy.hpp
  SU2_CFD/include/output/filewriter/CFileWriter.hpp
  SU2_CFD/include/solvers/CEulerSolver.hpp
  SU2_CFD/include/solvers/CIncEulerSolver.hpp
  SU2_CFD/include/solvers/CMeshSolver.hpp
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/src/SU2_CFD.cpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/integration/CMultiGridIntegration.cpp
  SU2_CFD/src/integration/CSingleGridIntegration.cpp
  SU2_CFD/src/iteration_structure.cpp
  SU2_CFD/src/numerics/CNumerics.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_CFD/src/solvers/CFEASolver.cpp
  SU2_CFD/src/solvers/CFEM_DG_EulerSolver.cpp
  SU2_CFD/src/solvers/CIncEulerSolver.cpp
  SU2_CFD/src/solvers/CMeshSolver.cpp
  SU2_CFD/src/solvers/CSolver.cpp
  SU2_CFD/src/solvers/CTurbSolver.cpp
  meson.build
Labels: PR: unreviewed, changelog:none, enhancement

#1020 Quasi-Newton convergence acceleration/stabilization of discrete adjoints
  Common/include/CConfig.hpp
  Common/include/mpi_structure.hpp
  Common/include/omp_structure.hpp
  Common/include/toolboxes/CQuasiNewtonInvLeastSquares.hpp
  Common/include/toolboxes/CSymmetricMatrix.hpp
  Common/src/CConfig.cpp
  Common/src/linear_algebra/CSysVector.cpp
  Common/src/toolboxes/CSymmetricMatrix.cpp
  SU2_CFD/include/drivers/CDriver.hpp
  SU2_CFD/include/fluid/CIncIdealGasPolynomial.hpp
  SU2_CFD/include/fluid/CPolynomialConductivity.hpp
  SU2_CFD/include/fluid/CPolynomialConductivityRANS.hpp
  SU2_CFD/include/fluid/CPolynomialViscosity.hpp
  SU2_CFD/src/drivers/CDiscAdjMultizoneDriver.cpp
  SU2_CFD/src/drivers/CDiscAdjSinglezoneDriver.cpp
  SU2_CFD/src/output/CFlowCompOutput.cpp
  SU2_CFD/src/solvers/CSolver.cpp
  TestCases/disc_adj_fea/configAD_fem.cfg
  UnitTests/Common/toolboxes/CQuasiNewtonInvLeastSquares_tests.cpp
  UnitTests/meson.build
  config_template.cfg
Labels: PR: reviewed-approved, changelog:feature
