Repository su2code/SU2, pull requests merged in 2020-03, with the labels that each got.

#897 Fix bug for incompressible FSI cases.
  SU2_CFD/src/interfaces/fsi/CFlowTractionInterface.cpp
Labels: PR: reviewed-approved

#898 makefile fixes and preconfigure version update
  SU2_CFD/obj/Makefile.am
  preconfigure.py
Labels: PR: reviewed-approved

#899 Tutorial test script
  .github/workflows/regression.yml
  Common/src/CConfig.cpp
  TestCases/parallel_regression.py
  TestCases/tutorials.py
Labels: PR: unreviewed

#901 Update to check convergence in elasticity adjoint problems.
  SU2_CFD/src/output/CAdjElasticityOutput.cpp
Labels: PR: unreviewed

#904 move one line of the comment that is misplaced
  SU2_CFD/include/solvers/CDiscAdjSolver.hpp
Labels: PR: reviewed-approved

#916 fixing for support for SST model in C1Dinterpolation
  Common/src/toolboxes/C1DInterpolation.cpp
Labels: PR: reviewed-approved

#908 Hybrid parallel coloring fallback strategies (better strong scaling and user friendliness)
  Common/include/geometry/CGeometry.hpp
  Common/include/linear_algebra/CSysMatrix.hpp
  Common/include/omp_structure.hpp
  Common/include/option_structure.hpp
  Common/include/toolboxes/C1DInterpolation.hpp
  Common/include/toolboxes/graph_toolbox.hpp
  Common/src/CConfig.cpp
  Common/src/geometry/CGeometry.cpp
  Common/src/geometry/CMultiGridGeometry.cpp
  Common/src/geometry/CPhysicalGeometry.cpp
  Common/src/linear_algebra/CSysMatrix.cpp
  Common/src/linear_algebra/CSysSolve.cpp
  SU2_CFD/include/numerics/elasticity/CFEALinearElasticity.hpp
  SU2_CFD/include/solvers/CEulerSolver.hpp
  SU2_CFD/include/solvers/CFEASolver.hpp
  SU2_CFD/include/solvers/CMeshSolver.hpp
  SU2_CFD/include/solvers/CNSSolver.hpp
  SU2_CFD/include/solvers/CTurbSolver.hpp
  SU2_CFD/include/variables/CVariable.hpp
  SU2_CFD/obj/Makefile.am
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/numerics/elasticity/CFEALinearElasticity.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_CFD/src/solvers/CFEASolver.cpp
  SU2_CFD/src/solvers/CMeshSolver.cpp
  SU2_CFD/src/solvers/CNSSolver.cpp
  SU2_CFD/src/solvers/CSolver.cpp
  SU2_CFD/src/solvers/CTurbSASolver.cpp
  SU2_CFD/src/solvers/CTurbSSTSolver.cpp
  SU2_CFD/src/solvers/CTurbSolver.cpp
  TestCases/parallel_regression.py
  TestCases/parallel_regression_AD.py
  TestCases/serial_regression.py
  TestCases/serial_regression_AD.py
  config_template.cfg
Labels: PR: unreviewed, changelog:fix, enhancement

#905 Fix for turbulent viscosity calculation in SST Solver
  SU2_CFD/src/numerics/turbulent/turb_sources.cpp
  TestCases/disc_adj_rans/naca0012/turb_NACA0012_sst.cfg
  TestCases/parallel_regression.py
  TestCases/parallel_regression_AD.py
  TestCases/serial_regression.py
  TestCases/serial_regression_AD.py
  TestCases/turbomachinery/transonic_stator_2D/transonic_stator_rst.cfg
  TestCases/tutorials.py
Labels: PR: unreviewed

#900 Feature restart
  Common/src/CConfig.cpp
  SU2_CFD/include/output/tools/CWindowingTools.hpp
  SU2_CFD/src/output/COutput.cpp
  SU2_CFD/src/output/tools/CWindowingTools.cpp
  SU2_PY/SU2/run/direct.py
  SU2_PY/discrete_adjoint.py
  TestCases/disc_adj_rans/naca0012/naca0012.cfg
  TestCases/parallel_regression_AD.py
Labels: PR: unreviewed
