Repository su2code/SU2, pull requests merged in 2020-02, with the labels that each got.

#859 Important Changes
  Common/include/CConfig.hpp
  Common/include/option_structure.hpp
  Common/include/toolboxes/C1DInterpolation.hpp
  Common/src/toolboxes/C1DInterpolation.cpp
  Common/src/toolboxes/meson.build
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/src/solvers/CSolver.cpp
Labels: PR: unreviewed

#862 Fix SU2 Mesh Writer
  SU2_CFD/src/output/filewriter/CSU2MeshFileWriter.cpp
Labels: PR: reviewed-approved, changelog:fix

#858 Fix error during dry-run and hinder overwrite of history files
  Common/include/omp_structure.hpp
  Common/src/geometry/CGeometry.cpp
  SU2_CFD/include/drivers/CDriver.hpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/drivers/CMultizoneDriver.cpp
  SU2_CFD/src/output/CAdjFlowIncOutput.cpp
  SU2_CFD/src/output/COutput.cpp
  SU2_PY/parallel_computation.py
  SU2_SOL/src/SU2_SOL.cpp
  TestCases/TestCase.py
  TestCases/aeroelastic/aeroelastic_NACA64A010.cfg
  TestCases/cont_adj_euler/naca0012/inv_NACA0012_discadj.cfg
  TestCases/cont_adj_euler/oneram6/inv_ONERAM6.cfg
  TestCases/cont_adj_euler/wedge/inv_wedge_ROE.cfg
  TestCases/cont_adj_navierstokes/cylinder/lam_cylinder.cfg
  TestCases/cont_adj_navierstokes/naca0012_sub/lam_NACA0012.cfg
  TestCases/cont_adj_navierstokes/naca0012_trans/lam_NACA0012.cfg
  TestCases/cont_adj_rans/naca0012/turb_nasa.cfg
  TestCases/cont_adj_rans/rae2822/turb_SA_RAE2822.cfg
  TestCases/disc_adj_fea/configAD_fem.cfg
  TestCases/disc_adj_incomp_euler/naca0012/incomp_NACA0012_disc.cfg
  TestCases/disc_adj_rans/cylinder/cylinder.cfg
  TestCases/disc_adj_rans/cylinder_DT_1ST/cylinder.cfg
  TestCases/euler/oneram6/inv_ONERAM6.cfg
  TestCases/fea_fsi/DynBeam_2d/configBeam_2d.cfg
  TestCases/navierstokes/poiseuille/lam_poiseuille.cfg
  TestCases/parallel_regression.py
  TestCases/parallel_regression_AD.py
  TestCases/serial_regression.py
  TestCases/serial_regression_AD.py
  TestCases/unsteady/square_cylinder/turb_square.cfg
Labels: PR: unreviewed, changelog:fix

#863 1D Interpolation
  Common/include/toolboxes/C1DInterpolation.hpp
  Common/src/toolboxes/C1DInterpolation.cpp
  SU2_CFD/src/solvers/CSolver.cpp
Labels: PR: unreviewed

#864 Inlet intep cylindrical1 d
  Common/include/toolboxes/C1DInterpolation.hpp
  Common/src/toolboxes/C1DInterpolation.cpp
  SU2_CFD/src/solvers/CSolver.cpp
Labels: PR: unreviewed

#865 minor c driver changes and this-> changes
  Common/include/toolboxes/C1DInterpolation.hpp
  SU2_CFD/src/drivers/CDriver.cpp
Labels: PR: unreviewed

#870 Inlet intep cylindrical1 d
  Common/include/toolboxes/C1DInterpolation.hpp
  Common/src/toolboxes/C1DInterpolation.cpp
Labels: PR: unreviewed

#871 Inlet intep cylindrical1 d
  Common/include/toolboxes/C1DInterpolation.hpp
  Common/src/toolboxes/C1DInterpolation.cpp
  SU2_CFD/src/solvers/CSolver.cpp
Labels: PR: unreviewed

#875 Inlet intep cylindrical1 d
  Common/include/toolboxes/C1DInterpolation.hpp
  Common/src/toolboxes/C1DInterpolation.cpp
  SU2_CFD/src/solvers/CSolver.cpp
Labels: PR: unreviewed

#873 Bug fixes for elasticity solver
  Common/include/CConfig.hpp
  Common/include/toolboxes/printing_toolbox.hpp
  Common/src/CConfig.cpp
  README.md
  SU2_CFD/include/output/COutput.hpp
  SU2_CFD/src/iteration_structure.cpp
  SU2_CFD/src/output/CElasticityOutput.cpp
  SU2_CFD/src/output/COutput.cpp
  SU2_CFD/src/solvers/CFEASolver.cpp
Labels: PR: unreviewed

#815 Inlet Spanwise Interpolation
  Common/include/CConfig.hpp
  Common/include/option_structure.hpp
  Common/include/toolboxes/C1DInterpolation.hpp
  Common/src/CConfig.cpp
  Common/src/toolboxes/C1DInterpolation.cpp
  Common/src/toolboxes/meson.build
  SU2_CFD/include/CMarkerProfileReaderFVM.hpp
  SU2_CFD/src/solvers/CSolver.cpp
Labels: PR: unreviewed, changelog:feature

#872 P1 solver for Radiative Heat Transfer
  .gitignore
  Common/include/CConfig.hpp
  Common/include/option_structure.hpp
  Common/src/CConfig.cpp
  Common/src/geometry/CPhysicalGeometry.cpp
  SU2_CFD/include/drivers/CDriver.hpp
  SU2_CFD/include/numerics/CNumerics.hpp
  SU2_CFD/include/numerics/flow/flow_sources.hpp
  SU2_CFD/include/numerics/radiation.hpp
  SU2_CFD/include/output/CAdjFlowIncOutput.hpp
  SU2_CFD/include/solvers/CDiscAdjSolver.hpp
  SU2_CFD/include/solvers/CIncEulerSolver.hpp
  SU2_CFD/include/solvers/CRadP1Solver.hpp
  SU2_CFD/include/solvers/CRadSolver.hpp
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/include/variables/CRadP1Variable.hpp
  SU2_CFD/include/variables/CRadVariable.hpp
  SU2_CFD/include/variables/CVariable.hpp
  SU2_CFD/obj/Makefile.am
  SU2_CFD/src/drivers/CDiscAdjMultizoneDriver.cpp
  SU2_CFD/src/drivers/CDiscAdjSinglezoneDriver.cpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/iteration_structure.cpp
  SU2_CFD/src/meson.build
  SU2_CFD/src/numerics/flow/flow_sources.cpp
  SU2_CFD/src/numerics/radiation.cpp
  SU2_CFD/src/output/CAdjFlowIncOutput.cpp
  SU2_CFD/src/output/CFlowIncOutput.cpp
  SU2_CFD/src/output/COutput.cpp
  SU2_CFD/src/output/output_structure_legacy.cpp
  SU2_CFD/src/python_wrapper_structure.cpp
  SU2_CFD/src/solvers/CDiscAdjSolver.cpp
  SU2_CFD/src/solvers/CIncEulerSolver.cpp
  SU2_CFD/src/solvers/CRadP1Solver.cpp
  SU2_CFD/src/solvers/CRadSolver.cpp
  SU2_CFD/src/variables/CRadP1Variable.cpp
  SU2_CFD/src/variables/CRadVariable.cpp
  SU2_DOT/src/SU2_DOT.cpp
  TestCases/parallel_regression.py
  TestCases/radiation/p1adjoint/configp1adjoint.cfg
  TestCases/radiation/p1model/configp1.cfg
  TestCases/serial_regression.py
  TestCases/serial_regression_AD.py
  config_template.cfg
Labels: PR: unreviewed

#874 Adding change version action and making regression build fail on warning
  .github/workflows/change-version.yml
  .github/workflows/regression.yml
  Common/src/CConfig.cpp
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_PY/change_version_number.py
  externals/cgns/meson.build
  externals/metis/meson.build
  meson.build
Labels: PR: unreviewed, changelog:none

#891 Small BLAS related documentation update
  Common/src/linear_algebra/CPastixWrapper.cpp
  SU2_CFD/src/solvers/CIncNSSolver.cpp
  TestCases/pastix_support/readme.txt
Labels: changelog:none
