Repository su2code/SU2, pull requests merged in 2020-04, with the labels that each got.

#928 Add LES (SGS Models)
  Common/src/CConfig.cpp
  SU2_CFD/include/solvers/CNSSolver.hpp
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/src/output/CFlowCompOutput.cpp
  SU2_CFD/src/solvers/CNSSolver.cpp
Labels: PR: unreviewed

#924 Fix wall distance computation for multizone problems
  Common/include/CConfig.hpp
  Common/include/fem_geometry_structure.hpp
  Common/include/geometry/CGeometry.hpp
  Common/include/geometry/CPhysicalGeometry.hpp
  Common/src/CConfig.cpp
  Common/src/fem_wall_distance.cpp
  Common/src/geometry/CGeometry.cpp
  Common/src/geometry/CPhysicalGeometry.cpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/iteration_structure.cpp
  TestCases/parallel_regression.py
  TestCases/serial_regression.py
Labels: PR: unreviewed, changelog:fix

#927 Fix mass flow calculation near axis for axisymmetric problems
  SU2_CFD/src/output/CFlowOutput.cpp
Labels: PR: unreviewed, changelog:fix

#929 Free memory from direct_iteration and direct_output
  Common/include/CConfig.hpp
  Common/src/geometry/CPhysicalGeometry.cpp
  SU2_CFD/src/drivers/CDiscAdjSinglezoneDriver.cpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/output/output_structure_legacy.cpp
  SU2_DOT/src/SU2_DOT.cpp
  SU2_SOL/src/SU2_SOL.cpp
Labels: PR: unreviewed

#933 CFEASolver CMeshSolver maintenance
  Common/include/CConfig.hpp
  Common/include/geometry/elements/CElement.hpp
  Common/include/linear_algebra/CSysMatrix.hpp
  Common/include/option_structure.hpp
  Common/src/interface_interpolation/CNearestNeighbor.cpp
  Common/src/linear_algebra/CSysMatrix.cpp
  SU2_CFD/include/iteration_structure.hpp
  SU2_CFD/include/solvers/CFEASolver.hpp
  SU2_CFD/include/solvers/CMeshSolver.hpp
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/include/variables/CFEAVariable.hpp
  SU2_CFD/include/variables/CVariable.hpp
  SU2_CFD/src/drivers/CDiscAdjMultizoneDriver.cpp
  SU2_CFD/src/drivers/CDiscAdjSinglezoneDriver.cpp
  SU2_CFD/src/drivers/CMultizoneDriver.cpp
  SU2_CFD/src/integration/CIntegration.cpp
  SU2_CFD/src/integration/CStructuralIntegration.cpp
  SU2_CFD/src/iteration_structure.cpp
  SU2_CFD/src/numerics/elasticity/CFEAElasticity.cpp
  SU2_CFD/src/output/CAdjElasticityOutput.cpp
  SU2_CFD/src/output/CElasticityOutput.cpp
  SU2_CFD/src/solvers/CFEASolver.cpp
  SU2_CFD/src/solvers/CMeshSolver.cpp
  SU2_CFD/src/solvers/CRadP1Solver.cpp
  SU2_CFD/src/solvers/CSolver.cpp
  SU2_PY/topology_optimization.py
  TestCases/fea_fsi/MixElemsKnowles/config.cfg
  TestCases/fea_topology/quick_start/settings.cfg
  TestCases/fea_topology/quick_start/settings_compliance.cfg
  TestCases/fea_topology/quick_start/settings_volfrac.cfg
  TestCases/serial_regression.py
Labels: PR: unreviewed

#935 Call SetSurface_...
  SU2_CFD/src/output/CFlowOutput.cpp
Labels: PR: unreviewed

#941 Output vorticity and Q-criterion in 2D
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/drivers/CSinglezoneDriver.cpp
  SU2_CFD/src/output/CFlowCompOutput.cpp
  SU2_CFD/src/output/CFlowIncOutput.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_CFD/src/solvers/CIncEulerSolver.cpp
  SU2_CFD/src/solvers/CTurbSolver.cpp
Labels: PR: unreviewed

#943 Add the Wtime function to the MPI wrapper (to avoid #ifdefs)
  Common/include/grid_movement_structure.hpp
  Common/include/mpi_structure.hpp
  Common/include/mpi_structure.inl
  Common/src/CConfig.cpp
  SU2_CFD/include/SU2_CFD.hpp
  SU2_CFD/include/definition_structure.hpp
  SU2_CFD/include/iteration_structure.hpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/drivers/CMultizoneDriver.cpp
  SU2_CFD/src/drivers/CSinglezoneDriver.cpp
  SU2_CFD/src/iteration_structure.cpp
  SU2_CFD/src/output/COutput.cpp
  SU2_CFD/src/output/filewriter/CParallelFileWriter.cpp
  SU2_CFD/src/output/filewriter/CParaviewFileWriter.cpp
  SU2_CFD/src/output/filewriter/CSU2FileWriter.cpp
  SU2_CFD/src/output/filewriter/CTecplotBinaryFileWriter.cpp
  SU2_CFD/src/output/filewriter/CTecplotFileWriter.cpp
  SU2_CFD/src/output/output_structure_legacy.cpp
  SU2_DEF/src/SU2_DEF.cpp
  SU2_DOT/src/SU2_DOT.cpp
  SU2_GEO/src/SU2_GEO.cpp
  SU2_MSH/src/SU2_MSH.cpp
  SU2_SOL/include/SU2_SOL.hpp
  SU2_SOL/src/SU2_SOL.cpp
Labels: PR: reviewed-approved

#945 Fix minor spelling for comment in CNumerics
  SU2_CFD/src/numerics/CNumerics.cpp
Labels: PR: reviewed-approved

#958 Quick Start Tutorial Fix
  QuickStart/inv_NACA0012.cfg
Labels: PR: reviewed-approved

#947 Change HEATFLUX to TOTAL_HEATFLUX in output files so that optimizatio…
  SU2_CFD/src/output/CFlowCompOutput.cpp
  SU2_CFD/src/output/CFlowIncOutput.cpp
  SU2_CFD/src/output/CHeatOutput.cpp
  SU2_PY/SU2/io/historyMap.py
  SU2_PY/updateHistoryMap.py
Labels: PR: unreviewed

#950 Small discrete adjoint tweaks and other fixes
  Common/include/CConfig.hpp
  Common/src/CConfig.cpp
  SU2_CFD/include/drivers/CDiscAdjMultizoneDriver.hpp
  SU2_CFD/include/solvers/CFEASolver.hpp
  SU2_CFD/src/drivers/CDiscAdjMultizoneDriver.cpp
  SU2_CFD/src/iteration_structure.cpp
  SU2_CFD/src/solvers/CAdjEulerSolver.cpp
  SU2_CFD/src/solvers/CDiscAdjFEASolver.cpp
  SU2_CFD/src/solvers/CDiscAdjSolver.cpp
  SU2_CFD/src/solvers/CFEASolver.cpp
  SU2_CFD/src/solvers/CSolver.cpp
  TestCases/cont_adj_euler/wedge/inv_wedge_ROE.cfg
  TestCases/cont_adj_euler/wedge/inv_wedge_ROE_multiobj.cfg
  TestCases/deformation/naca4412/def_NACA4412.cfg
  TestCases/disc_adj_euler/arina2k/Arina2KRS.cfg
  TestCases/disc_adj_euler/cylinder3D/inv_cylinder3D.cfg
  TestCases/disc_adj_fsi/Airfoil_2d/configFEA.cfg
  TestCases/optimization_euler/multiobjective_wedge/inv_wedge_ROE_2surf_1obj.cfg
  TestCases/optimization_euler/multiobjective_wedge/inv_wedge_ROE_multiobj.cfg
  TestCases/optimization_euler/multiobjective_wedge/inv_wedge_ROE_multiobj_1surf.cfg
  TestCases/optimization_euler/multiobjective_wedge/inv_wedge_ROE_multiobj_combo.cfg
  TestCases/parallel_regression_AD.py
  TestCases/serial_regression_AD.py
  config_template.cfg
Labels: PR: unreviewed, changelog:fix

#951 (towards) Aero Thermo Elasticity
  Common/include/CConfig.hpp
  Common/include/interface_interpolation/CInterpolator.hpp
  Common/include/mpi_structure.hpp
  Common/src/CConfig.cpp
  Common/src/geometry/CPhysicalGeometry.cpp
  Common/src/grid_movement_structure.cpp
  Common/src/interface_interpolation/CInterpolator.cpp
  Common/src/interface_interpolation/CIsoparametric.cpp
  Common/src/interface_interpolation/CMirror.cpp
  Common/src/interface_interpolation/CNearestNeighbor.cpp
  Common/src/interface_interpolation/CRadialBasisFunction.cpp
  Common/src/interface_interpolation/CSlidingMesh.cpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/interfaces/CInterface.cpp
  SU2_CFD/src/iteration_structure.cpp
  SU2_CFD/src/solvers/CFEASolver.cpp
Labels: PR: unreviewed, changelog:feature

#921 Fix bugs when restarting a shape optimization problem
  SU2_PY/SU2/eval/functions.py
  SU2_PY/SU2/io/data.py
Labels: PR: unreviewed, changelog:fix

#962 Add rotating frame coefficients to the history output.
  SU2_CFD/include/output/CFlowOutput.hpp
  SU2_CFD/src/output/CFlowCompOutput.cpp
  SU2_CFD/src/output/CFlowIncOutput.cpp
  SU2_CFD/src/output/CFlowOutput.cpp
Labels: PR: unreviewed, changelog:fix

#850 Add unit-testing framework to SU2
  .github/workflows/regression.yml
  Common/include/CConfig.hpp
  Common/src/CConfig.cpp
  SU2_CFD/src/meson.build
  SU2_DEF/src/meson.build
  SU2_DOT/src/meson.build
  SU2_PY/pySU2/meson.build
  SU2_SOL/src/meson.build
  UnitTests/Common/geometry/dual_grid/CDualGrid_tests.cpp
  UnitTests/Common/geometry/primal_grid/CPrimalGrid_tests.cpp
  UnitTests/Common/simple_ad_test.cpp
  UnitTests/Common/simple_directdiff_test.cpp
  UnitTests/SU2_CFD/numerics/CNumerics_tests.cpp
  UnitTests/meson.build
  UnitTests/test_driver.cpp
  externals/catch2/LICENSE.txt
  externals/catch2/catch.hpp
  meson.build
  meson_options.txt
Labels: PR: reviewed-approved, enhancement

#965 Fixes for MG in Multizone Disc Adjoint cases, and incompressible time-averaged history output
  SU2_CFD/src/drivers/CDiscAdjMultizoneDriver.cpp
  SU2_CFD/src/output/CFlowIncOutput.cpp
Labels: PR: reviewed-approved, changelog:fix
