Repository su2code/SU2, pull requests merged in 2020-11, with the labels that each got.

#1101 Fix meson init script
  meson_scripts/init.py
  preconfigure.py
Labels: PR: partially-approved, changelog:none

#1102 Add an option to meson for extra dependencies (to fix mpich and lapack issues)
  Common/include/parallelization/vectorization.hpp
  meson.build
  meson_options.txt
Labels: PR: reviewed-approved, changelog:fix

#1104 Mesh Quality metrics output
  Common/src/CConfig.cpp
  SU2_CFD/src/output/CFlowCompOutput.cpp
  SU2_CFD/src/output/CFlowIncOutput.cpp
  SU2_CFD/src/output/CHeatOutput.cpp
  SU2_CFD/src/output/CMeshOutput.cpp
Labels: PR: reviewed-approved, changelog:fix

#1105 Nan checks and better discrete adjoint default options
  Common/src/CConfig.cpp
  SU2_CFD/src/output/COutput.cpp
  config_template.cfg
Labels: PR: unreviewed, changelog:feature

#1111 Updates to NEMO solvers
  Common/include/CConfig.hpp
  Common/include/option_structure.hpp
  Common/src/CConfig.cpp
  SU2_CFD/include/CMarkerProfileReaderFVM.hpp
  SU2_CFD/include/fluid/CMutationTCLib.hpp
  SU2_CFD/include/fluid/CNEMOGas.hpp
  SU2_CFD/include/fluid/CUserDefinedTCLib.hpp
  SU2_CFD/include/numerics/NEMO/CNEMONumerics.hpp
  SU2_CFD/include/numerics/NEMO/NEMO_diffusion.hpp
  SU2_CFD/include/numerics/NEMO/convection/ausmplusup2.hpp
  SU2_CFD/include/numerics/NEMO/convection/msw.hpp
  SU2_CFD/include/output/CNEMOCompOutput.hpp
  SU2_CFD/include/solvers/CNEMOEulerSolver.hpp
  SU2_CFD/include/solvers/CNEMONSSolver.hpp
  SU2_CFD/include/variables/CNEMOEulerVariable.hpp
  SU2_CFD/include/variables/CNEMONSVariable.hpp
  SU2_CFD/src/fluid/CMutationTCLib.cpp
  SU2_CFD/src/fluid/CNEMOGas.cpp
  SU2_CFD/src/fluid/CUserDefinedTCLib.cpp
  SU2_CFD/src/numerics/NEMO/CNEMONumerics.cpp
  SU2_CFD/src/numerics/NEMO/NEMO_diffusion.cpp
  SU2_CFD/src/numerics/NEMO/NEMO_sources.cpp
  SU2_CFD/src/numerics/NEMO/convection/ausmpwplus.cpp
  SU2_CFD/src/numerics/NEMO/convection/lax.cpp
  SU2_CFD/src/numerics/NEMO/convection/msw.cpp
  SU2_CFD/src/numerics/NEMO/convection/roe.cpp
  SU2_CFD/src/output/CNEMOCompOutput.cpp
  SU2_CFD/src/solvers/CNEMOEulerSolver.cpp
  SU2_CFD/src/solvers/CNEMONSSolver.cpp
  SU2_CFD/src/variables/CNEMOEulerVariable.cpp
  SU2_CFD/src/variables/CNEMONSVariable.cpp
  TestCases/nonequilibrium/viscwedge/viscwedge.cfg
  TestCases/parallel_regression.py
  TestCases/serial_regression.py
Labels: PR: reviewed-approved

#1113 Fix for nDim initialization causing macos builds in develop
  SU2_CFD/src/fluid/CNEMOGas.cpp
Labels: PR: reviewed-approved

#1114 Windows Git Fix
  SU2_CFD/include/fluid/ 
Labels: PR: reviewed-approved
