Repository su2code/SU2, pull requests merged in 2020-12, with the labels that each got.

#1107 Heat solver fixes for primal and adjoint CHT simulations
  Common/include/CConfig.hpp
  Common/src/CConfig.cpp
  Common/src/geometry/CPhysicalGeometry.cpp
  Common/src/linear_algebra/CSysSolve.cpp
  SU2_CFD/include/drivers/CDiscAdjSinglezoneDriver.hpp
  SU2_CFD/include/iteration/CHeatIteration.hpp
  SU2_CFD/include/solvers/CDiscAdjFEASolver.hpp
  SU2_CFD/include/solvers/CDiscAdjMeshSolver.hpp
  SU2_CFD/include/solvers/CDiscAdjSolver.hpp
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/src/drivers/CDiscAdjMultizoneDriver.cpp
  SU2_CFD/src/drivers/CDiscAdjSinglezoneDriver.cpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/iteration/CDiscAdjHeatIteration.cpp
  SU2_CFD/src/iteration/CFluidIteration.cpp
  SU2_CFD/src/iteration/CHeatIteration.cpp
  SU2_CFD/src/output/CAdjElasticityOutput.cpp
  SU2_CFD/src/output/CAdjHeatOutput.cpp
  SU2_CFD/src/output/CFlowIncOutput.cpp
  SU2_CFD/src/output/COutput.cpp
  SU2_CFD/src/solvers/CDiscAdjFEASolver.cpp
  SU2_CFD/src/solvers/CDiscAdjMeshSolver.cpp
  SU2_CFD/src/solvers/CDiscAdjSolver.cpp
  SU2_CFD/src/solvers/CHeatSolver.cpp
  SU2_DEF/src/SU2_DEF.cpp
  TestCases/parallel_regression.py
  TestCases/parallel_regression_AD.py
  TestCases/serial_regression.py
  TestCases/serial_regression_AD.py
Labels: PR: unreviewed, changelog:fix

#1115 Cleaning parts of the legacy output
  Common/include/CConfig.hpp
  Common/src/CConfig.cpp
  SU2_CFD/include/output/COutputLegacy.hpp
  SU2_CFD/include/output/output_structure_legacy.inl
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_CFD/src/output/output_structure_legacy.cpp
  SU2_CFD/src/solvers/CNEMOEulerSolver.cpp
  SU2_DEF/src/SU2_DEF.cpp
Labels: PR: reviewed-approved, changelog:chore

#1067 Fixes for incompressible solver - rotating frame and convergence rate for unsteady problems
  Common/include/CConfig.hpp
  Common/src/CConfig.cpp
  SU2_CFD/include/numerics/flow/convection/centered.hpp
  SU2_CFD/src/numerics/flow/convection/centered.cpp
  SU2_CFD/src/solvers/CIncEulerSolver.cpp
  SU2_PY/SU2/eval/gradients.py
  SU2_PY/finite_differences.py
  TestCases/parallel_regression.py
  TestCases/serial_regression.py
Labels: PR: unreviewed, changelog:fix

#1128 Actuator Disk Tutorial
  TestCases/hybrid_regression.py
  TestCases/parallel_regression.py
  TestCases/serial_regression.py
  TestCases/tutorials.py
Labels: PR: reviewed-approved

#1127 Introduce a function to compute stress tensor
  SU2_CFD/include/numerics/CNumerics.hpp
  SU2_CFD/include/numerics/flow/flow_diffusion.hpp
  SU2_CFD/include/numerics/turbulent/turb_sources.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/src/interfaces/fsi/CFlowTractionInterface.cpp
  SU2_CFD/src/numerics/NEMO/CNEMONumerics.cpp
  SU2_CFD/src/numerics/flow/flow_diffusion.cpp
  SU2_CFD/src/numerics/flow/flow_sources.cpp
  SU2_CFD/src/numerics/turbulent/turb_sources.cpp
  SU2_CFD/src/python_wrapper_structure.cpp
  SU2_CFD/src/solvers/CAdjNSSolver.cpp
  SU2_CFD/src/solvers/CNEMONSSolver.cpp
  SU2_CFD/src/solvers/CNSSolver.cpp
  SU2_CFD/src/solvers/CSolver.cpp
  TestCases/hybrid_regression.py
  TestCases/parallel_regression.py
  TestCases/serial_regression.py
Labels: PR: unreviewed, changelog:chore

#1068 Added CSquareMatrixCM to the toolboxes
  Common/include/blas_structure.hpp
  Common/include/containers/C2DContainer.hpp
  Common/include/toolboxes/CSquareMatrixCM.hpp
  Common/include/toolboxes/CSymmetricMatrix.hpp
  Common/lib/Makefile.am
  Common/src/toolboxes/CSquareMatrixCM.cpp
  Common/src/toolboxes/CSymmetricMatrix.cpp
  Common/src/toolboxes/meson.build
Labels: PR: unreviewed

#1106 Axisymmetric problems : Viscous source terms and generalised convective source terms and jacobian
  Common/include/option_structure.hpp
  SU2_CFD/include/numerics/CNumerics.hpp
  SU2_CFD/include/numerics/flow/flow_sources.hpp
  SU2_CFD/include/solvers/CAdjEulerSolver.hpp
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/include/variables/CVariable.hpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/numerics/flow/flow_sources.cpp
  SU2_CFD/src/solvers/CAdjEulerSolver.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_CFD/src/solvers/CFEASolver.cpp
  SU2_CFD/src/solvers/CIncEulerSolver.cpp
  SU2_CFD/src/solvers/CSolver.cpp
  SU2_CFD/src/variables/CAdjEulerVariable.cpp
  SU2_CFD/src/variables/CEulerVariable.cpp
  SU2_CFD/src/variables/CFEAVariable.cpp
  SU2_CFD/src/variables/CIncEulerVariable.cpp
  SU2_CFD/src/variables/CIncNSVariable.cpp
Labels: PR: unreviewed, changelog:feature

#1117 Further NEMO cleanup and improvements
  Common/src/CConfig.cpp
  SU2_CFD/include/fluid/CMutationTCLib.hpp
  SU2_CFD/include/fluid/CNEMOGas.hpp
  SU2_CFD/include/fluid/CUserDefinedTCLib.hpp
  SU2_CFD/include/numerics/CNumerics.hpp
  SU2_CFD/include/numerics/NEMO/CNEMONumerics.hpp
  SU2_CFD/include/numerics/NEMO/NEMO_sources.hpp
  SU2_CFD/include/numerics/NEMO/convection/ausmplusup2.hpp
  SU2_CFD/include/numerics/NEMO/convection/ausmpwplus.hpp
  SU2_CFD/include/numerics/NEMO/convection/lax.hpp
  SU2_CFD/include/output/COutputLegacy.hpp
  SU2_CFD/include/variables/CNEMOEulerVariable.hpp
  SU2_CFD/obj/Makefile.am
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/fluid/CMutationTCLib.cpp
  SU2_CFD/src/fluid/CNEMOGas.cpp
  SU2_CFD/src/fluid/CUserDefinedTCLib.cpp
  SU2_CFD/src/numerics/CNumerics.cpp
  SU2_CFD/src/numerics/NEMO/CNEMONumerics.cpp
  SU2_CFD/src/numerics/NEMO/NEMO_diffusion.cpp
  SU2_CFD/src/numerics/NEMO/NEMO_sources.cpp
  SU2_CFD/src/numerics/NEMO/convection/ausm.cpp
  SU2_CFD/src/numerics/NEMO/convection/ausmplusup2.cpp
  SU2_CFD/src/numerics/NEMO/convection/ausmpwplus.cpp
  SU2_CFD/src/numerics/NEMO/convection/lax.cpp
  SU2_CFD/src/numerics/NEMO/convection/msw.cpp
  SU2_CFD/src/numerics/NEMO/convection/roe.cpp
  SU2_CFD/src/output/output_structure_legacy.cpp
  SU2_CFD/src/solvers/CNEMOEulerSolver.cpp
  SU2_CFD/src/solvers/CNEMONSSolver.cpp
  SU2_CFD/src/variables/CNEMOEulerVariable.cpp
  SU2_CFD/src/variables/CNEMONSVariable.cpp
  TestCases/nonequilibrium/invwedge/invwedge.cfg
  TestCases/nonequilibrium/viscwedge/viscwedge.cfg
  TestCases/parallel_regression.py
  TestCases/serial_regression.py
Labels: PR: unreviewed

#1135 Removing the tabs in all files
  Common/include/geometry/CGeometry.hpp
  Common/include/option_structure.hpp
  Common/src/geometry/CPhysicalGeometry.cpp
  Common/src/geometry/elements/CHEXA8.cpp
  Common/src/geometry/elements/CTETRA1.cpp
  SU2_CFD/src/output/output_physics.cpp
  SU2_CFD/src/output/output_structure_legacy.cpp
  SU2_GEO/src/SU2_GEO.cpp
  SU2_SOL/src/SU2_SOL.cpp
Labels: PR: reviewed-approved, changelog:chore

#1137 Update Area computations with the geometry toolbox
  Common/src/geometry/CMultiGridGeometry.cpp
  Common/src/geometry/CPhysicalGeometry.cpp
  Common/src/interface_interpolation/CSlidingMesh.cpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/src/interfaces/cht/CConjugateHeatInterface.cpp
  SU2_CFD/src/numerics/NEMO/NEMO_diffusion.cpp
  SU2_CFD/src/numerics/NEMO/convection/ausm.cpp
  SU2_CFD/src/numerics/NEMO/convection/ausmplusup2.cpp
  SU2_CFD/src/numerics/NEMO/convection/ausmpwplus.cpp
  SU2_CFD/src/numerics/NEMO/convection/lax.cpp
  SU2_CFD/src/numerics/NEMO/convection/msw.cpp
  SU2_CFD/src/numerics/NEMO/convection/roe.cpp
  SU2_CFD/src/numerics/continuous_adjoint/adj_convection.cpp
  SU2_CFD/src/numerics/flow/convection/ausm_slau.cpp
  SU2_CFD/src/numerics/flow/convection/centered.cpp
  SU2_CFD/src/numerics/flow/convection/cusp.cpp
  SU2_CFD/src/numerics/flow/convection/fds.cpp
  SU2_CFD/src/numerics/flow/convection/fvs.cpp
  SU2_CFD/src/numerics/flow/convection/hllc.cpp
  SU2_CFD/src/numerics/flow/convection/roe.cpp
  SU2_CFD/src/numerics/flow/flow_diffusion.cpp
  SU2_CFD/src/numerics/heat.cpp
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_CFD/src/python_wrapper_structure.cpp
  SU2_CFD/src/solvers/CAdjEulerSolver.cpp
  SU2_CFD/src/solvers/CAdjNSSolver.cpp
  SU2_CFD/src/solvers/CDiscAdjSolver.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_CFD/src/solvers/CHeatSolver.cpp
  SU2_CFD/src/solvers/CIncEulerSolver.cpp
  SU2_CFD/src/solvers/CIncNSSolver.cpp
  SU2_CFD/src/solvers/CNEMOEulerSolver.cpp
  SU2_CFD/src/solvers/CNEMONSSolver.cpp
  SU2_CFD/src/solvers/CNSSolver.cpp
  SU2_CFD/src/solvers/CRadP1Solver.cpp
  SU2_CFD/src/solvers/CTurbSASolver.cpp
  SU2_CFD/src/solvers/CTurbSSTSolver.cpp
Labels: PR: reviewed-approved, changelog:chore

#1138 Fix compiler warnings
  Common/src/geometry/CMultiGridGeometry.cpp
  Common/src/toolboxes/CSquareMatrixCM.cpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/src/interfaces/cht/CConjugateHeatInterface.cpp
  SU2_CFD/src/numerics/NEMO/convection/lax.cpp
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_CFD/src/python_wrapper_structure.cpp
  SU2_CFD/src/solvers/CAdjEulerSolver.cpp
  SU2_CFD/src/solvers/CAdjNSSolver.cpp
  SU2_CFD/src/solvers/CFEM_DG_EulerSolver.cpp
  SU2_CFD/src/solvers/CHeatSolver.cpp
  SU2_CFD/src/solvers/CIncEulerSolver.cpp
  SU2_CFD/src/solvers/CNEMOEulerSolver.cpp
  SU2_CFD/src/solvers/CNEMONSSolver.cpp
  SU2_CFD/src/solvers/CRadP1Solver.cpp
  SU2_CFD/src/solvers/CTurbSASolver.cpp
  SU2_CFD/src/solvers/CTurbSSTSolver.cpp
Labels: PR: unreviewed, changelog:none

#1076 Added prevention of intersections in grid elements after deformation
  Common/include/CConfig.hpp
  Common/include/geometry/CGeometry.hpp
  Common/include/grid_movement/CSurfaceMovement.hpp
  Common/include/grid_movement/CVolumetricMovement.hpp
  Common/src/CConfig.cpp
  Common/src/grid_movement/CSurfaceMovement.cpp
  Common/src/grid_movement/CVolumetricMovement.cpp
  SU2_DEF/src/SU2_DEF.cpp
  config_template.cfg
Labels: PR: unreviewed, changelog:feature

#1142 Address comments from #1076...
  Common/include/CConfig.hpp
  Common/include/geometry/CGeometry.hpp
  Common/include/grid_movement/CGridMovement.hpp
  Common/include/grid_movement/CSurfaceMovement.hpp
  Common/src/grid_movement/CSurfaceMovement.cpp
  Common/src/grid_movement/CVolumetricMovement.cpp
  SU2_DEF/src/SU2_DEF.cpp
Labels: PR: unreviewed, changelog:none

#1147 fix variable lenght arrays
  Common/src/grid_movement/CVolumetricMovement.cpp
Labels: PR: unreviewed, changelog:none
