Repository su2code/SU2, pull requests merged in 2020-09, with the labels that each got.

#1035 Restructure grid_movement and adt_structure, remove SU2_MSH and grid_adaptation
  Common/include/adt/CADTBaseClass.hpp
  Common/include/adt/CADTComparePointClass.hpp
  Common/include/adt/CADTElemClass.hpp
  Common/include/adt/CADTNodeClass.hpp
  Common/include/adt/CADTPointsOnlyClass.hpp
  Common/include/adt/CBBoxTargetClass.hpp
  Common/include/geometry/CGeometry.hpp
  Common/include/grid_adaptation_structure.hpp
  Common/include/grid_movement/CBSplineBlending.hpp
  Common/include/grid_movement/CBezierBlending.hpp
  Common/include/grid_movement/CFreeFormBlending.hpp
  Common/include/grid_movement/CFreeFormDefBox.hpp
  Common/include/grid_movement/CGridMovement.hpp
  Common/include/grid_movement/CSurfaceMovement.hpp
  Common/include/grid_movement/CVolumetricMovement.hpp
  Common/include/grid_movement_structure.hpp
  Common/include/grid_movement_structure.inl
  Common/lib/Makefile.am
  Common/src/adt/CADTBaseClass.cpp
  Common/src/adt/CADTElemClass.cpp
  Common/src/adt/CADTPointsOnlyClass.cpp
  Common/src/adt/meson.build
  Common/src/fem/fem_geometry_structure.cpp
  Common/src/fem/fem_wall_distance.cpp
  Common/src/fem/geometry_structure_fem_part.cpp
  Common/src/geometry/CPhysicalGeometry.cpp
  Common/src/grid_adaptation_structure.cpp
  Common/src/grid_movement/CBSplineBlending.cpp
  Common/src/grid_movement/CBezierBlending.cpp
  Common/src/grid_movement/CFreeFormBlending.cpp
  Common/src/grid_movement/CFreeFormDefBox.cpp
  Common/src/grid_movement/CGridMovement.cpp
  Common/src/grid_movement/CSurfaceMovement.cpp
  Common/src/grid_movement/CVolumetricMovement.cpp
  Common/src/grid_movement/meson.build
  Common/src/grid_movement_structure.cpp
  Common/src/meson.build
  Makefile.am
  SU2_CFD/include/drivers/CDriver.hpp
  SU2_CFD/include/iteration/CIteration.hpp
  SU2_CFD/include/solvers/CFEASolver.hpp
  SU2_CFD/include/solvers/CNEMOEulerSolver.hpp
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_CFD/src/solvers/CMeshSolver.cpp
  SU2_DEF/include/SU2_DEF.hpp
  SU2_DOT/include/SU2_DOT.hpp
  SU2_GEO/include/SU2_GEO.hpp
  SU2_MSH/bin/.gitignore
  SU2_MSH/obj/Makefile.am
  SU2_MSH/src/SU2_MSH.cpp
  SU2_MSH/src/meson.build
  configure.ac
  meson.build
  preconfigure.py
Labels: PR: unreviewed, changelog:chore

#1071 Cleanup native ASCII file writers
  SU2_CFD/include/output/filewriter/CSU2FileWriter.hpp
  SU2_CFD/include/output/filewriter/CSU2MeshFileWriter.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/include/solvers/CNEMOEulerSolver.hpp
  SU2_CFD/include/variables/CVariable.hpp
  SU2_CFD/src/output/filewriter/CSU2FileWriter.cpp
  SU2_CFD/src/output/filewriter/CSU2MeshFileWriter.cpp
  SU2_CFD/src/solvers/CNEMOEulerSolver.cpp
  SU2_CFD/src/variables/CEulerVariable.cpp
  SU2_CFD/src/variables/CIncEulerVariable.cpp
  SU2_CFD/src/variables/CIncNSVariable.cpp
  SU2_CFD/src/variables/CNSVariable.cpp
Labels: PR: unreviewed, changelog:fix

#1070 OptimalPropeller Python Script
  SU2_PY/OptimalPropeller.py
Labels: PR: unreviewed

#1061 Fix multi-physics simulations with "many-to-many" interfaces between markers and improve associated communications.
  Common/include/CConfig.hpp
  Common/include/geometry/dual_grid/CVertex.hpp
  Common/include/interface_interpolation/CInterpolator.hpp
  Common/include/interface_interpolation/CInterpolatorFactory.hpp
  Common/include/interface_interpolation/CIsoparametric.hpp
  Common/include/interface_interpolation/CMirror.hpp
  Common/include/interface_interpolation/CNearestNeighbor.hpp
  Common/include/interface_interpolation/CRadialBasisFunction.hpp
  Common/include/interface_interpolation/CSlidingMesh.hpp
  Common/src/CConfig.cpp
  Common/src/geometry/CGeometry.cpp
  Common/src/geometry/CPhysicalGeometry.cpp
  Common/src/geometry/dual_grid/CVertex.cpp
  Common/src/interface_interpolation/CInterpolatorFactory.cpp
  Common/src/interface_interpolation/CIsoparametric.cpp
  Common/src/interface_interpolation/CMirror.cpp
  Common/src/interface_interpolation/CNearestNeighbor.cpp
  Common/src/interface_interpolation/CRadialBasisFunction.cpp
  Common/src/interface_interpolation/CSlidingMesh.cpp
  SU2_CFD/include/drivers/CDiscAdjMultizoneDriver.hpp
  SU2_CFD/include/drivers/CDriver.hpp
  SU2_CFD/include/interfaces/CInterface.hpp
  SU2_CFD/include/interfaces/cfd/CConservativeVarsInterface.hpp
  SU2_CFD/include/interfaces/cfd/CMixingPlaneInterface.hpp
  SU2_CFD/include/interfaces/cfd/CSlidingInterface.hpp
  SU2_CFD/include/interfaces/cht/CConjugateHeatInterface.hpp
  SU2_CFD/include/interfaces/fsi/CDiscAdjFlowTractionInterface.hpp
  SU2_CFD/include/interfaces/fsi/CDisplacementsInterface.hpp
  SU2_CFD/include/interfaces/fsi/CFlowTractionInterface.hpp
  SU2_CFD/include/iteration/CFEAIteration.hpp
  SU2_CFD/include/solvers/CEulerSolver.hpp
  SU2_CFD/include/solvers/CFEASolver.hpp
  SU2_CFD/include/solvers/CTurbSolver.hpp
  SU2_CFD/src/CMarkerProfileReaderFVM.cpp
  SU2_CFD/src/definition_structure.cpp
  SU2_CFD/src/drivers/CDiscAdjMultizoneDriver.cpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/drivers/CMultizoneDriver.cpp
  SU2_CFD/src/interfaces/CInterface.cpp
  SU2_CFD/src/interfaces/cfd/CConservativeVarsInterface.cpp
  SU2_CFD/src/interfaces/cfd/CMixingPlaneInterface.cpp
  SU2_CFD/src/interfaces/cfd/CSlidingInterface.cpp
  SU2_CFD/src/interfaces/cht/CConjugateHeatInterface.cpp
  SU2_CFD/src/interfaces/fsi/CDiscAdjFlowTractionInterface.cpp
  SU2_CFD/src/interfaces/fsi/CDisplacementsInterface.cpp
  SU2_CFD/src/interfaces/fsi/CFlowTractionInterface.cpp
  SU2_CFD/src/iteration/CDiscAdjFEAIteration.cpp
  SU2_CFD/src/iteration/CFEAIteration.cpp
  SU2_CFD/src/solvers/CDiscAdjSolver.cpp
  SU2_CFD/src/solvers/CFEASolver.cpp
  SU2_CFD/src/solvers/CTurbSolver.cpp
  SU2_CFD/src/variables/CFEAVariable.cpp
Labels: PR: unreviewed, changelog:fix

#1077 Fix memory issues
  Common/include/CConfig.hpp
  Common/src/CConfig.cpp
  SU2_CFD/src/output/filewriter/CParallelDataSorter.cpp
Labels: PR: reviewed-approved

#1074 Fix EFFICIENCY calculation
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
Labels: PR: unreviewed, changelog:fix
