Repository su2code/SU2, pull requests merged in 2020-10, with the labels that each got.

#1078 NEMO ONLY (not develop): Update some structures within NEMO, more in line with develop
  SU2_CFD/include/numerics/NEMO/CNEMONumerics.hpp
  SU2_CFD/include/numerics/NEMO/NEMO_diffusion.hpp
  SU2_CFD/include/solvers/CNEMOEulerSolver.hpp
  SU2_CFD/include/solvers/CNEMONSSolver.hpp
  SU2_CFD/include/variables/CNEMOEulerVariable.hpp
  SU2_CFD/include/variables/CNEMONSVariable.hpp
  SU2_CFD/src/numerics/NEMO/CNEMONumerics.cpp
  SU2_CFD/src/numerics/NEMO/NEMO_diffusion.cpp
  SU2_CFD/src/solvers/CNEMOEulerSolver.cpp
  SU2_CFD/src/solvers/CNEMONSSolver.cpp
  SU2_CFD/src/variables/CNEMOEulerVariable.cpp
  SU2_CFD/src/variables/CNEMONSVariable.cpp
Labels: PR: reviewed-approved

#1080 Fix develop compilation on some compilers
  Common/include/containers/C2DContainer.hpp
  Common/include/parallelization/special_vectorization.hpp
Labels: PR: reviewed-approved, changelog:none

#1082 Fix #1081
  Common/include/basic_types/datatype_structure.hpp
  Common/include/containers/C2DContainer.hpp
  Common/include/mpi_structure.inl
  Common/src/CConfig.cpp
  Common/src/mpi_structure.cpp
  SU2_CFD/include/numerics/CNumerics.hpp
  SU2_CFD/include/numerics_simd/flow/convection/centered.hpp
  SU2_CFD/include/numerics_simd/flow/convection/roe.hpp
  SU2_CFD/include/numerics_simd/util.hpp
  externals/cgns/meson.build
  externals/metis/meson.build
  meson.build
Labels: PR: unreviewed, changelog:none

#1091 Fix or silence a few Intel compilation warnings
  Common/include/basic_types/datatype_structure.hpp
  Common/include/containers/C2DContainer.hpp
  Common/include/geometry/elements/CElement.hpp
  Common/include/geometry/meshreader/CMeshReaderFVM.hpp
  Common/include/geometry/primal_grid/CPrimalGrid.hpp
  Common/include/geometry/primal_grid/CPrimalGridBoundFEM.hpp
  Common/include/geometry/primal_grid/CPrimalGridFEM.hpp
  Common/include/linear_algebra/CSysMatrix.hpp
  Common/include/linear_algebra/CSysVector.hpp
  Common/include/omp_structure.hpp
  Common/src/geometry/CPhysicalGeometry.cpp
  Common/src/geometry/meshreader/CMeshReaderFVM.cpp
  SU2_CFD/include/gradients/computeGradientsLeastSquares.hpp
  SU2_CFD/src/fluid/CUserDefinedTCLib.cpp
Labels: PR: unreviewed, changelog:fix

#1092 Fixed the pedantic warnings in SU2 itself and some in the tecio sources
  Common/include/option_structure.hpp
  Common/src/blas_structure.cpp
  Common/src/toolboxes/CSymmetricMatrix.cpp
  SU2_CFD/src/interfaces/CInterface.cpp
  SU2_CFD/src/solvers/CFEM_DG_EulerSolver.cpp
  SU2_CFD/src/solvers/CFEM_DG_NSSolver.cpp
  SU2_CFD/src/solvers/CNEMOEulerSolver.cpp
  externals/tecio/teciompisrc/AnyTypeLightweightVector.h
  externals/tecio/teciompisrc/ClassicFEZoneWriter.h
  externals/tecio/teciompisrc/ClassicOrderedZoneWriter.h
  externals/tecio/teciompisrc/CszConnectivity.h
  externals/tecio/teciompisrc/FECellSubzoneCompressor.h
  externals/tecio/teciompisrc/FEZoneInfo.h
  externals/tecio/teciompisrc/FileIOStream.h
  externals/tecio/teciompisrc/FileStreamReader.h
  externals/tecio/teciompisrc/FileStreamWriter.h
  externals/tecio/teciompisrc/IntervalTree.h
  externals/tecio/teciompisrc/ItemSetIterator.h
  externals/tecio/teciompisrc/MPIFileIOStream.h
  externals/tecio/teciompisrc/MPIFileReader.h
  externals/tecio/teciompisrc/MPIFileWriter.h
  externals/tecio/teciompisrc/MinMaxTree.h
  externals/tecio/teciompisrc/ORBFESubzonePartitioner.h
  externals/tecio/teciompisrc/OrthogonalBisection.h
  externals/tecio/teciompisrc/PartitionMetadata.h
  externals/tecio/teciompisrc/SZLOrderedZoneWriter.h
  externals/tecio/teciompisrc/SzlFileLoader.h
  externals/tecio/teciompisrc/ZoneMetadata.h
  externals/tecio/teciompisrc/mpiDatatype.cpp
  externals/tecio/teciompisrc/xyz.h
Labels: PR: unreviewed

#1097 Fix rough wall model in SST turbulence model
  SU2_CFD/include/solvers/CFVMFlowSolverBase.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/src/solvers/CTurbSSTSolver.cpp
Labels: PR: unreviewed, changelog:fix
