Repository su2code/SU2, pull requests merged in 2020-05, with the labels that each got.

#959 Contiguous storage of CEdge(s)
  Common/include/geometry/CGeometry.hpp
  Common/include/geometry/dual_grid/CEdge.hpp
  Common/include/geometry/primal_grid/CPrimalGrid.hpp
  Common/include/option_structure.hpp
  Common/include/toolboxes/graph_toolbox.hpp
  Common/src/fem_geometry_structure.cpp
  Common/src/geometry/CDummyGeometry.cpp
  Common/src/geometry/CGeometry.cpp
  Common/src/geometry/CMultiGridGeometry.cpp
  Common/src/geometry/CPhysicalGeometry.cpp
  Common/src/geometry/dual_grid/CEdge.cpp
  Common/src/geometry/primal_grid/CPrimalGrid.cpp
  Common/src/grid_adaptation_structure.cpp
  Common/src/interface_interpolation/CInterpolator.cpp
  Common/src/linear_algebra/CSysMatrix.cpp
  Common/src/linear_algebra/CSysVector.cpp
  SU2_CFD/include/gradients/computeGradientsGreenGauss.hpp
  SU2_CFD/include/numerics/CNumerics.hpp
  SU2_CFD/include/solvers/CEulerSolver.hpp
  SU2_CFD/include/solvers/CFEM_DG_EulerSolver.hpp
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/include/solvers/CTurbSASolver.hpp
  SU2_CFD/include/solvers/CTurbSSTSolver.hpp
  SU2_CFD/include/solvers/CTurbSolver.hpp
  SU2_CFD/src/drivers/CDiscAdjMultizoneDriver.cpp
  SU2_CFD/src/integration/CFEM_DG_Integration.cpp
  SU2_CFD/src/integration/CMultiGridIntegration.cpp
  SU2_CFD/src/integration/CSingleGridIntegration.cpp
  SU2_CFD/src/iteration_structure.cpp
  SU2_CFD/src/numerics/CNumerics.cpp
  SU2_CFD/src/numerics/turbulent/turb_diffusion.cpp
  SU2_CFD/src/solvers/CAdjEulerSolver.cpp
  SU2_CFD/src/solvers/CAdjNSSolver.cpp
  SU2_CFD/src/solvers/CAdjTurbSolver.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_CFD/src/solvers/CFEM_DG_EulerSolver.cpp
  SU2_CFD/src/solvers/CHeatSolver.cpp
  SU2_CFD/src/solvers/CIncEulerSolver.cpp
  SU2_CFD/src/solvers/CIncNSSolver.cpp
  SU2_CFD/src/solvers/CNSSolver.cpp
  SU2_CFD/src/solvers/CRadP1Solver.cpp
  SU2_CFD/src/solvers/CSolver.cpp
  SU2_CFD/src/solvers/CTransLMSolver.cpp
  SU2_CFD/src/solvers/CTurbSASolver.cpp
  SU2_CFD/src/solvers/CTurbSSTSolver.cpp
  SU2_CFD/src/solvers/CTurbSolver.cpp
  UnitTests/Common/geometry/dual_grid/CDualGrid_tests.cpp
Labels: PR: unreviewed, changelog:chore, enhancement

#963 Multigrid and preprocessing efficiency tweaks
  Common/include/CMultiGridQueue.hpp
  Common/include/adt_structure.hpp
  Common/include/adt_structure.inl
  Common/include/geometry/CGeometry.hpp
  Common/include/geometry/CPhysicalGeometry.hpp
  Common/include/toolboxes/CFastFindAndEraseQueue.hpp
  Common/src/CConfig.cpp
  Common/src/CMultiGridQueue.cpp
  Common/src/adt_structure.cpp
  Common/src/geometry/CPhysicalGeometry.cpp
  SU2_CFD/include/solvers/CEulerSolver.hpp
  SU2_CFD/src/drivers/CDiscAdjMultizoneDriver.cpp
  SU2_CFD/src/drivers/CMultizoneDriver.cpp
  SU2_CFD/src/drivers/CSinglezoneDriver.cpp
  SU2_CFD/src/integration/CMultiGridIntegration.cpp
  SU2_CFD/src/iteration_structure.cpp
  SU2_CFD/src/numerics/flow/convection/ausm_slau.cpp
  SU2_CFD/src/numerics/flow/convection/centered.cpp
  SU2_CFD/src/numerics/flow/convection/cusp.cpp
  SU2_CFD/src/numerics/flow/convection/fvs.cpp
  SU2_CFD/src/numerics/flow/convection/hllc.cpp
  SU2_CFD/src/numerics/flow/convection/roe.cpp
  SU2_CFD/src/numerics/flow/flow_diffusion.cpp
  SU2_CFD/src/output/COutput.cpp
  SU2_CFD/src/solvers/CAdjEulerSolver.cpp
  SU2_CFD/src/solvers/CAdjNSSolver.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_CFD/src/solvers/CIncEulerSolver.cpp
  SU2_CFD/src/solvers/CIncNSSolver.cpp
  SU2_CFD/src/solvers/CMeshSolver.cpp
  SU2_CFD/src/solvers/CNSSolver.cpp
  SU2_CFD/src/solvers/CTurbSolver.cpp
  TestCases/cont_adj_euler/naca0012/of_grad_cd_disc.dat.ref
  TestCases/multiple_ffd/naca0012/of_grad_cd.dat.ref
  TestCases/parallel_regression_AD.py
  TestCases/serial_regression_AD.py
Labels: PR: unreviewed, changelog:fix, enhancement

#981 Update Xcode and one bug fix
  Common/include/adt_structure.hpp
  SU2_CFD/include/output/tools/CWindowingTools.hpp
  SU2_IDE/Xcode/SU2_CFD.xcodeproj/project.pbxproj
Labels: PR: reviewed-approved

#980 Fix large mesh
  Common/src/geometry/CPhysicalGeometry.cpp
  SU2_CFD/src/output/filewriter/CParaviewXMLFileWriter.cpp
  SU2_CFD/src/solvers/CSolver.cpp
Labels: PR: unreviewed

#985 adding reference for distortion and uniformity parameters
  SU2_CFD/src/output/CFlowOutput.cpp
Labels: PR: partially-approved

#964 Restart Features for some python scripts
  SU2_CFD/src/output/CAdjElasticityOutput.cpp
  SU2_CFD/src/output/CAdjFlowCompOutput.cpp
  SU2_CFD/src/output/CAdjFlowIncOutput.cpp
  SU2_CFD/src/output/CAdjHeatOutput.cpp
  SU2_PY/SU2/eval/functions.py
  SU2_PY/SU2/eval/gradients.py
  SU2_PY/SU2/io/state.py
  SU2_PY/SU2/io/tools.py
  SU2_PY/SU2/opt/project.py
  SU2_PY/direct_differentiation.py
  SU2_PY/discrete_adjoint.py
  SU2_PY/shape_optimization.py
  TestCases/optimization_rans/naca0012/naca0012.cfg
  TestCases/parallel_regression_AD.py
  TestCases/rans/restart_directdiff_naca/naca0012.cfg
  TestCases/serial_regression.py
Labels: PR: unreviewed, enhancement

#987 Fix spelling error in CSinglezoneDriver.cpp. Add missing comment for iteration_structure.hpp
  SU2_CFD/include/drivers/CSinglezoneDriver.hpp
  SU2_CFD/include/iteration_structure.hpp
Labels: PR: unreviewed

#974 Linear solver history/screen output for discrete adjoint solvers
  Common/include/linear_algebra/CSysSolve.hpp
  Common/src/linear_algebra/CSysSolve.cpp
  SU2_CFD/src/output/CAdjElasticityOutput.cpp
  SU2_CFD/src/output/CAdjFlowCompOutput.cpp
  SU2_CFD/src/output/CAdjFlowIncOutput.cpp
  SU2_CFD/src/output/CAdjHeatOutput.cpp
  SU2_CFD/src/output/CElasticityOutput.cpp
  SU2_CFD/src/output/CFlowCompFEMOutput.cpp
  SU2_CFD/src/output/CHeatOutput.cpp
  SU2_CFD/src/solvers/CDiscAdjFEASolver.cpp
  SU2_CFD/src/solvers/CDiscAdjSolver.cpp
Labels: PR: reviewed-approved, changelog:none

#993 Adds Missing Const Specifiers to Member Functions
  Common/include/CConfig.hpp
  Common/include/fem_gauss_jacobi_quadrature.hpp
  Common/include/fem_geometry_structure.hpp
  Common/include/fem_geometry_structure.inl
  Common/include/fem_standard_element.hpp
  Common/include/fem_standard_element.inl
  Common/include/geometry/CGeometry.hpp
  Common/include/geometry/CPhysicalGeometry.hpp
  Common/include/geometry/meshreader/CCGNSMeshReaderFVM.hpp
  Common/include/geometry/meshreader/CMeshReaderFVM.hpp
  Common/include/geometry/primal_grid/CPrimalGrid.hpp
  Common/include/grid_adaptation_structure.hpp
  Common/include/grid_movement_structure.hpp
  Common/include/grid_movement_structure.inl
  Common/src/CConfig.cpp
  Common/src/fem_gauss_jacobi_quadrature.cpp
  Common/src/fem_standard_element.cpp
  Common/src/geometry/CGeometry.cpp
  Common/src/geometry/CPhysicalGeometry.cpp
  Common/src/geometry/meshreader/CCGNSMeshReaderFVM.cpp
  Common/src/grid_adaptation_structure.cpp
  Common/src/grid_movement_structure.cpp
  SU2_CFD/include/CMarkerProfileReaderFVM.hpp
  SU2_CFD/include/drivers/CDriver.hpp
  SU2_CFD/include/fluid_model.hpp
  SU2_CFD/include/fluid_model.inl
  SU2_CFD/include/numerics/CNumerics.hpp
  SU2_CFD/include/numerics/transition.hpp
  SU2_CFD/include/output/COutput.hpp
  SU2_CFD/include/output/COutputLegacy.hpp
  SU2_CFD/include/solvers/CEulerSolver.hpp
  SU2_CFD/include/solvers/CMeshSolver.hpp
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/include/transport_model.hpp
  SU2_CFD/include/transport_model.inl
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/fluid_model_ppr.cpp
  SU2_CFD/src/numerics/CNumerics.cpp
  SU2_CFD/src/numerics/transition.cpp
  SU2_CFD/src/output/output_structure_legacy.cpp
  SU2_CFD/src/python_wrapper_structure.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_CFD/src/solvers/CMeshSolver.cpp
  SU2_CFD/src/solvers/CSolver.cpp
  SU2_CFD/src/transport_model.cpp
Labels: PR: reviewed-approved

#1001 Move FEM files
  Common/include/fem/fem_cgns_elements.hpp
  Common/include/fem/fem_gauss_jacobi_quadrature.hpp
  Common/include/fem/fem_geometry_structure.hpp
  Common/include/fem/fem_standard_element.hpp
  Common/include/fem/geometry_structure_fem_part.hpp
  Common/include/fem_gauss_jacobi_quadrature.inl
  Common/include/fem_geometry_structure.inl
  Common/include/fem_standard_element.inl
  Common/include/geometry/CGeometry.hpp
  Common/include/wall_model.hpp
  Common/include/wall_model.inl
  Common/lib/Makefile.am
  Common/src/CConfig.cpp
  Common/src/fem/fem_cgns_elements.cpp
  Common/src/fem/fem_gauss_jacobi_quadrature.cpp
  Common/src/fem/fem_geometry_structure.cpp
  Common/src/fem/fem_integration_rules.cpp
  Common/src/fem/fem_standard_element.cpp
  Common/src/fem/fem_wall_distance.cpp
  Common/src/fem/fem_work_estimate_metis.cpp
  Common/src/fem/geometry_structure_fem_part.cpp
  Common/src/fem/meson.build
  Common/src/meson.build
  SU2_CFD/include/SU2_CFD.hpp
  SU2_CFD/include/definition_structure.hpp
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/src/output/filewriter/CFEMDataSorter.cpp
  SU2_CFD/src/output/filewriter/CSurfaceFEMDataSorter.cpp
  SU2_DOT/include/SU2_DOT.hpp
Labels: PR: unreviewed, changelog:chore

#989 Mixed precision linear algebra
  Common/include/CMultiGridQueue.hpp
  Common/include/ad_structure.hpp
  Common/include/ad_structure.inl
  Common/include/datatype_structure.hpp
  Common/include/datatype_structure.inl
  Common/include/datatypes/codi_forward_structure.hpp
  Common/include/datatypes/codi_forward_structure.inl
  Common/include/datatypes/codi_reverse_structure.hpp
  Common/include/datatypes/codi_reverse_structure.inl
  Common/include/datatypes/primitive_structure.hpp
  Common/include/datatypes/primitive_structure.inl
  Common/include/grid_movement_structure.hpp
  Common/include/linear_algebra/CPastixWrapper.hpp
  Common/include/linear_algebra/CSysMatrix.hpp
  Common/include/linear_algebra/CSysMatrix.inl
  Common/include/mpi_structure.hpp
  Common/src/CMultiGridQueue.cpp
  Common/src/grid_movement_structure.cpp
  Common/src/linear_algebra/CPastixWrapper.cpp
  Common/src/linear_algebra/CSysMatrix.cpp
  Common/src/linear_algebra/CSysSolve.cpp
  Common/src/linear_algebra/CSysSolve_b.cpp
  Common/src/linear_algebra/CSysVector.cpp
  SU2_CFD/include/solvers/CFEASolver.hpp
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/include/solvers/CTransLMSolver.hpp
  SU2_CFD/src/numerics/flow/convection/centered.cpp
  SU2_CFD/src/solvers/CFEASolver.cpp
  SU2_PY/pySU2/pySU2.i
  SU2_PY/pySU2/pySU2ad.i
  TestCases/cont_adj_euler/naca0012/inv_NACA0012.cfg
  meson.build
  meson_options.txt
Labels: PR: reviewed-approved, changelog:feature

#975 Hybrid parallel boundary conditions for turbulence and compressible flow solvers
  .github/workflows/regression.yml
  .travis.yml
  Common/include/CConfig.hpp
  Common/include/basic_types/ad_structure.hpp
  Common/include/basic_types/datatype_structure.hpp
  Common/include/blas_structure.hpp
  Common/include/fem/geometry_structure_fem_part.hpp
  Common/include/interface_interpolation/CInterpolator.hpp
  Common/include/linear_algebra/CSysMatrix.hpp
  Common/include/mpi_structure.hpp
  Common/include/toolboxes/C1DInterpolation.hpp
  Common/include/toolboxes/C2DContainer.hpp
  Common/include/toolboxes/printing_toolbox.hpp
  Common/lib/Makefile.am
  Common/src/CConfig.cpp
  Common/src/basic_types/ad_structure.cpp
  Common/src/fem/fem_cgns_elements.cpp
  Common/src/grid_movement_structure.cpp
  Common/src/linear_algebra/CSysMatrix.cpp
  Common/src/meson.build
  SU2_CFD/include/solvers/CNSSolver.hpp
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/include/transport_model.hpp
  SU2_CFD/src/integration/CIntegration.cpp
  SU2_CFD/src/solvers/CAdjEulerSolver.cpp
  SU2_CFD/src/solvers/CAdjNSSolver.cpp
  SU2_CFD/src/solvers/CAdjTurbSolver.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_CFD/src/solvers/CFEASolver.cpp
  SU2_CFD/src/solvers/CHeatSolver.cpp
  SU2_CFD/src/solvers/CIncEulerSolver.cpp
  SU2_CFD/src/solvers/CIncNSSolver.cpp
  SU2_CFD/src/solvers/CNSSolver.cpp
  SU2_CFD/src/solvers/CRadP1Solver.cpp
  SU2_CFD/src/solvers/CSolver.cpp
  SU2_CFD/src/solvers/CTransLMSolver.cpp
  SU2_CFD/src/solvers/CTurbSASolver.cpp
  SU2_CFD/src/solvers/CTurbSSTSolver.cpp
  SU2_CFD/src/solvers/CTurbSolver.cpp
  SU2_PY/pySU2/pySU2.i
  SU2_PY/pySU2/pySU2ad.i
  TestCases/hybrid_regression.py
  UnitTests/Common/simple_ad_test.cpp
  UnitTests/Common/simple_directdiff_test.cpp
Labels: PR: reviewed-approved, changelog:none

#996 Multiline config option values and Paraview vtu default output
  Common/src/CConfig.cpp
  SU2_PY/SU2/io/config.py
Labels: PR: unreviewed, changelog:feature

#1004 Adds Grid Velocity Term in the Euler/Symmetry BC
  SU2_CFD/src/solvers/CEulerSolver.cpp
  TestCases/hybrid_regression.py
  TestCases/parallel_regression.py
  TestCases/parallel_regression_AD.py
  TestCases/rotating/caradonna_tung/rot_caradonna_tung.cfg
  TestCases/serial_regression.py
  TestCases/serial_regression_AD.py
Labels: PR: unreviewed
