Repository su2code/SU2, pull requests merged in 2020-08, with the labels that each got.

#877 Rough wall boundary condition for SA and SST turbulence models.
  Common/include/CConfig.hpp
  Common/include/geometry/CPhysicalGeometry.hpp
  Common/include/geometry/dual_grid/CPoint.hpp
  Common/include/geometry/dual_grid/CTurboVertex.hpp
  Common/include/mpi_structure.hpp
  Common/include/mpi_structure.inl
  Common/include/option_structure.hpp
  Common/src/CConfig.cpp
  Common/src/geometry/CPhysicalGeometry.cpp
  Common/src/geometry/dual_grid/CPoint.cpp
  SU2_CFD/include/numerics/CNumerics.hpp
  SU2_CFD/include/numerics/turbulent/turb_sources.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/include/variables/CTurbSSTVariable.hpp
  SU2_CFD/src/numerics/turbulent/turb_sources.cpp
  SU2_CFD/src/solvers/CTurbSASolver.cpp
  SU2_CFD/src/solvers/CTurbSSTSolver.cpp
  SU2_CFD/src/solvers/CTurbSolver.cpp
  SU2_CFD/src/variables/CTurbSSTVariable.cpp
  SU2_CFD/src/variables/CTurbVariable.cpp
  TestCases/incomp_rans/rough_flatplate/rough_flatplate_incomp.cfg
  config_template.cfg
Labels: PR: unreviewed, changelog:feature

#1057 Fix underrelaxation
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/src/solvers/CTurbSolver.cpp
  TestCases/hybrid_regression.py
  TestCases/parallel_regression.py
  TestCases/serial_regression.py
  TestCases/tutorials.py
Labels: PR: unreviewed

#1059 Improve partitioning load balance for hybrid grids and add advanced ParMETIS controls
  Common/include/CConfig.hpp
  Common/include/fem/fem_geometry_structure.hpp
  Common/include/geometry/CGeometry.hpp
  Common/include/geometry/CPhysicalGeometry.hpp
  Common/src/CConfig.cpp
  Common/src/fem/fem_geometry_structure.cpp
  Common/src/geometry/CPhysicalGeometry.cpp
  TestCases/fea_topology/config.cfg
  TestCases/parallel_regression.py
  TestCases/parallel_regression_AD.py
  TestCases/rans/oneram6/turb_ONERAM6.cfg
  TestCases/tutorials.py
  config_template.cfg
Labels: PR: unreviewed, changelog:feature

#1039 Small bug in polar sweep python script
  SU2_PY/SU2/util/polarSweepLib.py
Labels: PR: unreviewed, changelog:fix
