Repository su2code/SU2, pull requests merged in 2020-01, with the labels that each got.

#840 Fix periodic boundary condition for nodes on axis of rotation
  Common/src/geometry/CPhysicalGeometry.cpp
Labels: PR: reviewed-approved

#830 Hybrid parallel (OpenMP) implementation for Linear Algebra classes
  Common/include/fem_geometry_structure.hpp
  Common/include/fem_geometry_structure.inl
  Common/include/geometry/CGeometry.hpp
  Common/include/geometry/CPhysicalGeometry.hpp
  Common/include/linear_algebra/CMatrixVectorProduct.hpp
  Common/include/linear_algebra/CPastixWrapper.hpp
  Common/include/linear_algebra/CPreconditioner.hpp
  Common/include/linear_algebra/CSysMatrix.hpp
  Common/include/linear_algebra/CSysMatrix.inl
  Common/include/linear_algebra/CSysSolve.hpp
  Common/include/linear_algebra/CSysVector.hpp
  Common/include/mpi_structure.hpp
  Common/include/mpi_structure.inl
  Common/include/omp_structure.hpp
  Common/include/toolboxes/C2DContainer.hpp
  Common/include/toolboxes/allocation_toolbox.hpp
  Common/include/toolboxes/graph_toolbox.hpp
  Common/src/geometry/CGeometry.cpp
  Common/src/geometry/CPhysicalGeometry.cpp
  Common/src/grid_movement_structure.cpp
  Common/src/linear_algebra/CPastixWrapper.cpp
  Common/src/linear_algebra/CSysMatrix.cpp
  Common/src/linear_algebra/CSysSolve.cpp
  Common/src/linear_algebra/CSysVector.cpp
  SU2_CFD/include/SU2_CFD.hpp
  SU2_CFD/include/solver_structure.hpp
  SU2_CFD/include/solver_structure.inl
  SU2_CFD/src/SU2_CFD.cpp
  SU2_CFD/src/output/CElasticityOutput.cpp
  SU2_CFD/src/solver_direct_elasticity.cpp
  SU2_CFD/src/solver_direct_heat.cpp
  SU2_CFD/src/solver_direct_mean.cpp
  SU2_CFD/src/solver_direct_mean_inc.cpp
  SU2_CFD/src/solver_direct_turbulent.cpp
  SU2_DEF/include/SU2_DEF.hpp
  SU2_DEF/src/SU2_DEF.cpp
  SU2_DOT/include/SU2_DOT.hpp
  SU2_DOT/src/SU2_DOT.cpp
  TestCases/parallel_regression_AD.py
  TestCases/pastix_support/readme.txt
  TestCases/serial_regression_AD.py
Labels: PR: reviewed-approved, feature

#836 Added Windowing Regularizers for time averaged outputs.
  Common/include/config_structure.hpp
  Common/include/config_structure.inl
  Common/include/option_structure.hpp
  Common/include/toolboxes/signal_processing_toolbox.hpp
  Common/src/config_structure.cpp
  Common/src/toolboxes/signal_processing_toolbox.cpp
  SU2_CFD/include/drivers/CDiscAdjSinglezoneDriver.hpp
  SU2_CFD/include/drivers/CSinglezoneDriver.hpp
  SU2_CFD/include/output/COutput.hpp
  SU2_CFD/include/output/tools/CWindowingTools.hpp
  SU2_CFD/src/drivers/CDiscAdjMultizoneDriver.cpp
  SU2_CFD/src/drivers/CDiscAdjSinglezoneDriver.cpp
  SU2_CFD/src/drivers/CSinglezoneDriver.cpp
  SU2_CFD/src/meson.build
  SU2_CFD/src/output/COutput.cpp
  SU2_CFD/src/output/tools/CWindowingTools.cpp
  SU2_DEF/src/meson.build
  SU2_DOT/src/meson.build
  SU2_PY/SU2/eval/design.py
  SU2_PY/SU2/eval/functions.py
  SU2_PY/SU2/eval/gradients.py
  SU2_PY/SU2/io/config.py
  SU2_PY/SU2/io/historyMap.py
  SU2_PY/SU2/io/state.py
  SU2_PY/SU2/io/tools.py
  SU2_PY/SU2/opt/project.py
  SU2_PY/SU2/run/adjoint.py
  SU2_PY/SU2/run/direct.py
  SU2_PY/discrete_adjoint.py
  SU2_PY/shape_optimization.py
  SU2_PY/updateHistoryMap.py
  SU2_SOL/src/meson.build
  TestCases/disc_adj_rans/cylinder/cylinder_Windowing.cfg
  TestCases/disc_adj_rans/cylinder/cylinder_Windowing_AD.cfg
  TestCases/parallel_regression_AD.py
  config_template.cfg
Labels: PR: unreviewed, feature

#834 Hybrid parallel Gradients and Limiters
  Common/include/omp_structure.hpp
  Common/include/option_structure.hpp
  Common/include/toolboxes/C2DContainer.hpp
  Common/src/meson.build
  SU2_CFD/include/gradients/computeGradientsGreenGauss.hpp
  SU2_CFD/include/gradients/computeGradientsLeastSquares.hpp
  SU2_CFD/include/limiters/CLimiterDetails.hpp
  SU2_CFD/include/limiters/computeLimiters.hpp
  SU2_CFD/include/limiters/computeLimiters_impl.hpp
  SU2_CFD/include/variables/CAdjEulerVariable.hpp
  SU2_CFD/include/variables/CEulerVariable.hpp
  SU2_CFD/include/variables/CHeatFVMVariable.hpp
  SU2_CFD/include/variables/CIncEulerVariable.hpp
  SU2_CFD/include/variables/CTurbVariable.hpp
  SU2_CFD/include/variables/CVariable.hpp
  SU2_CFD/obj/Makefile.am
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/solver_direct_mean.cpp
  SU2_CFD/src/solver_direct_mean_inc.cpp
  SU2_CFD/src/solver_structure.cpp
  SU2_CFD/src/variables/CEulerVariable.cpp
  SU2_CFD/src/variables/CIncEulerVariable.cpp
  SU2_CFD/src/variables/CVariable.cpp
  TestCases/parallel_regression.py
  TestCases/parallel_regression_AD.py
  TestCases/serial_regression.py
  TestCases/serial_regression_AD.py
  TestCases/turbomachinery/transonic_stator_2D/transonic_stator_rst.cfg
Labels: PR: unreviewed, no_changelog

#847 Add *.stl (STereoLithography) output format
  Common/include/option_structure.hpp
  Common/src/config_structure.cpp
  SU2_CFD/include/output/filewriter/CCSVFileWriter.hpp
  SU2_CFD/include/output/filewriter/CFEMDataSorter.hpp
  SU2_CFD/include/output/filewriter/CFVMDataSorter.hpp
  SU2_CFD/include/output/filewriter/CParallelDataSorter.hpp
  SU2_CFD/include/output/filewriter/CParaviewFileWriter.hpp
  SU2_CFD/include/output/filewriter/CSTLFileWriter.hpp
  SU2_CFD/include/output/filewriter/CSU2FileWriter.hpp
  SU2_CFD/include/output/filewriter/CSU2MeshFileWriter.hpp
  SU2_CFD/include/output/filewriter/CSurfaceFEMDataSorter.hpp
  SU2_CFD/include/output/filewriter/CSurfaceFVMDataSorter.hpp
  SU2_CFD/obj/Makefile.am
  SU2_CFD/src/meson.build
  SU2_CFD/src/output/COutput.cpp
  SU2_CFD/src/output/filewriter/CSTLFileWriter.cpp
  SU2_CFD/src/output/filewriter/CSurfaceFEMDataSorter.cpp
  SU2_CFD/src/output/filewriter/CSurfaceFVMDataSorter.cpp
  SU2_DEF/src/meson.build
  SU2_DOT/src/meson.build
  SU2_SOL/src/meson.build
  TestCases/parallel_regression.py
  TestCases/rans/oneram6/turb_ONERAM6.cfg
  config_template.cfg
Labels: PR: unreviewed, feature

#848 Restructuring dual/primal grid structure
  Common/include/dual_grid_structure.hpp
  Common/include/dual_grid_structure.inl
  Common/include/fem_cgns_elements.hpp
  Common/include/geometry/CGeometry.hpp
  Common/include/geometry/CPhysicalGeometry.hpp
  Common/include/geometry/dual_grid/CDualGrid.hpp
  Common/include/geometry/dual_grid/CEdge.hpp
  Common/include/geometry/dual_grid/CPoint.hpp
  Common/include/geometry/dual_grid/CTurboVertex.hpp
  Common/include/geometry/dual_grid/CVertex.hpp
  Common/include/geometry/meshreader/CBoxMeshReaderFVM.hpp
  Common/include/geometry/meshreader/CCGNSMeshReaderFVM.hpp
  Common/include/geometry/meshreader/CMeshReaderFVM.hpp
  Common/include/geometry/meshreader/CRectangularMeshReaderFVM.hpp
  Common/include/geometry/meshreader/CSU2ASCIIMeshReaderFVM.hpp
  Common/include/geometry/primal_grid/CHexahedron.hpp
  Common/include/geometry/primal_grid/CLine.hpp
  Common/include/geometry/primal_grid/CPrimalGrid.hpp
  Common/include/geometry/primal_grid/CPrimalGridBoundFEM.hpp
  Common/include/geometry/primal_grid/CPrimalGridFEM.hpp
  Common/include/geometry/primal_grid/CPrism.hpp
  Common/include/geometry/primal_grid/CPyramid.hpp
  Common/include/geometry/primal_grid/CQuadrilateral.hpp
  Common/include/geometry/primal_grid/CTetrahedron.hpp
  Common/include/geometry/primal_grid/CTriangle.hpp
  Common/include/geometry/primal_grid/CVertexMPI.hpp
  Common/include/primal_grid_structure.hpp
  Common/include/primal_grid_structure.inl
  Common/src/fem_geometry_structure.cpp
  Common/src/geometry/CPhysicalGeometry.cpp
  Common/src/geometry/dual_grid/CDualGrid.cpp
  Common/src/geometry/dual_grid/CEdge.cpp
  Common/src/geometry/dual_grid/CPoint.cpp
  Common/src/geometry/dual_grid/CTurboVertex.cpp
  Common/src/geometry/dual_grid/CVertex.cpp
  Common/src/geometry/dual_grid/meson.build
  Common/src/geometry/meshreader/CBoxMeshReaderFVM.cpp
  Common/src/geometry/meshreader/CCGNSMeshReaderFVM.cpp
  Common/src/geometry/meshreader/CMeshReaderFVM.cpp
  Common/src/geometry/meshreader/CRectangularMeshReaderFVM.cpp
  Common/src/geometry/meshreader/CSU2ASCIIMeshReaderFVM.cpp
  Common/src/geometry/meshreader/meson.build
  Common/src/geometry/primal_grid/CHexahedron.cpp
  Common/src/geometry/primal_grid/CLine.cpp
  Common/src/geometry/primal_grid/CPrimalGrid.cpp
  Common/src/geometry/primal_grid/CPrimalGridBoundFEM.cpp
  Common/src/geometry/primal_grid/CPrimalGridFEM.cpp
  Common/src/geometry/primal_grid/CPrism.cpp
  Common/src/geometry/primal_grid/CPyramid.cpp
  Common/src/geometry/primal_grid/CQuadrilateral.cpp
  Common/src/geometry/primal_grid/CTetrahedron.cpp
  Common/src/geometry/primal_grid/CTriangle.cpp
  Common/src/geometry/primal_grid/CVertexMPI.cpp
  Common/src/geometry/primal_grid/meson.build
  Common/src/geometry_structure_fem_part.cpp
  Common/src/grid_adaptation_structure.cpp
  Common/src/meson.build
  Common/src/primal_grid_structure.cpp
  SU2_CFD/include/output/filewriter/CSurfaceFVMDataSorter.hpp
  SU2_CFD/src/output/filewriter/CSTLFileWriter.cpp
Labels: PR: unreviewed, chore

#843 Hybrid parallel CFEASolver and CMeshSolver
  Common/include/config_structure.hpp
  Common/include/geometry/CGeometry.hpp
  Common/include/linear_algebra/CSysMatrix.hpp
  Common/include/linear_algebra/CSysVector.hpp
  Common/include/omp_structure.hpp
  Common/include/option_structure.hpp
  Common/include/toolboxes/graph_toolbox.hpp
  Common/src/config_structure.cpp
  Common/src/geometry/CGeometry.cpp
  Common/src/geometry/CMultiGridGeometry.cpp
  Common/src/linear_algebra/CSysMatrix.cpp
  SU2_CFD/include/solver_structure.hpp
  SU2_CFD/include/solver_structure.inl
  SU2_CFD/include/solvers/CFEASolver.hpp
  SU2_CFD/include/solvers/CMeshSolver.hpp
  SU2_CFD/include/variables/CFEAVariable.hpp
  SU2_CFD/include/variables/CVariable.hpp
  SU2_CFD/obj/Makefile.am
  SU2_CFD/src/SU2_CFD.cpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/integration_structure.cpp
  SU2_CFD/src/iteration_structure.cpp
  SU2_CFD/src/meson.build
  SU2_CFD/src/numerics/elasticity/CFEAElasticity.cpp
  SU2_CFD/src/numerics/elasticity/CFEANonlinearElasticity.cpp
  SU2_CFD/src/numerics/elasticity/CFEM_IdealDE.cpp
  SU2_CFD/src/output/output_structure_legacy.cpp
  SU2_CFD/src/solver_direct_elasticity.cpp
  SU2_CFD/src/solvers/CFEASolver.cpp
  SU2_CFD/src/solvers/CMeshSolver.cpp
  TestCases/parallel_regression_AD.py
  TestCases/serial_regression_AD.py
  meson.build
  meson_options.txt
Labels: PR: unreviewed, feature

#853 Faster compilation
  Common/include/CConfig.hpp
  Common/include/blas_structure.hpp
  Common/include/config_structure.inl
  Common/include/fem_gauss_jacobi_quadrature.hpp
  Common/include/fem_standard_element.hpp
  Common/include/geometry/CGeometry.hpp
  Common/include/geometry/dual_grid/CDualGrid.hpp
  Common/include/geometry/meshreader/CMeshReaderFVM.hpp
  Common/include/geometry/primal_grid/CPrimalGrid.hpp
  Common/include/graph_coloring_structure.hpp
  Common/include/grid_adaptation_structure.hpp
  Common/include/grid_movement_structure.hpp
  Common/include/interpolation_structure.hpp
  Common/include/linear_algebra/CMatrixVectorProduct.hpp
  Common/include/linear_algebra/CPreconditioner.hpp
  Common/include/linear_algebra/CSysSolve_b.hpp
  Common/include/option_structure.hpp
  Common/include/option_structure.inl
  Common/include/toolboxes/MMS/CVerificationSolution.hpp
  Common/include/toolboxes/printing_toolbox.hpp
  Common/include/wall_model.hpp
  Common/lib/Makefile.am
  Common/src/CConfig.cpp
  Common/src/linear_algebra/CPastixWrapper.cpp
  Common/src/linear_algebra/CSysMatrix.cpp
  Common/src/linear_algebra/CSysSolve.cpp
  Common/src/meson.build
  SU2_CFD/include/CMarkerProfileReaderFVM.hpp
  SU2_CFD/include/SU2_CFD.hpp
  SU2_CFD/include/definition_structure.hpp
  SU2_CFD/include/drivers/CDriver.hpp
  SU2_CFD/include/fluid_model.hpp
  SU2_CFD/include/integration_structure.hpp
  SU2_CFD/include/interfaces/CInterface.hpp
  SU2_CFD/include/iteration_structure.hpp
  SU2_CFD/include/numerics_structure.hpp
  SU2_CFD/include/output/CMultizoneOutput.hpp
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/include/variables/CMeshElement.hpp
  SU2_CFD/include/variables/CVariable.hpp
  SU2_CFD/src/output/COutput.cpp
  SU2_DEF/include/SU2_DEF.hpp
  SU2_DOT/include/SU2_DOT.hpp
  SU2_GEO/include/SU2_GEO.hpp
  SU2_MSH/include/SU2_MSH.hpp
  SU2_SOL/include/SU2_SOL.hpp
Labels: PR: reviewed-approved, changelog:chore, enhancement
