Repository su2code/SU2, pull requests merged in 2021-10, with the labels that each got.

#1383 Addition of species diffusion term to surface heat flux
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/include/variables/CNEMONSVariable.hpp
  SU2_CFD/include/variables/CVariable.hpp
  SU2_CFD/src/variables/CNEMONSVariable.cpp
Labels: changelog:chore, PR: partially-approved

#1372 Cleanup and document the multigrid agglomeration strategy
  Common/include/geometry/CGeometry.hpp
  Common/include/geometry/CMultiGridGeometry.hpp
  Common/include/geometry/CPhysicalGeometry.hpp
  Common/src/fem/geometry_structure_fem_part.cpp
  Common/src/geometry/CGeometry.cpp
  Common/src/geometry/CMultiGridGeometry.cpp
  Common/src/geometry/CPhysicalGeometry.cpp
  Common/src/grid_movement/CVolumetricMovement.cpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/solvers/CMeshSolver.cpp
Labels: PR: reviewed-approved, changelog:chore

#1389 Cleanup in NEMO
  SU2_CFD/src/fluid/CSU2TCLib.cpp
  SU2_CFD/src/numerics/NEMO/NEMO_diffusion.cpp
  SU2_CFD/src/solvers/CNEMOEulerSolver.cpp
Labels: PR: unreviewed, changelog:chore, PR: partially-approved

#1391 More NEMO cleanup
  SU2_CFD/src/fluid/CNEMOGas.cpp
  SU2_CFD/src/numerics/NEMO/NEMO_diffusion.cpp
  SU2_CFD/src/numerics/NEMO/NEMO_sources.cpp
  SU2_CFD/src/solvers/CNEMOEulerSolver.cpp
  SU2_CFD/src/solvers/CNEMONSSolver.cpp
Labels: PR: reviewed-approved
