Repository su2code/SU2, pull requests merged in 2021-12, with the labels that each got.

#1388 Species transport solver (passive for now)
  Common/include/CConfig.hpp
  Common/include/option_structure.hpp
  Common/include/option_structure.inl
  Common/src/CConfig.cpp
  SU2_CFD/include/drivers/CDriver.hpp
  SU2_CFD/include/numerics/scalar/scalar_convection.hpp
  SU2_CFD/include/numerics/scalar/scalar_diffusion.hpp
  SU2_CFD/include/numerics/species/species_convection.hpp
  SU2_CFD/include/numerics/species/species_diffusion.hpp
  SU2_CFD/include/numerics/species/species_sources.hpp
  SU2_CFD/include/output/CFlowOutput.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/include/solvers/CScalarSolver.hpp
  SU2_CFD/include/solvers/CScalarSolver.inl
  SU2_CFD/include/solvers/CSolverFactory.hpp
  SU2_CFD/include/solvers/CSpeciesSolver.hpp
  SU2_CFD/include/solvers/CTurbSSTSolver.hpp
  SU2_CFD/include/variables/CSpeciesVariable.hpp
  SU2_CFD/include/variables/CTurbVariable.hpp
  SU2_CFD/obj/Makefile.am
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/iteration/CDiscAdjFluidIteration.cpp
  SU2_CFD/src/iteration/CFluidIteration.cpp
  SU2_CFD/src/meson.build
  SU2_CFD/src/numerics/species/species_sources.cpp
  SU2_CFD/src/output/CFlowCompFEMOutput.cpp
  SU2_CFD/src/output/CFlowCompOutput.cpp
  SU2_CFD/src/output/CFlowIncOutput.cpp
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_CFD/src/output/CNEMOCompOutput.cpp
  SU2_CFD/src/solvers/CDiscAdjSolver.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_CFD/src/solvers/CIncEulerSolver.cpp
  SU2_CFD/src/solvers/CSolver.cpp
  SU2_CFD/src/solvers/CSolverFactory.cpp
  SU2_CFD/src/solvers/CSpeciesSolver.cpp
  SU2_CFD/src/solvers/CTurbSASolver.cpp
  SU2_CFD/src/solvers/CTurbSSTSolver.cpp
  SU2_CFD/src/solvers/CTurbSolver.cpp
  SU2_CFD/src/variables/CSpeciesVariable.cpp
  TestCases/parallel_regression.py
  TestCases/rans/flatplate/inlet.dat
  TestCases/rans/flatplate/turb_SA_flatplate_species.cfg
  TestCases/species_transport/passive_transport_validation/README.md
  TestCases/species_transport/passive_transport_validation/passive_transport.cfg
  TestCases/species_transport/venturi_primitive_3species/README.md
  TestCases/species_transport/venturi_primitive_3species/inlet_venturi.dat
  TestCases/species_transport/venturi_primitive_3species/restart_validation.sh
  TestCases/species_transport/venturi_primitive_3species/species2_primitiveVenturi.cfg
  TestCases/species_transport/venturi_primitive_3species/species3_primitiveVenturi.cfg
  TestCases/species_transport/venturi_primitive_3species/species3_primitiveVenturi_inletFile.cfg
  TestCases/species_transport/venturi_primitive_3species/test_inlet_files.sh
  config_template.cfg
Labels: PR: unreviewed, changelog:feature

#1470 Treat SU2_CFD library similar to Common in meson build process
  SU2_DEF/src/meson.build
  SU2_DOT/src/meson.build
  SU2_GEO/src/meson.build
  SU2_SOL/src/meson.build
Labels: PR: reviewed-approved, changelog:chore

#1475 Fix "offline" builds with meson
  meson_scripts/init.py
Labels: PR: unreviewed, changelog:fix

#1476 Using the primitive variable index classes in more places (+ minor chores)
  Common/include/CConfig.hpp
  Common/include/option_structure.hpp
  Common/src/CConfig.cpp
  Common/src/geometry/CGeometry.cpp
  Common/src/geometry/CPhysicalGeometry.cpp
  SU2_CFD/include/solvers/CEulerSolver.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/include/solvers/CIncEulerSolver.hpp
  SU2_CFD/include/solvers/CIncNSSolver.hpp
  SU2_CFD/include/solvers/CNEMOEulerSolver.hpp
  SU2_CFD/include/variables/CEulerVariable.hpp
  SU2_CFD/include/variables/CIncEulerVariable.hpp
  SU2_CFD/src/drivers/CMultizoneDriver.cpp
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_CFD/src/solvers/CAdjEulerSolver.cpp
  SU2_CFD/src/solvers/CAdjNSSolver.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_CFD/src/solvers/CIncEulerSolver.cpp
  SU2_CFD/src/solvers/CIncNSSolver.cpp
  SU2_CFD/src/solvers/CNEMOEulerSolver.cpp
  SU2_CFD/src/solvers/CNSSolver.cpp
  SU2_CFD/src/solvers/CRadP1Solver.cpp
  SU2_CFD/src/solvers/CSolver.cpp
  TestCases/incomp_navierstokes/streamwise_periodic/chtPinArray_2d/of_grad_findiff.csv.ref
  TestCases/parallel_regression.py
  TestCases/parallel_regression_AD.py
  TestCases/species_transport/passive_transport_validation/passive_transport.cfg
  config_template.cfg
Labels: PR: unreviewed, changelog:chore
