Repository su2code/SU2, pull requests merged in 2021-02, with the labels that each got.

#1181 Simplify FEA MPI communications
  Common/include/option_structure.hpp
  SU2_CFD/include/variables/CFEAVariable.hpp
  SU2_CFD/include/variables/CVariable.hpp
  SU2_CFD/src/integration/CMultiGridIntegration.cpp
  SU2_CFD/src/iteration/CDiscAdjFEAIteration.cpp
  SU2_CFD/src/solvers/CFEASolver.cpp
  SU2_CFD/src/solvers/CSolver.cpp
  TestCases/parallel_regression_AD.py
  meson_scripts/init.py
Labels: PR: unreviewed, changelog:chore

#1188 Added CFL_AdaptParam to the destructor of CConfig
  Common/src/CConfig.cpp
Labels: PR: reviewed-approved

#1192 Fix axi auxvargrad
  SU2_CFD/src/numerics/flow/flow_sources.cpp
  SU2_CFD/src/solvers/CSolver.cpp
Labels: PR: reviewed-approved, changelog:fix

#1189 Fixed Coord_j for boundary viscous numerics (bug waiting to happen)
  Common/include/toolboxes/geometry_toolbox.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/src/solvers/CAdjEulerSolver.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_CFD/src/solvers/CIncEulerSolver.cpp
  SU2_CFD/src/solvers/CNEMOEulerSolver.cpp
  SU2_CFD/src/solvers/CTurbSASolver.cpp
  SU2_CFD/src/solvers/CTurbSSTSolver.cpp
  SU2_CFD/src/solvers/CTurbSolver.cpp
  TestCases/hybrid_regression.py
  TestCases/parallel_regression.py
  TestCases/parallel_regression_AD.py
  TestCases/serial_regression.py
  TestCases/serial_regression_AD.py
Labels: PR: unreviewed, changelog:fix

#1194 Fix Multigrid for Incompressible NS with moving walls, and for NEMO NS in general
  .gitignore
  SU2_CFD/include/variables/CAdjEulerVariable.hpp
  SU2_CFD/include/variables/CEulerVariable.hpp
  SU2_CFD/include/variables/CIncEulerVariable.hpp
  SU2_CFD/include/variables/CNEMOEulerVariable.hpp
  SU2_CFD/include/variables/CVariable.hpp
  SU2_CFD/src/integration/CMultiGridIntegration.cpp
  SU2_CFD/src/solvers/CIncEulerSolver.cpp
  TestCases/.gitignore
Labels: PR: unreviewed, changelog:fix

#1193 Fix some screen output and frozen limiter logic
  Common/src/CConfig.cpp
  Common/src/geometry/CPhysicalGeometry.cpp
  SU2_CFD/include/numerics/turbulent/turb_sources.hpp
  SU2_CFD/src/numerics/turbulent/turb_sources.cpp
  SU2_CFD/src/output/CFlowCompOutput.cpp
  SU2_CFD/src/output/CFlowIncOutput.cpp
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_CFD/src/output/CNEMOCompOutput.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_CFD/src/solvers/CIncEulerSolver.cpp
  SU2_CFD/src/solvers/CNEMOEulerSolver.cpp
  SU2_CFD/src/solvers/CNEMONSSolver.cpp
  SU2_CFD/src/solvers/CTurbSASolver.cpp
  SU2_CFD/src/solvers/CTurbSSTSolver.cpp
  SU2_CFD/src/variables/CEulerVariable.cpp
  SU2_CFD/src/variables/CIncEulerVariable.cpp
  TestCases/parallel_regression.py
  TestCases/serial_regression.py
Labels: PR: unreviewed, changelog:fix

#1198 Starting point for python cleanup
  SU2_PY/FSI_tools/FSIInterface.py
  SU2_PY/FSI_tools/FSI_config.py
  SU2_PY/FSI_tools/__init__.py
  SU2_PY/FSI_tools/switch.py
  SU2_PY/SU2_Nastran/pysu2_nastran.py
  SU2_PY/meson.build
Labels: PR: reviewed-approved

#1186 Update AUTHORS.md (CHECK IF YOU ARE HERE!)
  AUTHORS.md
Labels: PR: unreviewed, changelog:none

#1195 k-omega SST 2D axisymmetric source terms
  SU2_CFD/include/numerics/turbulent/turb_sources.hpp
  SU2_CFD/src/numerics/turbulent/turb_sources.cpp
  SU2_CFD/src/solvers/CTurbSSTSolver.cpp
  TestCases/axisymmetric_rans/air_nozzle/air_nozzle.cfg
  TestCases/hybrid_regression.py
  TestCases/parallel_regression.py
  TestCases/serial_regression.py
Labels: PR: unreviewed, changelog:fix

#1200 Fix on wall distance calculation from symmetry plane of mesh deformation
  SU2_CFD/src/solvers/CMeshSolver.cpp
Labels: PR: reviewed-approved, changelog:fix

#1199 Fix grid velocities in dual-time RANS simulations with deforming grids (aeroelastic and legacy FSI)
  SU2_CFD/include/integration/CIntegration.hpp
  SU2_CFD/include/integration/CStructuralIntegration.hpp
  SU2_CFD/include/iteration/CFluidIteration.hpp
  SU2_CFD/include/solvers/CFEASolver.hpp
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/src/integration/CIntegration.cpp
  SU2_CFD/src/integration/CStructuralIntegration.cpp
  SU2_CFD/src/iteration/CAdjFluidIteration.cpp
  SU2_CFD/src/iteration/CFEAIteration.cpp
  SU2_CFD/src/iteration/CFluidIteration.cpp
  SU2_CFD/src/iteration/CHeatIteration.cpp
  SU2_CFD/src/solvers/CFEASolver.cpp
  TestCases/parallel_regression.py
  TestCases/serial_regression.py
Labels: PR: unreviewed, changelog:fix

#1201 fix typo Linael -> Linear
  TestCases/axisymmetric_rans/air_nozzle/air_nozzle.cfg
  TestCases/cont_adj_euler/naca0012/inv_NACA0012.cfg
  TestCases/cont_adj_euler/naca0012/inv_NACA0012_FD.cfg
  TestCases/cont_adj_euler/wedge/inv_wedge_ROE_multiobj.cfg
  TestCases/coupled_cht/comp_2d/flow_cylinder.cfg
  TestCases/coupled_cht/comp_2d/solid_cylinder1.cfg
  TestCases/coupled_cht/comp_2d/solid_cylinder2.cfg
  TestCases/coupled_cht/comp_2d/solid_cylinder3.cfg
  TestCases/coupled_cht/disc_adj_incomp_2d/flow_cylinder.cfg
  TestCases/coupled_cht/disc_adj_incomp_2d/solid_cylinder1.cfg
  TestCases/coupled_cht/disc_adj_incomp_2d/solid_cylinder2.cfg
  TestCases/coupled_cht/disc_adj_incomp_2d/solid_cylinder3.cfg
  TestCases/coupled_cht/incomp_2d/flow_cylinder.cfg
  TestCases/coupled_cht/incomp_2d/solid_cylinder1.cfg
  TestCases/coupled_cht/incomp_2d/solid_cylinder2.cfg
  TestCases/coupled_cht/incomp_2d/solid_cylinder3.cfg
  TestCases/coupled_cht/incomp_2d_unsteady/flow_cylinder.cfg
  TestCases/coupled_cht/incomp_2d_unsteady/solid_cylinder1.cfg
  TestCases/coupled_cht/incomp_2d_unsteady/solid_cylinder2.cfg
  TestCases/coupled_cht/incomp_2d_unsteady/solid_cylinder3.cfg
  TestCases/disc_adj_euler/arina2k/Arina2KRS.cfg
  TestCases/disc_adj_euler/cylinder3D/inv_cylinder3D.cfg
  TestCases/disc_adj_incomp_navierstokes/cylinder/heated_cylinder.cfg
  TestCases/disc_adj_incomp_rans/naca0012/turb_naca0012_sa.cfg
  TestCases/disc_adj_incomp_rans/naca0012/turb_naca0012_sst.cfg
  TestCases/incomp_euler/nozzle/inv_nozzle.cfg
  TestCases/incomp_navierstokes/buoyancy_cavity/lam_buoyancy_cavity.cfg
  TestCases/incomp_navierstokes/cylinder/poly_cylinder.cfg
  TestCases/incomp_rans/rough_flatplate/rough_flatplate_incomp.cfg
  TestCases/mms/fvm_incomp_euler/inv_mms_jst.cfg
  TestCases/mms/fvm_incomp_navierstokes/lam_mms_fds.cfg
  TestCases/mms/fvm_navierstokes/lam_mms_roe.cfg
  TestCases/optimization_euler/multiobjective_wedge/inv_wedge_ROE_2surf_1obj.cfg
  TestCases/optimization_euler/multiobjective_wedge/inv_wedge_ROE_multiobj.cfg
  TestCases/optimization_euler/multiobjective_wedge/inv_wedge_ROE_multiobj_1surf.cfg
  TestCases/optimization_euler/multiobjective_wedge/inv_wedge_ROE_multiobj_combo.cfg
  TestCases/py_wrapper/flatPlate_rigidMotion/flatPlate_rigidMotion_Conf.cfg
  TestCases/py_wrapper/flatPlate_unsteady_CHT/unsteady_CHT_FlatPlate_Conf.cfg
  config_template.cfg
Labels: PR: reviewed-approved, changelog:chore

#1197 Cleanup python wrapper, replace legacy python FSI
  Common/include/CConfig.hpp
  Common/include/option_structure.hpp
  Common/src/CConfig.cpp
  SU2_CFD/include/drivers/CDriver.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/src/iteration/CDiscAdjFluidIteration.cpp
  SU2_CFD/src/iteration/CIteration.cpp
  SU2_CFD/src/iteration/CIterationFactory.cpp
  SU2_CFD/src/output/CFlowCompOutput.cpp
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_CFD/src/output/CNEMOCompOutput.cpp
  SU2_CFD/src/python_wrapper_structure.cpp
  SU2_CFD/src/solvers/CSolver.cpp
  SU2_PY/FSI_tools/FSIInterface.py
  SU2_PY/FSI_tools/FSI_config.py
  SU2_PY/FSI_tools/__init__.py
  SU2_PY/FSI_tools/switch.py
  SU2_PY/SU2_Nastran/pysu2_nastran.py
  SU2_PY/meson.build
  TestCases/cont_adj_rans/oneram6/turb_ONERAM6.cfg
  TestCases/gust/inv_gust_NACA0012.cfg
  TestCases/moving_wall/cavity/lam_cavity.cfg
  TestCases/moving_wall/spinning_cylinder/spinning_cylinder.cfg
  TestCases/optimization_euler/pitching_naca64a010/pitching_NACA64A010.cfg
  TestCases/optimization_euler/pitching_oneram6/pitching_ONERAM6.cfg
  TestCases/optimization_euler/rotating_naca0012/rotating_NACA0012.cfg
  TestCases/parallel_regression.py
  TestCases/py_wrapper/flatPlate_rigidMotion/flatPlate_rigidMotion_Conf.cfg
  TestCases/py_wrapper/flatPlate_rigidMotion/launch_flatPlate_rigidMotion.py
  TestCases/py_wrapper/flatPlate_unsteady_CHT/launch_unsteady_CHT_FlatPlate.py
  TestCases/serial_regression.py
Labels: PR: unreviewed, changelog:chore

#1203 Strict compiler warning policy for CI builds
  .github/workflows/regression.yml
  Common/src/CConfig.cpp
  SU2_CFD/include/numerics_simd/flow/diffusion/common.hpp
  SU2_CFD/include/sgs_model.inl
  SU2_CFD/include/solvers/CEulerSolver.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/include/solvers/CNEMONSSolver.hpp
  SU2_CFD/include/solvers/CNSSolver.hpp
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/include/solvers/CTurbSASolver.hpp
  SU2_CFD/include/solvers/CTurbSSTSolver.hpp
  SU2_CFD/include/solvers/CTurbSolver.hpp
  SU2_CFD/src/fluid/CNEMOGas.cpp
  SU2_CFD/src/fluid/CSU2TCLib.cpp
  SU2_CFD/src/numerics/NEMO/CNEMONumerics.cpp
  SU2_CFD/src/output/filewriter/CTecplotBinaryFileWriter.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_CFD/src/solvers/CFEM_DG_EulerSolver.cpp
  SU2_CFD/src/solvers/CHeatSolver.cpp
  SU2_CFD/src/solvers/CNEMONSSolver.cpp
  SU2_CFD/src/solvers/CNSSolver.cpp
  SU2_CFD/src/solvers/CTurbSASolver.cpp
  SU2_CFD/src/solvers/CTurbSSTSolver.cpp
  SU2_CFD/src/solvers/CTurbSolver.cpp
  UnitTests/SU2_CFD/numerics/CNumerics_tests.cpp
  UnitTests/test_driver.cpp
  externals/cgns/meson.build
  externals/metis/meson.build
  externals/parmetis/meson.build
  externals/tecio/teciompisrc/meson.build
  externals/tecio/teciosrc/meson.build
  meson.build
Labels: PR: unreviewed, changelog:chore

#1207 minor fix to auxvargrad in axisymmetric source residual
  SU2_CFD/src/numerics/NEMO/NEMO_sources.cpp
Labels: PR: unreviewed

#1183 Newton-Krylov primal iterations & Krylov discrete adjoint
  Common/include/CConfig.hpp
  Common/include/linear_algebra/CSysMatrix.hpp
  Common/include/linear_algebra/CSysSolve.hpp
  Common/include/linear_algebra/CSysVector.hpp
  Common/include/option_structure.hpp
  Common/include/option_structure.inl
  Common/include/parallelization/mpi_structure.cpp
  Common/include/parallelization/mpi_structure.hpp
  Common/src/CConfig.cpp
  Common/src/geometry/CPhysicalGeometry.cpp
  Common/src/grid_movement/CVolumetricMovement.cpp
  Common/src/linear_algebra/CPastixWrapper.cpp
  Common/src/linear_algebra/CSysMatrix.cpp
  Common/src/linear_algebra/CSysSolve.cpp
  Common/src/linear_algebra/CSysSolve_b.cpp
  Common/src/linear_algebra/CSysVector.cpp
  SU2_CFD/include/drivers/CDiscAdjMultizoneDriver.hpp
  SU2_CFD/include/gradients/computeGradientsGreenGauss.hpp
  SU2_CFD/include/integration/CIntegration.hpp
  SU2_CFD/include/integration/CNewtonIntegration.hpp
  SU2_CFD/include/solvers/CEulerSolver.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/include/solvers/CIncEulerSolver.hpp
  SU2_CFD/include/solvers/CNEMOEulerSolver.hpp
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/include/solvers/CSolverFactory.hpp
  SU2_CFD/include/solvers/CTurbSolver.hpp
  SU2_CFD/include/variables/CVariable.hpp
  SU2_CFD/obj/Makefile.am
  SU2_CFD/src/drivers/CDiscAdjMultizoneDriver.cpp
  SU2_CFD/src/integration/CIntegrationFactory.cpp
  SU2_CFD/src/integration/CNewtonIntegration.cpp
  SU2_CFD/src/iteration/CFluidIteration.cpp
  SU2_CFD/src/meson.build
  SU2_CFD/src/output/CNEMOCompOutput.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_CFD/src/solvers/CFEASolver.cpp
  SU2_CFD/src/solvers/CIncEulerSolver.cpp
  SU2_CFD/src/solvers/CNEMOEulerSolver.cpp
  SU2_CFD/src/solvers/CSolver.cpp
  SU2_CFD/src/solvers/CSolverFactory.cpp
  SU2_CFD/src/solvers/CTurbSASolver.cpp
  SU2_CFD/src/solvers/CTurbSSTSolver.cpp
  SU2_CFD/src/solvers/CTurbSolver.cpp
  SU2_CFD/src/variables/CNEMOEulerVariable.cpp
  SU2_DEF/src/SU2_DEF.cpp
  SU2_DOT/src/SU2_DOT.cpp
  TestCases/parallel_regression.py
  TestCases/rans/oneram6/turb_ONERAM6_nk.cfg
  UnitTests/test_driver.cpp
  config_template.cfg
Labels: PR: unreviewed, changelog:feature

#1208 Fix skin friction coefficient
  SU2_CFD/include/solvers/CFVMFlowSolverBase.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/src/solvers/CNSSolver.cpp
Labels: PR: reviewed-approved, changelog:none

#1212 Small fixes
  SU2_CFD/include/fluid/CMutationTCLib.hpp
  SU2_CFD/src/fluid/CMutationTCLib.cpp
  SU2_CFD/src/numerics/NEMO/NEMO_sources.cpp
  SU2_CFD/src/output/COutput.cpp
  preconfigure.py
Labels: PR: unreviewed, changelog:none
