Repository su2code/SU2, pull requests merged in 2021-03, with the labels that each got.

#773 Streamwise periodicity for incompressible flow
  Common/include/CConfig.hpp
  Common/include/geometry/CGeometry.hpp
  Common/include/geometry/CPhysicalGeometry.hpp
  Common/include/option_structure.hpp
  Common/src/CConfig.cpp
  Common/src/geometry/CPhysicalGeometry.cpp
  Common/src/grid_movement/CVolumetricMovement.cpp
  SU2_CFD/include/numerics/CNumerics.hpp
  SU2_CFD/include/numerics/flow/flow_sources.hpp
  SU2_CFD/include/output/CFlowIncOutput.hpp
  SU2_CFD/include/solvers/CIncEulerSolver.hpp
  SU2_CFD/include/solvers/CIncNSSolver.hpp
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/include/variables/CIncEulerVariable.hpp
  SU2_CFD/include/variables/CVariable.hpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/numerics/flow/flow_sources.cpp
  SU2_CFD/src/output/CFlowIncOutput.cpp
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_CFD/src/output/COutput.cpp
  SU2_CFD/src/solvers/CHeatSolver.cpp
  SU2_CFD/src/solvers/CIncEulerSolver.cpp
  SU2_CFD/src/solvers/CIncNSSolver.cpp
  SU2_CFD/src/variables/CIncEulerVariable.cpp
  SU2_CFD/src/variables/CIncNSVariable.cpp
  SU2_DOT/src/SU2_DOT.cpp
  SU2_PY/SU2/eval/functions.py
  SU2_PY/SU2/eval/gradients.py
  SU2_PY/SU2/io/config.py
  SU2_PY/SU2/io/tools.py
  SU2_PY/SU2/run/direct.py
  TestCases/incomp_navierstokes/streamwise_periodic/README.md
  TestCases/incomp_navierstokes/streamwise_periodic/chtPinArray_2d/DA_configMaster.cfg
  TestCases/incomp_navierstokes/streamwise_periodic/chtPinArray_2d/FD_configMaster.cfg
  TestCases/incomp_navierstokes/streamwise_periodic/chtPinArray_2d/README.md
  TestCases/incomp_navierstokes/streamwise_periodic/chtPinArray_2d/configFluid.cfg
  TestCases/incomp_navierstokes/streamwise_periodic/chtPinArray_2d/configMaster.cfg
  TestCases/incomp_navierstokes/streamwise_periodic/chtPinArray_2d/configSolid.cfg
  TestCases/incomp_navierstokes/streamwise_periodic/chtPinArray_2d/of_grad_findiff.csv.ref
  TestCases/incomp_navierstokes/streamwise_periodic/chtPinArray_3d/configFluid.cfg
  TestCases/incomp_navierstokes/streamwise_periodic/chtPinArray_3d/configMaster.cfg
  TestCases/incomp_navierstokes/streamwise_periodic/chtPinArray_3d/configSolid.cfg
  TestCases/incomp_navierstokes/streamwise_periodic/pipeSlice_3d/sp_pipeSlice_3d_dp_hf_tp.cfg
  TestCases/parallel_regression.py
  TestCases/parallel_regression_AD.py
  TestCases/tutorials.py
  config_template.cfg
Labels: PR: unreviewed, changelog:feature

#1221 Fix calculation of number of spanwise sections
  Common/src/geometry/CPhysicalGeometry.cpp
Labels: PR: unreviewed, changelog:fix

#1222 Removed CSolver::Convective_Residual
  SU2_CFD/include/drivers/CDriver.hpp
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/src/SU2_CFD.cpp
  SU2_CFD/src/integration/CIntegration.cpp
Labels: PR: unreviewed, changelog:chore

#1224 Small adjoint fixes
  Common/src/linear_algebra/CSysSolve.cpp
  SU2_CFD/include/drivers/CDriver.hpp
  SU2_CFD/include/numerics_simd/flow/convection/common.hpp
  SU2_CFD/include/solvers/CEulerSolver.hpp
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/src/drivers/CDiscAdjMultizoneDriver.cpp
  SU2_CFD/src/solvers/CDiscAdjSolver.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  TestCases/parallel_regression_AD.py
  TestCases/serial_regression_AD.py
Labels: PR: unreviewed

#1225 Cleanup more pointers
  Common/src/geometry/CGeometry.cpp
  Common/src/grid_movement/CVolumetricMovement.cpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/src/SU2_CFD.cpp
  SU2_CFD/src/integration/CSingleGridIntegration.cpp
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_CFD/src/output/output_structure_legacy.cpp
  SU2_CFD/src/solvers/CAdjEulerSolver.cpp
  SU2_CFD/src/solvers/CAdjNSSolver.cpp
  SU2_CFD/src/solvers/CAdjTurbSolver.cpp
  SU2_CFD/src/solvers/CDiscAdjFEASolver.cpp
  SU2_CFD/src/solvers/CDiscAdjMeshSolver.cpp
  SU2_CFD/src/solvers/CDiscAdjSolver.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_CFD/src/solvers/CFEASolver.cpp
  SU2_CFD/src/solvers/CFEM_DG_EulerSolver.cpp
  SU2_CFD/src/solvers/CHeatSolver.cpp
  SU2_CFD/src/solvers/CIncEulerSolver.cpp
  SU2_CFD/src/solvers/CMeshSolver.cpp
  SU2_CFD/src/solvers/CNEMOEulerSolver.cpp
  SU2_CFD/src/solvers/CRadP1Solver.cpp
  SU2_CFD/src/solvers/CSolver.cpp
  SU2_CFD/src/solvers/CTransLMSolver.cpp
  SU2_CFD/src/solvers/CTurbSASolver.cpp
  SU2_CFD/src/solvers/CTurbSSTSolver.cpp
  SU2_CFD/src/solvers/CTurbSolver.cpp
  SU2_DOT/src/SU2_DOT.cpp
Labels: PR: reviewed-approved, changelog:chore

#1232 Cleanup COption duplication
  .lgtm.yml
  Common/include/option_structure.inl
  meson_scripts/init.py
Labels: PR: unreviewed, changelog:chore

#1236 Fixed values for turbulence quantities in upstream half-plane
  Common/include/CConfig.hpp
  Common/src/CConfig.cpp
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/include/solvers/CTurbSASolver.hpp
  SU2_CFD/include/solvers/CTurbSSTSolver.hpp
  SU2_CFD/include/solvers/CTurbSolver.hpp
  SU2_CFD/src/integration/CIntegration.cpp
  SU2_CFD/src/solvers/CTurbSASolver.cpp
  SU2_CFD/src/solvers/CTurbSSTSolver.cpp
  SU2_CFD/src/solvers/CTurbSolver.cpp
  TestCases/rans/naca0012/turb_NACA0012_sst_fixedvalues.cfg
  TestCases/serial_regression.py
  config_template.cfg
Labels: PR: unreviewed, changelog:feature

#1228 Linear solver changes to support hybrid parallel AD
  Common/include/linear_algebra/CMatrixVectorProduct.hpp
  Common/include/linear_algebra/CPastixWrapper.hpp
  Common/include/linear_algebra/CPreconditioner.hpp
  Common/include/linear_algebra/CSysMatrix.hpp
  Common/include/linear_algebra/CSysMatrix.inl
  Common/include/linear_algebra/CSysSolve.hpp
  Common/include/linear_algebra/CSysVector.hpp
  Common/include/option_structure.hpp
  Common/include/toolboxes/CQuasiNewtonInvLeastSquares.hpp
  Common/src/CConfig.cpp
  Common/src/grid_movement/CVolumetricMovement.cpp
  Common/src/linear_algebra/CPastixWrapper.cpp
  Common/src/linear_algebra/CSysMatrix.cpp
  Common/src/linear_algebra/CSysSolve.cpp
  Common/src/linear_algebra/CSysSolve_b.cpp
  SU2_CFD/include/drivers/CDiscAdjMultizoneDriver.hpp
  SU2_CFD/src/SU2_CFD.cpp
  SU2_CFD/src/drivers/CDiscAdjMultizoneDriver.cpp
  SU2_CFD/src/integration/CNewtonIntegration.cpp
  SU2_CFD/src/solvers/CMeshSolver.cpp
  TestCases/incomp_navierstokes/streamwise_periodic/chtPinArray_2d/of_grad_findiff.csv.ref
  TestCases/parallel_regression.py
  TestCases/parallel_regression_AD.py
Labels: PR: unreviewed, changelog:feature

#1240 Continuation of #1236
  Common/src/CConfig.cpp
  TestCases/hybrid_regression.py
  TestCases/parallel_regression.py
  TestCases/rans/naca0012/turb_NACA0012_sst.cfg
  TestCases/rans/naca0012/turb_NACA0012_sst_fixedvalues.cfg
  TestCases/rans/naca0012/turb_NACA0012_sst_sust.cfg
  TestCases/serial_regression.py
  config_template.cfg
Labels: PR: unreviewed, changelog:none

#1249 Fix some reconstruction gradient issues on periodic boundaries (when NUM_METHOD_GRAD != NUM_METHOD_GRAD_RECON))
  Common/include/option_structure.hpp
  Common/src/CConfig.cpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/include/solvers/CNEMONSSolver.hpp
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/include/variables/CAdjEulerVariable.hpp
  SU2_CFD/include/variables/CEulerVariable.hpp
  SU2_CFD/include/variables/CHeatVariable.hpp
  SU2_CFD/include/variables/CIncEulerVariable.hpp
  SU2_CFD/include/variables/CNEMOEulerVariable.hpp
  SU2_CFD/include/variables/CTurbVariable.hpp
  SU2_CFD/include/variables/CVariable.hpp
  SU2_CFD/src/integration/CIntegration.cpp
  SU2_CFD/src/solvers/CNEMONSSolver.cpp
  SU2_CFD/src/solvers/CSolver.cpp
Labels: PR: unreviewed, changelog:fix
