Repository su2code/SU2, pull requests merged in 2021-01, with the labels that each got.

#1145 Fix Xcode project and paths
  SU2_CFD/src/interfaces/cfd/CConservativeVarsInterface.cpp
  SU2_CFD/src/interfaces/cfd/CMixingPlaneInterface.cpp
  SU2_CFD/src/interfaces/cfd/CSlidingInterface.cpp
  SU2_CFD/src/interfaces/cht/CConjugateHeatInterface.cpp
  SU2_CFD/src/interfaces/fsi/CDiscAdjFlowTractionInterface.cpp
  SU2_CFD/src/interfaces/fsi/CDisplacementsInterface.cpp
  SU2_CFD/src/interfaces/fsi/CFlowTractionInterface.cpp
  SU2_CFD/src/numerics/NEMO/NEMO_diffusion.cpp
  SU2_CFD/src/numerics/NEMO/convection/ausm.cpp
  SU2_CFD/src/numerics/NEMO/convection/ausmplusup2.cpp
  SU2_CFD/src/numerics/NEMO/convection/ausmpwplus.cpp
  SU2_CFD/src/numerics/NEMO/convection/lax.cpp
  SU2_CFD/src/numerics/NEMO/convection/msw.cpp
  SU2_CFD/src/numerics/NEMO/convection/roe.cpp
  SU2_CFD/src/numerics/continuous_adjoint/adj_convection.cpp
  SU2_CFD/src/numerics/flow/convection/ausm_slau.cpp
  SU2_CFD/src/numerics/flow/convection/centered.cpp
  SU2_CFD/src/numerics/flow/convection/cusp.cpp
  SU2_CFD/src/numerics/flow/convection/fds.cpp
  SU2_CFD/src/numerics/flow/convection/fvs.cpp
  SU2_CFD/src/numerics/flow/convection/hllc.cpp
  SU2_CFD/src/numerics/flow/convection/roe.cpp
  SU2_CFD/src/numerics/flow/flow_diffusion.cpp
  SU2_CFD/src/python_wrapper_structure.cpp
  SU2_CFD/src/solvers/CNEMONSSolver.cpp
  SU2_IDE/Xcode/SU2_CFD.xcodeproj/project.pbxproj
Labels: PR: unreviewed

#1132 BC Transition Model Term2 update
  SU2_CFD/src/numerics/turbulent/turb_sources.cpp
Labels: PR: reviewed-approved, changelog:feature

#1157 Fix compilation with gcc 4.8
  Common/include/linear_algebra/CSysVector.hpp
  Common/include/parallelization/vectorization.hpp
  Common/src/CConfig.cpp
  SU2_CFD/src/numerics/turbulent/turb_sources.cpp
  TestCases/parallel_regression.py
  TestCases/serial_regression.py
  TestCases/tutorials.py
  config_template.cfg
Labels: PR: unreviewed, changelog:fix

#1153 Cleanup adaptation
  SU2_PY/Makefile.am
  SU2_PY/SU2/__init__.py
  SU2_PY/SU2/mesh/__init__.py
  SU2_PY/SU2/mesh/adapt.py
  SU2_PY/SU2/mesh/tools.py
  SU2_PY/SU2/run/__init__.py
  SU2_PY/SU2/run/adaptation.py
  SU2_PY/SU2/run/interface.py
  SU2_PY/documentation.txt
  SU2_PY/mesh_adaptation.py
  SU2_PY/meson.build
  SU2_PY/package_tests.py
  SU2_PY/pySU2/pySU2.i
  SU2_PY/pySU2/pySU2ad.i
  SU2_PY/remove_periodic_halos.py
Labels: PR: unreviewed, changelog:none

#1139 NEMO - transition to primitive limiter
  SU2_CFD/include/numerics/NEMO/NEMO_diffusion.hpp
  SU2_CFD/include/numerics/NEMO/convection/ausm.hpp
  SU2_CFD/include/numerics/NEMO/convection/ausmplusup2.hpp
  SU2_CFD/include/numerics/NEMO/convection/lax.hpp
  SU2_CFD/include/solvers/CNEMOEulerSolver.hpp
  SU2_CFD/include/solvers/CNEMONSSolver.hpp
  SU2_CFD/include/variables/CNEMOEulerVariable.hpp
  SU2_CFD/include/variables/CNEMONSVariable.hpp
  SU2_CFD/include/variables/CVariable.hpp
  SU2_CFD/src/fluid/CNEMOGas.cpp
  SU2_CFD/src/numerics/NEMO/convection/ausm.cpp
  SU2_CFD/src/numerics/NEMO/convection/ausmplusup2.cpp
  SU2_CFD/src/numerics/NEMO/convection/lax.cpp
  SU2_CFD/src/numerics/NEMO/convection/msw.cpp
  SU2_CFD/src/numerics/NEMO/convection/roe.cpp
  SU2_CFD/src/output/CNEMOCompOutput.cpp
  SU2_CFD/src/solvers/CNEMOEulerSolver.cpp
  SU2_CFD/src/solvers/CNEMONSSolver.cpp
  SU2_CFD/src/variables/CNEMOEulerVariable.cpp
  TestCases/parallel_regression.py
  TestCases/serial_regression.py
Labels: PR: unreviewed, changelog:chore, changelog:feature

#1149 Support for UQ and NICF with vectorized (SIMD) centered schemes
  Common/include/grid_movement/CFreeFormDefBox.hpp
  Common/include/grid_movement/CVolumetricMovement.hpp
  Common/include/linear_algebra/CSysVector.hpp
  Common/include/linear_algebra/blas_structure.hpp
  SU2_CFD/include/numerics/CNumerics.hpp
  SU2_CFD/include/numerics/flow/convection/centered.hpp
  SU2_CFD/include/numerics/flow/flow_diffusion.hpp
  SU2_CFD/include/numerics/turbulent/turb_sources.hpp
  SU2_CFD/include/numerics_simd/CNumericsSIMD.cpp
  SU2_CFD/include/numerics_simd/CNumericsSIMD.hpp
  SU2_CFD/include/numerics_simd/flow/diffusion/common.hpp
  SU2_CFD/include/numerics_simd/flow/diffusion/viscous_fluxes.hpp
  SU2_CFD/include/numerics_simd/flow/variables.hpp
  SU2_CFD/include/solvers/CEulerSolver.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/include/variables/CEulerVariable.hpp
  SU2_CFD/include/variables/CVariable.hpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/numerics/CNumerics.cpp
  SU2_CFD/src/numerics/flow/convection/centered.cpp
  SU2_CFD/src/numerics/flow/flow_diffusion.cpp
  SU2_CFD/src/numerics/turbulent/turb_sources.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  TestCases/cont_adj_euler/naca0012/of_grad_cd.dat.ref
  TestCases/cont_adj_euler/naca0012/of_grad_cd_disc.dat.ref
  TestCases/cont_adj_euler/naca0012/of_grad_directdiff.dat.ref
  TestCases/hybrid_regression.py
  TestCases/multiple_ffd/naca0012/of_grad_cd.dat.ref
  TestCases/multiple_ffd/naca0012/of_grad_directdiff.dat.ref
  TestCases/parallel_regression.py
  TestCases/parallel_regression_AD.py
  TestCases/rans_uq/naca0012/turb_NACA0012_uq_1c.cfg
  TestCases/serial_regression.py
  TestCases/serial_regression_AD.py
  TestCases/tutorials.py
Labels: PR: unreviewed, changelog:feature

#1163 Bsend -> Isend on ActDisk and Nearfield methods
  Common/include/option_structure.hpp
  Common/include/parallelization/mpi_structure.hpp
  SU2_CFD/src/SU2_CFD.cpp
  SU2_CFD/src/solvers/CAdjEulerSolver.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  UnitTests/test_driver.cpp
Labels: PR: unreviewed, changelog:chore

#1162 Addition of Source Terms for NEMO Axisymmetric Flows
  SU2_CFD/src/numerics/NEMO/NEMO_sources.cpp
  SU2_CFD/src/solvers/CNEMOEulerSolver.cpp
  SU2_CFD/src/variables/CNEMOEulerVariable.cpp
Labels: PR: unreviewed

#1036 Update adaptive CFL
  Common/include/CConfig.hpp
  Common/include/option_structure.hpp
  Common/src/CConfig.cpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/src/iteration/CFluidIteration.cpp
  SU2_CFD/src/numerics/NEMO/NEMO_sources.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_CFD/src/solvers/CNEMOEulerSolver.cpp
  SU2_CFD/src/solvers/CSolver.cpp
  SU2_CFD/src/solvers/CTurbSolver.cpp
  SU2_IDE/Xcode/SU2_CFD.xcodeproj/project.pbxproj
  TestCases/hybrid_regression.py
  TestCases/parallel_regression.py
  TestCases/parallel_regression_AD.py
  TestCases/rans_uq/naca0012/turb_NACA0012_uq.cfg
  TestCases/rans_uq/naca0012/turb_NACA0012_uq_1c.cfg
  TestCases/rans_uq/naca0012/turb_NACA0012_uq_2c.cfg
  TestCases/rans_uq/naca0012/turb_NACA0012_uq_3c.cfg
  TestCases/rans_uq/naca0012/turb_NACA0012_uq_p1c1.cfg
  TestCases/rans_uq/naca0012/turb_NACA0012_uq_p1c2.cfg
  TestCases/serial_regression.py
  TestCases/serial_regression_AD.py
  TestCases/tutorials.py
  config_template.cfg
Labels: PR: partially-approved, changelog:fix

#1159 Reduce discrete adjoint memory usage ~25%
  Common/include/geometry/CGeometry.hpp
  Common/include/geometry/CPhysicalGeometry.hpp
  Common/include/geometry/dual_grid/CDualGrid.hpp
  Common/include/geometry/dual_grid/CEdge.hpp
  Common/include/geometry/dual_grid/CPoint.hpp
  Common/include/geometry/dual_grid/CVertex.hpp
  Common/include/geometry/primal_grid/CPrimalGrid.hpp
  Common/include/linear_algebra/vector_expressions.hpp
  Common/src/geometry/CGeometry.cpp
  Common/src/geometry/CPhysicalGeometry.cpp
  Common/src/geometry/dual_grid/CEdge.cpp
  Common/src/geometry/dual_grid/CVertex.cpp
  Common/src/geometry/primal_grid/CHexahedron.cpp
  Common/src/geometry/primal_grid/CLine.cpp
  Common/src/geometry/primal_grid/CPrimalGrid.cpp
  Common/src/geometry/primal_grid/CPrism.cpp
  Common/src/geometry/primal_grid/CPyramid.cpp
  Common/src/geometry/primal_grid/CQuadrilateral.cpp
  Common/src/geometry/primal_grid/CTetrahedron.cpp
  Common/src/geometry/primal_grid/CTriangle.cpp
  Common/src/geometry/primal_grid/CVertexMPI.cpp
  Common/src/grid_movement/CVolumetricMovement.cpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/src/drivers/CDiscAdjMultizoneDriver.cpp
  SU2_CFD/src/drivers/CDiscAdjSinglezoneDriver.cpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/iteration/CDiscAdjFEAIteration.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_CFD/src/solvers/CFEASolver.cpp
  SU2_CFD/src/solvers/CIncEulerSolver.cpp
  SU2_CFD/src/solvers/CMeshSolver.cpp
  SU2_CFD/src/solvers/CNEMOEulerSolver.cpp
  SU2_CFD/src/solvers/CNSSolver.cpp
  SU2_CFD/src/solvers/CTurbSASolver.cpp
  SU2_CFD/src/solvers/CTurbSSTSolver.cpp
  SU2_DEF/src/SU2_DEF.cpp
  SU2_DOT/src/SU2_DOT.cpp
  SU2_GEO/src/SU2_GEO.cpp
  TestCases/multiple_ffd/naca0012/of_grad_directdiff.dat.ref
  UnitTests/Common/geometry/CGeometry_test.cpp
  UnitTests/SU2_CFD/gradients.cpp
  UnitTests/UnitQuadTestCase.hpp
Labels: PR: unreviewed, changelog:feature

#1166 Fix MSW
  SU2_CFD/include/numerics/flow/convection/fvs.hpp
  SU2_CFD/include/variables/CEulerVariable.hpp
  SU2_CFD/src/numerics/flow/convection/fvs.cpp
  SU2_CFD/src/solvers/CNSSolver.cpp
Labels: PR: unreviewed, changelog:fix

#1169 Remove mapping of global<->local marker IDs
  Common/include/geometry/CGeometry.hpp
  Common/include/geometry/CPhysicalGeometry.hpp
  Common/src/geometry/CPhysicalGeometry.cpp
Labels: PR: reviewed-approved

#1170 Restructure source residual computation to fix axisymmetric chemsitry/vib source computation
  SU2_CFD/src/numerics/NEMO/NEMO_sources.cpp
  SU2_CFD/src/solvers/CNEMOEulerSolver.cpp
Labels: PR: reviewed-approved

#1167 Fix objective functions (for shape_optimization.py)
  Common/include/CConfig.hpp
  Common/include/option_structure.hpp
  Common/src/CConfig.cpp
  Common/src/grid_movement/CVolumetricMovement.cpp
  SU2_CFD/include/numerics/NEMO/NEMO_diffusion.hpp
  SU2_CFD/include/solvers/CDiscAdjFEASolver.hpp
  SU2_CFD/include/solvers/CDiscAdjMeshSolver.hpp
  SU2_CFD/include/solvers/CDiscAdjSolver.hpp
  SU2_CFD/include/solvers/CEulerSolver.hpp
  SU2_CFD/include/solvers/CFEASolver.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/include/solvers/CIncEulerSolver.hpp
  SU2_CFD/include/solvers/CNSSolver.hpp
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/include/variables/CNEMOEulerVariable.hpp
  SU2_CFD/src/SU2_CFD.cpp
  SU2_CFD/src/drivers/CDiscAdjMultizoneDriver.cpp
  SU2_CFD/src/drivers/CDiscAdjSinglezoneDriver.cpp
  SU2_CFD/src/integration/CMultiGridIntegration.cpp
  SU2_CFD/src/integration/CStructuralIntegration.cpp
  SU2_CFD/src/iteration/CDiscAdjFEAIteration.cpp
  SU2_CFD/src/output/CAdjElasticityOutput.cpp
  SU2_CFD/src/output/CElasticityOutput.cpp
  SU2_CFD/src/output/CFlowCompOutput.cpp
  SU2_CFD/src/output/CFlowIncOutput.cpp
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_CFD/src/output/CHeatOutput.cpp
  SU2_CFD/src/output/CNEMOCompOutput.cpp
  SU2_CFD/src/output/output_structure_legacy.cpp
  SU2_CFD/src/solvers/CDiscAdjFEASolver.cpp
  SU2_CFD/src/solvers/CDiscAdjSolver.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_CFD/src/solvers/CFEASolver.cpp
  SU2_CFD/src/solvers/CIncEulerSolver.cpp
  SU2_CFD/src/solvers/CNEMOEulerSolver.cpp
  SU2_CFD/src/solvers/CNSSolver.cpp
  SU2_DEF/src/SU2_DEF.cpp
  SU2_DOT/src/SU2_DOT.cpp
  SU2_GEO/src/SU2_GEO.cpp
  SU2_PY/SU2/io/historyMap.py
  SU2_PY/topology_optimization.py
  SU2_SOL/src/SU2_SOL.cpp
  TestCases/fea_fsi/MixElemsKnowles/config.cfg
  TestCases/fea_topology/quick_start/settings.cfg
  TestCases/fea_topology/quick_start/settings_compliance.cfg
  TestCases/fea_topology/quick_start/settings_volfrac.cfg
  UnitTests/test_driver.cpp
Labels: PR: unreviewed, changelog:fix

#1158 add testcase for intersection prevention
  TestCases/deformation/intersection_prevention/def_intersect.cfg
  TestCases/serial_regression.py
Labels: PR: reviewed-approved

#1177 Reduce flow solver triplication (comp, incomp, nemo)
  Common/include/linear_algebra/CSysMatrix.hpp
  SU2_CFD/include/solvers/CEulerSolver.hpp
  SU2_CFD/include/solvers/CFEM_DG_EulerSolver.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/include/solvers/CIncEulerSolver.hpp
  SU2_CFD/include/solvers/CIncNSSolver.hpp
  SU2_CFD/include/solvers/CNEMOEulerSolver.hpp
  SU2_CFD/include/solvers/CNSSolver.hpp
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/include/solvers/CTurbSASolver.hpp
  SU2_CFD/include/solvers/CTurbSSTSolver.hpp
  SU2_CFD/include/variables/CNEMOEulerVariable.hpp
  SU2_CFD/include/variables/CNEMONSVariable.hpp
  SU2_CFD/src/SU2_CFD.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_CFD/src/solvers/CIncEulerSolver.cpp
  SU2_CFD/src/solvers/CIncNSSolver.cpp
  SU2_CFD/src/solvers/CNEMOEulerSolver.cpp
  SU2_CFD/src/solvers/CNSSolver.cpp
  TestCases/parallel_regression.py
  TestCases/serial_regression.py
Labels: PR: unreviewed, changelog:chore

#1176 Structural stress penalty function for optimization, fix some CConfig problems
  Common/include/CConfig.hpp
  Common/include/geometry/elements/CElement.hpp
  Common/include/option_structure.hpp
  Common/include/option_structure.inl
  Common/src/CConfig.cpp
  Common/src/grid_movement/CSurfaceMovement.cpp
  SU2_CFD/include/numerics/CNumerics.hpp
  SU2_CFD/include/numerics/elasticity/CFEAElasticity.hpp
  SU2_CFD/include/numerics/elasticity/CFEALinearElasticity.hpp
  SU2_CFD/include/numerics/elasticity/CFEANonlinearElasticity.hpp
  SU2_CFD/include/solvers/CFEASolver.hpp
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/include/variables/CFEAVariable.hpp
  SU2_CFD/include/variables/CVariable.hpp
  SU2_CFD/src/numerics/elasticity/CFEAElasticity.cpp
  SU2_CFD/src/numerics/elasticity/CFEALinearElasticity.cpp
  SU2_CFD/src/numerics/elasticity/CFEANonlinearElasticity.cpp
  SU2_CFD/src/output/CElasticityOutput.cpp
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_CFD/src/solvers/CFEASolver.cpp
  SU2_CFD/src/solvers/CFEM_DG_EulerSolver.cpp
  SU2_PY/SU2/io/historyMap.py
  TestCases/cont_adj_rans/naca0012/turb_nasa.cfg
  TestCases/cont_adj_rans/naca0012/turb_nasa_binary.cfg
  TestCases/disc_adj_euler/arina2k/Arina2KRS.cfg
  TestCases/disc_adj_fea/configAD_fem.cfg
  TestCases/disc_adj_fsi/configFEA.cfg
  TestCases/disc_adj_turbomachinery/transonic_stator_2D/transonic_stator.cfg
  TestCases/fea_topology/config.cfg
  TestCases/navierstokes/poiseuille/lam_poiseuille.cfg
  TestCases/navierstokes/poiseuille/profile_poiseuille.cfg
  TestCases/radiation/p1model/configp1.cfg
  TestCases/turbomachinery/centrifugal_blade/centrifugal_blade.cfg
  TestCases/turbomachinery/centrifugal_stage/centrifugal_stage.cfg
Labels: PR: unreviewed, changelog:feature

#1148 Small update of the python fsi interface
  Common/src/CConfig.cpp
  Common/src/geometry/CGeometry.cpp
  SU2_CFD/src/output/CAdjFlowIncOutput.cpp
  SU2_CFD/src/output/CFlowCompOutput.cpp
  SU2_CFD/src/output/CFlowIncOutput.cpp
  SU2_CFD/src/output/CNEMOCompOutput.cpp
  SU2_PY/FSI_tools/FSIInterface.py
  SU2_PY/FSI_tools/FSI_config.py
  SU2_PY/SU2_Nastran/pysu2_nastran.py
  SU2_PY/fsi_computation.py
  SU2_PY/meson.build
  TestCases/tutorials.py
  config_template.cfg
Labels: PR: unreviewed

#1178 Hybrid parallel (OpenMP) support for incompressible solvers
  SU2_CFD/include/solvers/CAdjEulerSolver.hpp
  SU2_CFD/include/solvers/CEulerSolver.hpp
  SU2_CFD/include/solvers/CFEM_DG_EulerSolver.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/include/solvers/CHeatSolver.hpp
  SU2_CFD/include/solvers/CIncEulerSolver.hpp
  SU2_CFD/include/solvers/CIncNSSolver.hpp
  SU2_CFD/include/solvers/CNEMOEulerSolver.hpp
  SU2_CFD/include/solvers/CNSSolver.hpp
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/include/solvers/CTurbSASolver.hpp
  SU2_CFD/include/solvers/CTurbSSTSolver.hpp
  SU2_CFD/include/variables/CEulerVariable.hpp
  SU2_CFD/include/variables/CIncEulerVariable.hpp
  SU2_CFD/include/variables/CIncNSVariable.hpp
  SU2_CFD/include/variables/CNSVariable.hpp
  SU2_CFD/include/variables/CVariable.hpp
  SU2_CFD/src/drivers/CDiscAdjMultizoneDriver.cpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/drivers/CMultizoneDriver.cpp
  SU2_CFD/src/drivers/CSinglezoneDriver.cpp
  SU2_CFD/src/numerics/flow/convection/roe.cpp
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_CFD/src/solvers/CAdjEulerSolver.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_CFD/src/solvers/CFEASolver.cpp
  SU2_CFD/src/solvers/CFEM_DG_EulerSolver.cpp
  SU2_CFD/src/solvers/CFEM_DG_NSSolver.cpp
  SU2_CFD/src/solvers/CHeatSolver.cpp
  SU2_CFD/src/solvers/CIncEulerSolver.cpp
  SU2_CFD/src/solvers/CIncNSSolver.cpp
  SU2_CFD/src/solvers/CNEMOEulerSolver.cpp
  SU2_CFD/src/solvers/CNSSolver.cpp
  SU2_CFD/src/solvers/CSolver.cpp
  SU2_CFD/src/solvers/CTurbSASolver.cpp
  SU2_CFD/src/variables/CIncEulerVariable.cpp
  SU2_CFD/src/variables/CIncNSVariable.cpp
  SU2_CFD/src/variables/CNSVariable.cpp
  SU2_CFD/src/variables/CVariable.cpp
  TestCases/hybrid_regression.py
Labels: PR: reviewed-approved, changelog:feature
