Repository su2code/SU2, pull requests merged in 2021-09, with the labels that each got.

#1366 fix axisym source term + update regression cases
  SU2_CFD/src/numerics/NEMO/NEMO_sources.cpp
  SU2_CFD/src/numerics/flow/flow_sources.cpp
  TestCases/hybrid_regression.py
  TestCases/parallel_regression.py
  TestCases/serial_regression.py
Labels: PR: reviewed-approved, changelog:fix

#1361 Cleanup ASCII mesh reader
  Common/include/geometry/meshreader/CMeshReaderFVM.hpp
  Common/include/geometry/meshreader/CRectangularMeshReaderFVM.hpp
  Common/include/geometry/meshreader/CSU2ASCIIMeshReaderFVM.hpp
  Common/include/option_structure.hpp
  Common/include/toolboxes/CLinearPartitioner.hpp
  Common/src/geometry/meshreader/CMeshReaderFVM.cpp
  Common/src/geometry/meshreader/CRectangularMeshReaderFVM.cpp
  Common/src/geometry/meshreader/CSU2ASCIIMeshReaderFVM.cpp
  Common/src/toolboxes/CLinearPartitioner.cpp
Labels: PR: reviewed-approved, changelog:chore

#1371 Make primal residual for adjoint like normal screen output.
  SU2_CFD/include/drivers/CDiscAdjSinglezoneDriver.hpp
  SU2_CFD/include/drivers/CDriver.hpp
  SU2_CFD/src/drivers/CDiscAdjMultizoneDriver.cpp
  SU2_CFD/src/drivers/CDiscAdjSinglezoneDriver.cpp
  SU2_CFD/src/drivers/CDriver.cpp
Labels: PR: unreviewed, changelog:chore

#1374 Register TauWall as preaccumulation input
  SU2_CFD/src/numerics/flow/flow_diffusion.cpp
Labels: PR: reviewed-approved, changelog:fix

#1370 Fixing screen output for thermo-based NS initialization
  SU2_CFD/src/solvers/CEulerSolver.cpp
Labels: PR: reviewed-approved, changelog:fix

#1375 Intermediate class of variable for all flow solver variables + Fix for MUSCL in NEMO solver
  Common/include/code_config.hpp
  SU2_CFD/include/limiters/CLimiterDetails.hpp
  SU2_CFD/include/solvers/CEulerSolver.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.hpp
  SU2_CFD/include/solvers/CScalarSolver.inl
  SU2_CFD/include/variables/CEulerVariable.hpp
  SU2_CFD/include/variables/CFlowVariable.hpp
  SU2_CFD/include/variables/CIncEulerVariable.hpp
  SU2_CFD/include/variables/CIncNSVariable.hpp
  SU2_CFD/include/variables/CNEMOEulerVariable.hpp
  SU2_CFD/include/variables/CNEMONSVariable.hpp
  SU2_CFD/include/variables/CNSVariable.hpp
  SU2_CFD/include/variables/CScalarVariable.hpp
  SU2_CFD/include/variables/CVariable.hpp
  SU2_CFD/obj/Makefile.am
  SU2_CFD/src/integration/CMultiGridIntegration.cpp
  SU2_CFD/src/meson.build
  SU2_CFD/src/output/CNEMOCompOutput.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_CFD/src/solvers/CIncEulerSolver.cpp
  SU2_CFD/src/solvers/CNEMOEulerSolver.cpp
  SU2_CFD/src/solvers/CTurbSASolver.cpp
  SU2_CFD/src/solvers/CTurbSSTSolver.cpp
  SU2_CFD/src/variables/CEulerVariable.cpp
  SU2_CFD/src/variables/CFlowVariable.cpp
  SU2_CFD/src/variables/CIncEulerVariable.cpp
  SU2_CFD/src/variables/CIncNSVariable.cpp
  SU2_CFD/src/variables/CNEMOEulerVariable.cpp
  SU2_CFD/src/variables/CNEMONSVariable.cpp
  SU2_CFD/src/variables/CNSVariable.cpp
  SU2_CFD/src/variables/CScalarVariable.cpp
  SU2_CFD/src/variables/CVariable.cpp
  TestCases/parallel_regression.py
  TestCases/serial_regression.py
Labels: PR: unreviewed, changelog:fix, PR: partially-approved

#1382 Add periodic boundary conditions to the heat-equation solver
  SU2_CFD/include/solvers/CHeatSolver.hpp
  SU2_CFD/src/solvers/CHeatSolver.cpp
  TestCases/parallel_regression.py
  TestCases/solid_heat_conduction/periodic_pins/README.md
  TestCases/solid_heat_conduction/periodic_pins/configSolid.cfg
Labels: PR: unreviewed, changelog:feature

#1386 Fix possible segfault using SetConsVarGradient
  SU2_CFD/src/solvers/CNEMOEulerSolver.cpp
  SU2_CFD/src/solvers/CNEMONSSolver.cpp
Labels: bug, PR: unreviewed, PR: reviewed-approved
