Repository su2code/SU2, pull requests merged in 2021-05, with the labels that each got.

#1277 Interpolate restart file when it does not match the mesh
  Common/include/adt/CADTPointsOnlyClass.hpp
  Common/include/toolboxes/CLinearPartitioner.hpp
  Common/src/CConfig.cpp
  Common/src/adt/CADTPointsOnlyClass.cpp
  Common/src/grid_movement/CSurfaceMovement.cpp
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/src/solvers/CSolver.cpp
  TestCases/navierstokes/flatplate/lam_flatplate_unst.cfg
  TestCases/parallel_regression.py
Labels: PR: unreviewed, changelog:feature

#1257 Chore in discrete adjoint bits
  SU2_CFD/include/drivers/CDiscAdjMultizoneDriver.hpp
  SU2_CFD/include/drivers/CMultizoneDriver.hpp
  SU2_CFD/include/output/COutput.hpp
  SU2_CFD/include/solvers/CDiscAdjSolver.hpp
  SU2_CFD/include/variables/CHeatVariable.hpp
  SU2_CFD/include/variables/CVariable.hpp
  SU2_CFD/src/CMarkerProfileReaderFVM.cpp
  SU2_CFD/src/drivers/CDiscAdjMultizoneDriver.cpp
  SU2_CFD/src/drivers/CDiscAdjSinglezoneDriver.cpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/drivers/CMultizoneDriver.cpp
  SU2_CFD/src/integration/CIntegration.cpp
  SU2_CFD/src/iteration/CDiscAdjFluidIteration.cpp
  SU2_CFD/src/iteration/CDiscAdjHeatIteration.cpp
  SU2_CFD/src/iteration/CFluidIteration.cpp
  SU2_CFD/src/output/CFlowIncOutput.cpp
  SU2_CFD/src/output/COutput.cpp
  SU2_CFD/src/solvers/CDiscAdjSolver.cpp
  SU2_CFD/src/solvers/CHeatSolver.cpp
  SU2_CFD/src/solvers/CIncEulerSolver.cpp
  SU2_CFD/src/solvers/CIncNSSolver.cpp
  TestCases/fea_fsi/dyn_fsi/config.cfg
Labels: PR: unreviewed, changelog:chore

#1281 Chore in CHeatSolver.cpp
  SU2_CFD/include/solvers/CHeatSolver.hpp
  SU2_CFD/src/SU2_CFD.cpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/drivers/CMultizoneDriver.cpp
  SU2_CFD/src/drivers/CSinglezoneDriver.cpp
  SU2_CFD/src/iteration/CDiscAdjFluidIteration.cpp
  SU2_CFD/src/iteration/CDiscAdjHeatIteration.cpp
  SU2_CFD/src/iteration/CHeatIteration.cpp
  SU2_CFD/src/solvers/CHeatSolver.cpp
  SU2_CFD/src/solvers/CSolverFactory.cpp
Labels: PR: reviewed-approved, changelog:chore

#1288 Add unsteady cht adjoint testcase
  TestCases/coupled_cht/disc_adj_unsteadyCHT_cylinder/O_mesh_cylinder.geo
  TestCases/coupled_cht/disc_adj_unsteadyCHT_cylinder/README.md
  TestCases/coupled_cht/disc_adj_unsteadyCHT_cylinder/chtMaster.cfg
  TestCases/coupled_cht/disc_adj_unsteadyCHT_cylinder/fluid.cfg
  TestCases/coupled_cht/disc_adj_unsteadyCHT_cylinder/gradient_validation.py
  TestCases/coupled_cht/disc_adj_unsteadyCHT_cylinder/postprocess.py
  TestCases/coupled_cht/disc_adj_unsteadyCHT_cylinder/solid.cfg
  TestCases/parallel_regression_AD.py
Labels: PR: unreviewed

#1286 New data structure for multidimensional data (+some bugfixes)
  Common/include/code_config.hpp
  Common/include/fem/fem_geometry_structure.hpp
  Common/include/geometry/CGeometry.hpp
  Common/include/geometry/CPhysicalGeometry.hpp
  Common/include/geometry/dual_grid/CPoint.hpp
  Common/include/geometry/primal_grid/CPrimalGrid.hpp
  Common/include/parallelization/mpi_structure.cpp
  Common/include/parallelization/mpi_structure.hpp
  Common/include/toolboxes/ndflattener.hpp
  Common/src/fem/fem_wall_distance.cpp
  Common/src/geometry/CGeometry.cpp
  Common/src/geometry/CPhysicalGeometry.cpp
  Common/src/geometry/dual_grid/CPoint.cpp
  UnitTests/Common/toolboxes/ndflattener_tests.cpp
  UnitTests/meson.build
Labels: PR: unreviewed, changelog:fix

#1284 Hybrid Parallel AD (Part 2/?)
  Common/include/CConfig.hpp
  Common/include/basic_types/ad_structure.hpp
  Common/include/basic_types/datatype_structure.hpp
  Common/include/code_config.hpp
  Common/include/geometry/CGeometry.hpp
  Common/include/geometry/dual_grid/CPoint.hpp
  Common/src/CConfig.cpp
  Common/src/basic_types/ad_structure.cpp
  Common/src/geometry/CGeometry.cpp
  Common/src/geometry/dual_grid/CPoint.cpp
  SU2_CFD/include/solvers/CDiscAdjFEASolver.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/include/solvers/CMeshSolver.hpp
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/include/variables/CFEAVariable.hpp
  SU2_CFD/include/variables/CMeshVariable.hpp
  SU2_CFD/include/variables/CVariable.hpp
  SU2_CFD/src/drivers/CDiscAdjMultizoneDriver.cpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/drivers/CMultizoneDriver.cpp
  SU2_CFD/src/drivers/CSinglezoneDriver.cpp
  SU2_CFD/src/iteration/CDiscAdjFEAIteration.cpp
  SU2_CFD/src/iteration/CDiscAdjFluidIteration.cpp
  SU2_CFD/src/iteration/CDiscAdjHeatIteration.cpp
  SU2_CFD/src/output/CFlowCompOutput.cpp
  SU2_CFD/src/output/CFlowIncOutput.cpp
  SU2_CFD/src/output/CNEMOCompOutput.cpp
  SU2_CFD/src/solvers/CDiscAdjFEASolver.cpp
  SU2_CFD/src/solvers/CDiscAdjMeshSolver.cpp
  SU2_CFD/src/solvers/CDiscAdjSolver.cpp
  SU2_CFD/src/solvers/CFEASolver.cpp
  SU2_CFD/src/solvers/CHeatSolver.cpp
  SU2_CFD/src/solvers/CMeshSolver.cpp
  SU2_CFD/src/solvers/CSolver.cpp
  SU2_CFD/src/variables/CMeshVariable.cpp
  SU2_CFD/src/variables/CVariable.cpp
  SU2_DOT/src/SU2_DOT.cpp
  TestCases/disc_adj_fsi/Airfoil_2d/config.cfg
  TestCases/disc_adj_fsi/dyn_fsi/configFlow.cfg
  TestCases/disc_adj_fsi/dyn_fsi/grad_dv.opt.ref
  TestCases/hybrid_regression.py
  TestCases/parallel_regression.py
  TestCases/serial_regression.py
  UnitTests/Common/simple_ad_test.cpp
Labels: PR: unreviewed, changelog:feature
