Repository su2code/SU2, pull requests merged in 2021-06, with the labels that each got.

#1295 Fix restart logic in python FSI
  SU2_CFD/include/drivers/CDriver.hpp
  SU2_CFD/src/python_wrapper_structure.cpp
  SU2_CFD/src/solvers/CMeshSolver.cpp
  SU2_PY/FSI_tools/FSIInterface.py
  SU2_PY/FSI_tools/FSI_config.py
  SU2_PY/SU2_Nastran/pysu2_nastran.py
Labels: PR: reviewed-approved

#1302 Fix fixed CL mode when sideslip is not 0
  Common/src/grid_movement/CVolumetricMovement.cpp
  SU2_CFD/include/output/CAdjFlowCompOutput.hpp
  SU2_CFD/include/output/CAdjFlowIncOutput.hpp
  SU2_CFD/include/output/CElasticityOutput.hpp
  SU2_CFD/include/output/CFlowCompFEMOutput.hpp
  SU2_CFD/include/output/CFlowCompOutput.hpp
  SU2_CFD/include/output/CFlowIncOutput.hpp
  SU2_CFD/include/output/CFlowOutput.hpp
  SU2_CFD/include/output/CMultizoneOutput.hpp
  SU2_CFD/include/output/CNEMOCompOutput.hpp
  SU2_CFD/include/output/COutput.hpp
  SU2_CFD/src/output/CAdjFlowCompOutput.cpp
  SU2_CFD/src/output/CAdjFlowIncOutput.cpp
  SU2_CFD/src/output/CElasticityOutput.cpp
  SU2_CFD/src/output/CFlowCompFEMOutput.cpp
  SU2_CFD/src/output/CFlowCompOutput.cpp
  SU2_CFD/src/output/CFlowIncOutput.cpp
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_CFD/src/output/CMultizoneOutput.cpp
  SU2_CFD/src/output/CNEMOCompOutput.cpp
  SU2_CFD/src/output/COutput.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
Labels: PR: unreviewed, changelog:fix

#1204 Fix SA and SST wall functions
  Common/include/CConfig.hpp
  Common/include/linear_algebra/CSysMatrix.hpp
  Common/include/option_structure.hpp
  Common/include/option_structure.inl
  Common/include/toolboxes/geometry_toolbox.hpp
  Common/src/CConfig.cpp
  Common/src/fem/fem_geometry_structure.cpp
  Common/src/fem/geometry_structure_fem_part.cpp
  Common/src/wall_model.cpp
  SU2_CFD/include/numerics/CNumerics.hpp
  SU2_CFD/include/numerics/NEMO/CNEMONumerics.hpp
  SU2_CFD/include/numerics/flow/flow_diffusion.hpp
  SU2_CFD/include/numerics/turbulent/turb_sources.hpp
  SU2_CFD/include/numerics_simd/CNumericsSIMD.hpp
  SU2_CFD/include/numerics_simd/flow/diffusion/common.hpp
  SU2_CFD/include/numerics_simd/flow/diffusion/viscous_fluxes.hpp
  SU2_CFD/include/numerics_simd/util.hpp
  SU2_CFD/include/solvers/CEulerSolver.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/include/solvers/CIncEulerSolver.hpp
  SU2_CFD/include/solvers/CIncNSSolver.hpp
  SU2_CFD/include/solvers/CNEMOEulerSolver.hpp
  SU2_CFD/include/solvers/CNSSolver.hpp
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/include/solvers/CTurbSASolver.hpp
  SU2_CFD/include/solvers/CTurbSSTSolver.hpp
  SU2_CFD/include/variables/CNSVariable.hpp
  SU2_CFD/include/variables/CVariable.hpp
  SU2_CFD/src/numerics/flow/flow_diffusion.cpp
  SU2_CFD/src/numerics/flow/flow_sources.cpp
  SU2_CFD/src/output/CFlowIncOutput.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_CFD/src/solvers/CIncEulerSolver.cpp
  SU2_CFD/src/solvers/CIncNSSolver.cpp
  SU2_CFD/src/solvers/CNEMOEulerSolver.cpp
  SU2_CFD/src/solvers/CNEMONSSolver.cpp
  SU2_CFD/src/solvers/CNSSolver.cpp
  SU2_CFD/src/solvers/CTurbSASolver.cpp
  SU2_CFD/src/solvers/CTurbSSTSolver.cpp
Labels: PR: unreviewed, changelog:feature

#1303 Class for cubic splines
  Common/include/CConfig.hpp
  Common/include/geometry/CGeometry.hpp
  Common/include/linear_algebra/blas_structure.hpp
  Common/include/option_structure.hpp
  Common/include/option_structure.inl
  Common/include/toolboxes/C1DInterpolation.hpp
  Common/src/CConfig.cpp
  Common/src/geometry/CGeometry.cpp
  Common/src/geometry/CPhysicalGeometry.cpp
  Common/src/grid_movement/CSurfaceMovement.cpp
  Common/src/toolboxes/C1DInterpolation.cpp
  SU2_CFD/include/solvers/CSolverFactory.hpp
  SU2_CFD/src/solvers/CSolver.cpp
  UnitTests/Common/toolboxes/C1DInterpolation_tests.cpp
  UnitTests/meson.build
Labels: PR: unreviewed, changelog:chore

#1311 Fix inverse design Cp function
  SU2_CFD/include/output/CFlowOutput.hpp
  SU2_CFD/src/output/CFlowCompOutput.cpp
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_CFD/src/output/CNEMOCompOutput.cpp
  TestCases/disc_adj_euler/arina2k/TargetCp.dat
  TestCases/parallel_regression_AD.py
  TestCases/serial_regression_AD.py
Labels: PR: reviewed-approved, changelog:fix
