Repository su2code/SU2, pull requests merged in 2021-08, with the labels that each got.

#1341 Fix "per-surface" outputs
  Common/include/toolboxes/printing_toolbox.hpp
  Common/src/toolboxes/printing_toolbox.cpp
  SU2_CFD/include/output/CFVMOutput.hpp
  SU2_CFD/include/output/CFlowCompOutput.hpp
  SU2_CFD/include/output/CFlowOutput.hpp
  SU2_CFD/include/output/CMultizoneOutput.hpp
  SU2_CFD/include/output/COutput.hpp
  SU2_CFD/include/variables/CNEMOEulerVariable.hpp
  SU2_CFD/src/output/CFVMOutput.cpp
  SU2_CFD/src/output/CFlowCompFEMOutput.cpp
  SU2_CFD/src/output/CFlowCompOutput.cpp
  SU2_CFD/src/output/CFlowIncOutput.cpp
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_CFD/src/output/CHeatOutput.cpp
  SU2_CFD/src/output/CMultizoneOutput.cpp
  SU2_CFD/src/output/CNEMOCompOutput.cpp
  SU2_CFD/src/output/COutput.cpp
  TestCases/hybrid_regression.py
  TestCases/navierstokes/flatplate/lam_flatplate.cfg
  TestCases/parallel_regression.py
  TestCases/serial_regression.py
Labels: PR: unreviewed, changelog:fix

#1344 Fix slidingmesh for SA
  SU2_CFD/src/interfaces/cfd/CSlidingInterface.cpp
Labels: PR: unreviewed, changelog:fix

#1343 NEMO - Improvements on the Preprocessing phase and inclusion of Chapmann-Enskog for Mutation++
  Common/include/CConfig.hpp
  Common/include/option_structure.hpp
  Common/src/CConfig.cpp
  SU2_CFD/include/fluid/CNEMOGas.hpp
  SU2_CFD/include/variables/CNEMOEulerVariable.hpp
  SU2_CFD/src/fluid/CMutationTCLib.cpp
  SU2_CFD/src/fluid/CSU2TCLib.cpp
  SU2_CFD/src/solvers/CNEMOEulerSolver.cpp
  SU2_CFD/src/variables/CNEMOEulerVariable.cpp
  config_template.cfg
Labels: enhancement, PR: unreviewed, changelog:chore, PR: partially-approved

#1329 Fix equivalent area calculation
  SU2_CFD/include/output/CFlowOutput.hpp
  SU2_CFD/include/output/COutputLegacy.hpp
  SU2_CFD/include/solvers/CEulerSolver.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/src/output/CFlowCompOutput.cpp
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_CFD/src/output/CNEMOCompOutput.cpp
  SU2_CFD/src/output/output_structure_legacy.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_PY/SU2/io/historyMap.py
  TestCases/optimization_euler/equivalentarea_naca64206/NACA64206.cfg
  TestCases/optimization_euler/equivalentarea_naca64206/README.md
  TestCases/parallel_regression.py
  TestCases/parallel_regression_AD.py
  config_template.cfg
Labels: PR: unreviewed

#1346 Fix the neighbor-finding in `CInterpolator::ReconstructBoundary`
  Common/include/interface_interpolation/CInterpolator.hpp
  Common/include/interface_interpolation/CSlidingMesh.hpp
  Common/src/interface_interpolation/CInterpolator.cpp
  Common/src/interface_interpolation/CIsoparametric.cpp
  Common/src/interface_interpolation/CNearestNeighbor.cpp
  Common/src/interface_interpolation/CRadialBasisFunction.cpp
  Common/src/interface_interpolation/CSlidingMesh.cpp
  TestCases/hybrid_regression.py
  TestCases/parallel_regression.py
  TestCases/serial_regression.py
Labels: PR: unreviewed, changelog:fix

#1351 Delete dead-code for "nearfield" and "interface" boundaries
  Common/include/geometry/CGeometry.hpp
  Common/include/geometry/CMultiGridGeometry.hpp
  Common/include/geometry/CPhysicalGeometry.hpp
  Common/include/option_structure.hpp
  Common/src/geometry/CMultiGridGeometry.cpp
  Common/src/geometry/CPhysicalGeometry.cpp
  SU2_CFD/include/gradients/computeGradientsGreenGauss.hpp
  SU2_CFD/include/solvers/CAdjEulerSolver.hpp
  SU2_CFD/include/solvers/CEulerSolver.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/include/solvers/CTurbSASolver.hpp
  SU2_CFD/include/variables/CAdjEulerVariable.hpp
  SU2_CFD/include/variables/CVariable.hpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/integration/CMultiGridIntegration.cpp
  SU2_CFD/src/iteration/CAdjFluidIteration.cpp
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_CFD/src/solvers/CAdjEulerSolver.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_CFD/src/solvers/CIncEulerSolver.cpp
  SU2_CFD/src/solvers/CSolver.cpp
  SU2_CFD/src/solvers/CTurbSASolver.cpp
  SU2_CFD/src/solvers/CTurbSolver.cpp
  SU2_CFD/src/variables/CAdjEulerVariable.cpp
  SU2_PY/SU2/eval/functions.py
  SU2_PY/SU2/eval/gradients.py
  SU2_PY/SU2/run/direct.py
  TestCases/optimization_euler/equivalentarea_naca64206/NACA64206.cfg
  TestCases/parallel_regression_AD.py
Labels: PR: unreviewed, changelog:chore

#1347 Updating some of the NEMO viscous solver routines.
  SU2_CFD/include/solvers/CFVMFlowSolverBase.hpp
  SU2_CFD/include/solvers/CNEMONSSolver.hpp
  SU2_CFD/include/variables/CNEMOEulerVariable.hpp
  SU2_CFD/include/variables/CNEMONSVariable.hpp
  SU2_CFD/src/fluid/CNEMOGas.cpp
  SU2_CFD/src/solvers/CIncNSSolver.cpp
  SU2_CFD/src/solvers/CNEMOEulerSolver.cpp
  SU2_CFD/src/solvers/CNEMONSSolver.cpp
  SU2_CFD/src/solvers/CNSSolver.cpp
  configure.ac
  preconfigure.py
Labels: changelog:chore, PR: partially-approved

#1357 Updates of SU2-python
  SU2_CFD/include/drivers/CDriver.hpp
  SU2_CFD/src/python_wrapper_structure.cpp
  SU2_PY/FSI_tools/FSIInterface.py
  SU2_PY/FSI_tools/FSI_config.py
  SU2_PY/SU2_Nastran/pysu2_nastran.py
  SU2_PY/fsi_computation.py
Labels: PR: reviewed-approved, changelog:chore

#1359 Update SU2-python 2.0
  SU2_PY/FSI_tools/FSIInterface.py
  SU2_PY/SU2_Nastran/pysu2_nastran.py
Labels: PR: unreviewed

#1352 Refactor CPrimalGrid classes
  Common/include/fem/fem_cgns_elements.hpp
  Common/include/geometry/CGeometry.hpp
  Common/include/geometry/primal_grid/CHexahedron.hpp
  Common/include/geometry/primal_grid/CLine.hpp
  Common/include/geometry/primal_grid/CPrimalGrid.hpp
  Common/include/geometry/primal_grid/CPrimalGridBoundFEM.hpp
  Common/include/geometry/primal_grid/CPrimalGridFEM.hpp
  Common/include/geometry/primal_grid/CPrism.hpp
  Common/include/geometry/primal_grid/CPyramid.hpp
  Common/include/geometry/primal_grid/CQuadrilateral.hpp
  Common/include/geometry/primal_grid/CTetrahedron.hpp
  Common/include/geometry/primal_grid/CTriangle.hpp
  Common/include/geometry/primal_grid/CVertexMPI.hpp
  Common/include/option_structure.hpp
  Common/src/fem/fem_cgns_elements.cpp
  Common/src/fem/geometry_structure_fem_part.cpp
  Common/src/geometry/CGeometry.cpp
  Common/src/geometry/CPhysicalGeometry.cpp
  Common/src/geometry/primal_grid/CHexahedron.cpp
  Common/src/geometry/primal_grid/CLine.cpp
  Common/src/geometry/primal_grid/CPrimalGrid.cpp
  Common/src/geometry/primal_grid/CPrimalGridBoundFEM.cpp
  Common/src/geometry/primal_grid/CPrimalGridFEM.cpp
  Common/src/geometry/primal_grid/CPrism.cpp
  Common/src/geometry/primal_grid/CPyramid.cpp
  Common/src/geometry/primal_grid/CQuadrilateral.cpp
  Common/src/geometry/primal_grid/CTetrahedron.cpp
  Common/src/geometry/primal_grid/CTriangle.cpp
  Common/src/geometry/primal_grid/CVertexMPI.cpp
  Common/src/interface_interpolation/CInterpolator.cpp
  UnitTests/Common/geometry/CGeometry_test.cpp
  UnitTests/Common/geometry/primal_grid/CPrimalGrid_tests.cpp
Labels: PR: unreviewed, changelog:chore
