Repository su2code/SU2, pull requests merged in 2021-07, with the labels that each got.

#1320 Fix download link for binaries
  README.md
Labels: PR: reviewed-approved, changelog:fix

#1310 Feature libROM for reduced order modelling
  Common/include/CConfig.hpp
  Common/include/option_structure.hpp
  Common/src/CConfig.cpp
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/src/drivers/CSinglezoneDriver.cpp
  SU2_CFD/src/solvers/CSolver.cpp
  config_template.cfg
  meson.build
  meson_options.txt
Labels: PR: unreviewed, changelog:feature

#1312 Another charge against pointer to pointer
  Common/include/containers/container_decorators.hpp
  Common/include/geometry/dual_grid/CPoint.hpp
  SU2_CFD/include/numerics/CNumerics.hpp
  SU2_CFD/include/numerics/heat.hpp
  SU2_CFD/include/numerics/radiation.hpp
  SU2_CFD/include/numerics/turbulent/turb_convection.hpp
  SU2_CFD/include/numerics/turbulent/turb_diffusion.hpp
  SU2_CFD/include/output/CFlowOutput.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/include/variables/CAdjEulerVariable.hpp
  SU2_CFD/include/variables/CEulerVariable.hpp
  SU2_CFD/include/variables/CHeatVariable.hpp
  SU2_CFD/include/variables/CIncEulerVariable.hpp
  SU2_CFD/include/variables/CNEMOEulerVariable.hpp
  SU2_CFD/include/variables/CTurbSAVariable.hpp
  SU2_CFD/include/variables/CTurbVariable.hpp
  SU2_CFD/include/variables/CVariable.hpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/integration/CMultiGridIntegration.cpp
  SU2_CFD/src/interfaces/fsi/CFlowTractionInterface.cpp
  SU2_CFD/src/numerics/CNumerics.cpp
  SU2_CFD/src/numerics/NEMO/CNEMONumerics.cpp
  SU2_CFD/src/numerics/NEMO/NEMO_sources.cpp
  SU2_CFD/src/numerics/NEMO/convection/msw.cpp
  SU2_CFD/src/numerics/NEMO/convection/roe.cpp
  SU2_CFD/src/numerics/flow/flow_diffusion.cpp
  SU2_CFD/src/numerics/flow/flow_sources.cpp
  SU2_CFD/src/numerics/heat.cpp
  SU2_CFD/src/numerics/radiation.cpp
  SU2_CFD/src/numerics/turbulent/turb_convection.cpp
  SU2_CFD/src/numerics/turbulent/turb_diffusion.cpp
  SU2_CFD/src/output/CFlowCompOutput.cpp
  SU2_CFD/src/output/CFlowIncOutput.cpp
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_CFD/src/solvers/CAdjEulerSolver.cpp
  SU2_CFD/src/solvers/CAdjNSSolver.cpp
  SU2_CFD/src/solvers/CAdjTurbSolver.cpp
  SU2_CFD/src/solvers/CHeatSolver.cpp
  SU2_CFD/src/solvers/CNEMONSSolver.cpp
  SU2_CFD/src/solvers/CTurbSASolver.cpp
  SU2_CFD/src/variables/CTurbSAVariable.cpp
  TestCases/incomp_navierstokes/streamwise_periodic/chtPinArray_2d/of_grad_findiff.csv.ref
  TestCases/serial_regression.py
  TestCases/serial_regression_AD.py
Labels: PR: unreviewed, changelog:chore

#1326 Fix for axisymmetric terms in NEMO + general NEMO updates
  Common/src/CConfig.cpp
  SU2_CFD/include/fluid/CMutationTCLib.hpp
  SU2_CFD/include/fluid/CNEMOGas.hpp
  SU2_CFD/include/fluid/CSU2TCLib.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/src/fluid/CMutationTCLib.cpp
  SU2_CFD/src/fluid/CNEMOGas.cpp
  SU2_CFD/src/fluid/CSU2TCLib.cpp
  SU2_CFD/src/numerics/NEMO/CNEMONumerics.cpp
  SU2_CFD/src/numerics/NEMO/NEMO_sources.cpp
  SU2_CFD/src/numerics/flow/flow_sources.cpp
  SU2_CFD/src/output/CNEMOCompOutput.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_CFD/src/solvers/CNEMOEulerSolver.cpp
  SU2_CFD/src/solvers/CNEMONSSolver.cpp
  SU2_CFD/src/variables/CNEMOEulerVariable.cpp
  SU2_CFD/src/variables/CNEMONSVariable.cpp
  TestCases/hybrid_regression.py
  TestCases/nonequilibrium/axi_visccone/axi_visccone.cfg
  TestCases/parallel_regression.py
  TestCases/serial_regression.py
Labels: PR: unreviewed, bug, changelog:fix

#1340 SU2-NEMO - Optimize initialization time
  SU2_CFD/include/variables/CNEMOEulerVariable.hpp
  SU2_CFD/src/solvers/CNEMOEulerSolver.cpp
  SU2_CFD/src/solvers/CSolverFactory.cpp
  SU2_CFD/src/variables/CNEMOEulerVariable.cpp
Labels: PR: partially-approved, changelog:fix

#1226 Heat Transfer boundary condition
  .github/workflows/regression.yml
  Common/include/CConfig.hpp
  Common/include/option_structure.hpp
  Common/src/CConfig.cpp
  SU2_CFD/include/solvers/CIncNSSolver.hpp
  SU2_CFD/include/solvers/CNSSolver.hpp
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/src/fluid/CFluidModel.cpp
  SU2_CFD/src/integration/CIntegration.cpp
  SU2_CFD/src/interfaces/cht/CConjugateHeatInterface.cpp
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_CFD/src/output/output_structure_legacy.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_CFD/src/solvers/CFEM_DG_EulerSolver.cpp
  SU2_CFD/src/solvers/CHeatSolver.cpp
  SU2_CFD/src/solvers/CIncEulerSolver.cpp
  SU2_CFD/src/solvers/CIncNSSolver.cpp
  SU2_CFD/src/solvers/CNEMOEulerSolver.cpp
  SU2_CFD/src/solvers/CNSSolver.cpp
  TestCases/coupled_cht/comp_2d/solid_cylinder1.cfg
  TestCases/coupled_cht/comp_2d/solid_cylinder2.cfg
  TestCases/coupled_cht/comp_2d/solid_cylinder3.cfg
  TestCases/coupled_cht/disc_adj_incomp_2d/flow_cylinder.cfg
  TestCases/coupled_cht/disc_adj_incomp_2d/solid_cylinder1.cfg
  TestCases/coupled_cht/disc_adj_incomp_2d/solid_cylinder2.cfg
  TestCases/coupled_cht/disc_adj_incomp_2d/solid_cylinder3.cfg
  TestCases/coupled_cht/disc_adj_unsteadyCHT_cylinder/solid.cfg
  TestCases/coupled_cht/incomp_2d/flow_cylinder.cfg
  TestCases/coupled_cht/incomp_2d/solid_cylinder1.cfg
  TestCases/coupled_cht/incomp_2d/solid_cylinder2.cfg
  TestCases/coupled_cht/incomp_2d/solid_cylinder3.cfg
  TestCases/coupled_cht/incomp_2d_unsteady/flow_cylinder.cfg
  TestCases/coupled_cht/incomp_2d_unsteady/solid_cylinder1.cfg
  TestCases/coupled_cht/incomp_2d_unsteady/solid_cylinder2.cfg
  TestCases/coupled_cht/incomp_2d_unsteady/solid_cylinder3.cfg
  TestCases/disc_adj_heat/disc_adj_heat.cfg
  TestCases/disc_adj_incomp_navierstokes/cylinder/heated_cylinder.cfg
  TestCases/disc_adj_turbomachinery/transonic_stator_2D/transonic_stator.cfg
  TestCases/incomp_navierstokes/buoyancy_cavity/lam_buoyancy_cavity.cfg
  TestCases/incomp_navierstokes/cylinder/poly_cylinder.cfg
  TestCases/incomp_navierstokes/streamwise_periodic/chtPinArray_2d/BC_HeatTransfer.cfg
  TestCases/incomp_navierstokes/streamwise_periodic/chtPinArray_2d/configSolid.cfg
  TestCases/incomp_navierstokes/streamwise_periodic/chtPinArray_3d/configSolid.cfg
  TestCases/mms/fvm_incomp_navierstokes/lam_mms_fds.cfg
  TestCases/navierstokes/poiseuille/lam_poiseuille.cfg
  TestCases/navierstokes/poiseuille/profile_poiseuille.cfg
  TestCases/nicf/LS89/turb_SA_PR.cfg
  TestCases/nicf/LS89/turb_SST_PR.cfg
  TestCases/parallel_regression.py
  TestCases/py_wrapper/flatPlate_unsteady_CHT/unsteady_CHT_FlatPlate_Conf.cfg
  TestCases/radiation/p1model/configp1.cfg
  TestCases/sliding_interface/bars_SST_2D/bars.cfg
  TestCases/turbomachinery/centrifugal_blade/centrifugal_blade.cfg
  TestCases/turbomachinery/centrifugal_stage/centrifugal_stage.cfg
  TestCases/turbomachinery/transonic_stator_2D/transonic_stator.cfg
  TestCases/turbomachinery/transonic_stator_2D/transonic_stator_rst.cfg
  TestCases/tutorials.py
  config_template.cfg
  docker/test/runTests.sh
Labels: PR: unreviewed, changelog:feature

#1339 Updating some dates
  Common/doc/docmain.hpp
  SU2_DEF/obj/Makefile.am
  SU2_DOT/obj/Makefile.am
  SU2_GEO/obj/Makefile.am
  SU2_SOL/obj/Makefile.am
  TestCases/py_wrapper/disc_adj_fea/flow_load_sens/run_adjoint.py
  TestCases/py_wrapper/disc_adj_flow/mesh_disp_sens/run_adjoint.py
  TestCases/py_wrapper/flatPlate_rigidMotion/launch_flatPlate_rigidMotion.py
  TestCases/py_wrapper/flatPlate_unsteady_CHT/launch_unsteady_CHT_FlatPlate.py
  configure.ac
  externals/Makefile.am
  meson_scripts/init.py
  preconfigure.py
  su2omp.syntax.json
Labels: PR: unreviewed, changelog:chore
