Repository su2code/SU2, pull requests merged in 2021-04, with the labels that each got.

#1237 Fix restart file writing for time convergence and 2nd order time stepping
  SU2_CFD/include/output/COutput.hpp
  SU2_CFD/src/drivers/CMultizoneDriver.cpp
  SU2_CFD/src/drivers/CSinglezoneDriver.cpp
  SU2_CFD/src/output/COutput.cpp
Labels: PR: unreviewed

#1256 Fix memory leaks in CHeatSolver
  Common/include/containers/C2DContainer.hpp
  Common/include/containers/container_decorators.hpp
  Common/src/CConfig.cpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/include/solvers/CHeatSolver.hpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_CFD/src/solvers/CHeatSolver.cpp
Labels: PR: unreviewed

#1259 Fixes in history output for time averaged and multizone problems
  Common/include/CConfig.hpp
  Common/include/option_structure.hpp
  Common/src/CConfig.cpp
  SU2_CFD/include/output/CAdjFlowIncOutput.hpp
  SU2_CFD/include/output/CAdjFlowOutput.hpp
  SU2_CFD/include/output/CElasticityOutput.hpp
  SU2_CFD/include/output/CFlowCompFEMOutput.hpp
  SU2_CFD/include/output/CFlowCompOutput.hpp
  SU2_CFD/include/output/CFlowIncOutput.hpp
  SU2_CFD/include/output/CNEMOCompOutput.hpp
  SU2_CFD/include/output/COutput.hpp
  SU2_CFD/include/output/tools/CWindowingTools.hpp
  SU2_CFD/src/output/CAdjFlowCompOutput.cpp
  SU2_CFD/src/output/CAdjFlowIncOutput.cpp
  SU2_CFD/src/output/CFlowCompFEMOutput.cpp
  SU2_CFD/src/output/CFlowCompOutput.cpp
  SU2_CFD/src/output/CFlowIncOutput.cpp
  SU2_CFD/src/output/CNEMOCompOutput.cpp
  SU2_CFD/src/output/COutput.cpp
  SU2_CFD/src/output/tools/CWindowingTools.cpp
  TestCases/fea_fsi/dyn_fsi/config.cfg
  TestCases/fea_fsi/dyn_fsi/configFEA.cfg
  TestCases/fea_fsi/dyn_fsi/configFlow.cfg
  TestCases/parallel_regression_AD.py
Labels: PR: unreviewed, changelog:fix

#1264 Fix inlet profile file loading when not restarting unsteady problems
  Common/include/toolboxes/C1DInterpolation.hpp
  Common/include/toolboxes/geometry_toolbox.hpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/solvers/CSolver.cpp
Labels: PR: reviewed-approved, changelog:fix

#1268 Fix dissipation in transition model and update inlet profile (initial profile from config)
  .gitignore
  SU2_CFD/include/CMarkerProfileReaderFVM.hpp
  SU2_CFD/src/CMarkerProfileReaderFVM.cpp
  SU2_CFD/src/numerics/transition.cpp
  SU2_CFD/src/numerics/turbulent/turb_sources.cpp
  SU2_CFD/src/output/CFlowIncOutput.cpp
  SU2_CFD/src/solvers/CSolver.cpp
  SU2_CFD/src/solvers/CTransLMSolver.cpp
  TestCases/parallel_regression.py
  TestCases/serial_regression.py
Labels: PR: unreviewed, changelog:feature

#1258 Part 2: Make enum -> enum class
  Common/include/CConfig.hpp
  Common/include/interface_interpolation/CRadialBasisFunction.hpp
  Common/include/option_structure.hpp
  Common/include/option_structure.inl
  Common/src/CConfig.cpp
  Common/src/interface_interpolation/CInterpolatorFactory.cpp
  Common/src/interface_interpolation/CRadialBasisFunction.cpp
  Common/src/toolboxes/MMS/CIncTGVSolution.cpp
  Common/src/toolboxes/MMS/CMMSIncNSSolution.cpp
  Common/src/toolboxes/MMS/CMMSNSTwoHalfCirclesSolution.cpp
  Common/src/toolboxes/MMS/CMMSNSTwoHalfSpheresSolution.cpp
  Common/src/toolboxes/MMS/CMMSNSUnitQuadSolution.cpp
  Common/src/toolboxes/MMS/CMMSNSUnitQuadSolutionWallBC.cpp
  Common/src/toolboxes/MMS/CNSUnitQuadSolution.cpp
  Common/src/toolboxes/MMS/CTGVSolution.cpp
  SU2_CFD/include/drivers/CDiscAdjMultizoneDriver.hpp
  SU2_CFD/include/drivers/CDiscAdjSinglezoneDriver.hpp
  SU2_CFD/include/iteration/CDiscAdjFEAIteration.hpp
  SU2_CFD/include/iteration/CDiscAdjFluidIteration.hpp
  SU2_CFD/include/iteration/CDiscAdjHeatIteration.hpp
  SU2_CFD/include/iteration/CIteration.hpp
  SU2_CFD/include/output/CAdjFlowIncOutput.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/src/drivers/CDiscAdjMultizoneDriver.cpp
  SU2_CFD/src/drivers/CDiscAdjSinglezoneDriver.cpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/drivers/CMultizoneDriver.cpp
  SU2_CFD/src/drivers/CSinglezoneDriver.cpp
  SU2_CFD/src/fluid/CFluidModel.cpp
  SU2_CFD/src/integration/CStructuralIntegration.cpp
  SU2_CFD/src/interfaces/cht/CConjugateHeatInterface.cpp
  SU2_CFD/src/iteration/CDiscAdjFEAIteration.cpp
  SU2_CFD/src/iteration/CDiscAdjFluidIteration.cpp
  SU2_CFD/src/iteration/CDiscAdjHeatIteration.cpp
  SU2_CFD/src/iteration/CFEAIteration.cpp
  SU2_CFD/src/iteration/CIteration.cpp
  SU2_CFD/src/numerics/elasticity/CFEAElasticity.cpp
  SU2_CFD/src/numerics/elasticity/CFEANonlinearElasticity.cpp
  SU2_CFD/src/output/CAdjFlowIncOutput.cpp
  SU2_CFD/src/output/CElasticityOutput.cpp
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_CFD/src/output/output_structure_legacy.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_CFD/src/solvers/CFEASolver.cpp
  SU2_CFD/src/solvers/CFEM_DG_EulerSolver.cpp
  SU2_CFD/src/solvers/CIncEulerSolver.cpp
  SU2_CFD/src/solvers/CRadP1Solver.cpp
  SU2_CFD/src/solvers/CTurbSASolver.cpp
  SU2_CFD/src/solvers/CTurbSSTSolver.cpp
  SU2_CFD/src/variables/CFEABoundVariable.cpp
  SU2_CFD/src/variables/CFEAVariable.cpp
Labels: PR: reviewed-approved, changelog:chore

#1174 Velocity transfer at fluid-structure interface
  Common/include/option_structure.hpp
  SU2_CFD/include/solvers/CFEASolver.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/include/solvers/CMeshSolver.hpp
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/include/variables/CFEAVariable.hpp
  SU2_CFD/include/variables/CMeshBoundVariable.hpp
  SU2_CFD/include/variables/CVariable.hpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/integration/CStructuralIntegration.cpp
  SU2_CFD/src/interfaces/fsi/CDisplacementsInterface.cpp
  SU2_CFD/src/output/CElasticityOutput.cpp
  SU2_CFD/src/output/CFlowCompOutput.cpp
  SU2_CFD/src/output/CFlowIncOutput.cpp
  SU2_CFD/src/solvers/CFEASolver.cpp
  SU2_CFD/src/solvers/CMeshSolver.cpp
  SU2_CFD/src/variables/CFEAVariable.cpp
  SU2_CFD/src/variables/CMeshBoundVariable.cpp
  SU2_CFD/src/variables/CVariable.cpp
  TestCases/hybrid_regression.py
  TestCases/parallel_regression.py
  TestCases/serial_regression.py
Labels: PR: unreviewed, changelog:fix

#1266 Multi grid output
  Common/include/CConfig.hpp
  Common/include/geometry/CGeometry.hpp
  Common/include/linear_algebra/CSysMatrix.hpp
  Common/src/CConfig.cpp
  Common/src/geometry/CGeometry.cpp
  SU2_CFD/include/output/CFlowOutput.hpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/output/CFlowCompOutput.cpp
  SU2_CFD/src/output/CFlowIncOutput.cpp
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_CFD/src/output/CNEMOCompOutput.cpp
Labels: PR: unreviewed, changelog:feature

#1269 "Did you mean...?" (make config errors more helpful)
  Common/include/option_structure.inl
  Common/src/CConfig.cpp
Labels: PR: unreviewed, changelog:feature

#1272 Fix dual time restarts with UNST_CFL_NUMBER != 0
  Common/include/CConfig.hpp
  Common/include/fem/fem_geometry_structure.hpp
  Common/include/geometry/CGeometry.hpp
  Common/include/geometry/CMultiGridGeometry.hpp
  Common/include/grid_movement/CSurfaceMovement.hpp
  Common/src/CConfig.cpp
  Common/src/fem/fem_geometry_structure.cpp
  Common/src/geometry/CGeometry.cpp
  Common/src/geometry/CMultiGridGeometry.cpp
  Common/src/grid_movement/CSurfaceMovement.cpp
  SU2_CFD/include/drivers/CDriver.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.hpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/iteration/CDiscAdjFluidIteration.cpp
  SU2_CFD/src/iteration/CIteration.cpp
  TestCases/disc_adj_euler/naca0012_pitching_def/inv_NACA0012_pitching_deform.cfg
  TestCases/disc_adj_euler/naca0012_pitching_def/inv_NACA0012_pitching_deform_ad.cfg
  TestCases/py_wrapper/disc_adj_flow/mesh_disp_sens/configAD_flow.cfg
Labels: PR: unreviewed, changelog:fix
