Repository su2code/SU2, pull requests merged in 2021-11, with the labels that each got.

#1421 Fix compilation with GCC 4.8.5
  SU2_CFD/include/solvers/CScalarSolver.hpp
  SU2_CFD/include/solvers/CScalarSolver.inl
  SU2_CFD/include/solvers/CTransLMSolver.hpp
  SU2_CFD/include/solvers/CTurbSASolver.hpp
  SU2_CFD/include/solvers/CTurbSSTSolver.hpp
  SU2_CFD/include/solvers/CTurbSolver.hpp
  SU2_CFD/src/solvers/CTransLMSolver.cpp
  SU2_CFD/src/solvers/CTurbSASolver.cpp
  SU2_CFD/src/solvers/CTurbSSTSolver.cpp
  SU2_CFD/src/solvers/CTurbSolver.cpp
Labels: PR: unreviewed, changelog:fix

#1418 Test cases for turbulence model variants
  TestCases/parallel_regression.py
  TestCases/turbulence_models/sa/rae2822/turb_SA_BSL_RAE2822.cfg
  TestCases/turbulence_models/sa/rae2822/turb_SA_COMP_EDW_RAE2822.cfg
  TestCases/turbulence_models/sa/rae2822/turb_SA_COMP_RAE2822.cfg
  TestCases/turbulence_models/sa/rae2822/turb_SA_EDW_RAE2822.cfg
  TestCases/turbulence_models/sa/rae2822/turb_SA_NEG_RAE2822.cfg
  TestCases/turbulence_models/sa/rae2822/turb_SA_QCR_RAE2822.cfg
Labels: PR: unreviewed, changelog:chore

#1392 Fix bug in SA-neg diffusion term (and generalize indices of flow variables for use by scalar solvers and numerics)
  SU2_CFD/include/drivers/CDriver.hpp
  SU2_CFD/include/numerics/scalar/scalar_convection.hpp
  SU2_CFD/include/numerics/scalar/scalar_diffusion.hpp
  SU2_CFD/include/numerics/turbulent/turb_convection.hpp
  SU2_CFD/include/numerics/turbulent/turb_diffusion.hpp
  SU2_CFD/include/numerics/turbulent/turb_sources.hpp
  SU2_CFD/include/variables/CEulerVariable.hpp
  SU2_CFD/include/variables/CIncEulerVariable.hpp
  SU2_CFD/include/variables/CIncNSVariable.hpp
  SU2_CFD/include/variables/CNEMOEulerVariable.hpp
  SU2_CFD/include/variables/CNEMONSVariable.hpp
  SU2_CFD/include/variables/CNSVariable.hpp
  SU2_CFD/include/variables/CVariable.hpp
  SU2_CFD/obj/Makefile.am
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/interfaces/fsi/CFlowTractionInterface.cpp
  SU2_CFD/src/meson.build
  SU2_CFD/src/numerics/scalar/scalar_convection.cpp
  SU2_CFD/src/numerics/scalar/scalar_diffusion.cpp
  SU2_CFD/src/numerics/turbulent/turb_convection.cpp
  SU2_CFD/src/numerics/turbulent/turb_diffusion.cpp
  SU2_CFD/src/numerics/turbulent/turb_sources.cpp
  SU2_CFD/src/output/CFlowCompOutput.cpp
  SU2_CFD/src/output/CFlowIncOutput.cpp
  SU2_CFD/src/solvers/CSolver.cpp
  SU2_CFD/src/solvers/CTurbSASolver.cpp
  SU2_CFD/src/variables/CEulerVariable.cpp
  SU2_CFD/src/variables/CIncEulerVariable.cpp
  SU2_CFD/src/variables/CIncNSVariable.cpp
  SU2_CFD/src/variables/CNEMOEulerVariable.cpp
  SU2_CFD/src/variables/CNSVariable.cpp
  TestCases/hybrid_regression.py
  TestCases/hybrid_regression_AD.py
  TestCases/parallel_regression.py
  TestCases/parallel_regression_AD.py
  TestCases/serial_regression.py
  TestCases/serial_regression_AD.py
Labels: PR: unreviewed, changelog:fix

#1422 Implementation of Implicit for viscous NEMO problems
  Common/include/geometry/CGeometry.hpp
  Common/src/CConfig.cpp
  Common/src/geometry/elements/CTETRA1.cpp
  SU2_CFD/include/numerics/NEMO/CNEMONumerics.hpp
  SU2_CFD/include/numerics/NEMO/NEMO_diffusion.hpp
  SU2_CFD/src/fluid/CNEMOGas.cpp
  SU2_CFD/src/numerics/NEMO/CNEMONumerics.cpp
  SU2_CFD/src/numerics/NEMO/NEMO_diffusion.cpp
  SU2_CFD/src/numerics/NEMO/NEMO_sources.cpp
  SU2_CFD/src/output/output_structure_legacy.cpp
  SU2_CFD/src/solvers/CAdjEulerSolver.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_CFD/src/solvers/CNEMOEulerSolver.cpp
  SU2_CFD/src/solvers/CNEMONSSolver.cpp
  SU2_CFD/src/solvers/CNSSolver.cpp
  SU2_PY/FSI_tools/FSI_config.py
  TestCases/nonequilibrium/axi_visccone/axi_visccone.cfg
  TestCases/parallel_regression.py
  TestCases/serial_regression.py
Labels: PR: unreviewed, changelog:feature

#1427 Fixes to inlet files
  SU2_CFD/src/CMarkerProfileReaderFVM.cpp
  SU2_CFD/src/solvers/CSolver.cpp
  SU2_CFD/src/solvers/CTurbSASolver.cpp
  SU2_CFD/src/solvers/CTurbSSTSolver.cpp
Labels: PR: unreviewed, changelog:fix

#1437 Fixed an error for the Coupled RHT-CFD Adjoint test in serial_regression_AD.py
  TestCases/serial_regression_AD.py
Labels: PR: reviewed-approved, changelog:chore

#1438 fix mistake in axisymmetric turbulent source production term
  SU2_CFD/include/numerics/turbulent/turb_sources.hpp
  TestCases/hybrid_regression.py
  TestCases/parallel_regression.py
  TestCases/serial_regression.py
Labels: PR: unreviewed, changelog:fix

#1436 Changes for new libROM API
  Common/src/CConfig.cpp
  SU2_CFD/include/solvers/CSolver.hpp
  config_template.cfg
  meson.build
Labels: PR: unreviewed, changelog:chore

#1445 Fix compilation with GCC 4.8.5
  SU2_CFD/include/numerics/turbulent/turb_sources.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
Labels: PR: unreviewed, changelog:fix

#1450 Clean LoadRestart for Flow/Turb/Heat
  Common/include/CConfig.hpp
  Common/src/CConfig.cpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/src/solvers/CHeatSolver.cpp
  SU2_CFD/src/solvers/CTurbSolver.cpp
Labels: PR: unreviewed, changelog:chore

#1449 Collect Turb output from Comp/Inc/Nemo in CFlowOutput
  SU2_CFD/include/output/CFlowCompOutput.hpp
  SU2_CFD/include/output/CFlowIncOutput.hpp
  SU2_CFD/include/output/CFlowOutput.hpp
  SU2_CFD/include/output/CNEMOCompOutput.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/include/variables/CFlowVariable.hpp
  SU2_CFD/include/variables/CVariable.hpp
  SU2_CFD/src/output/CFlowCompOutput.cpp
  SU2_CFD/src/output/CFlowIncOutput.cpp
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_CFD/src/output/CNEMOCompOutput.cpp
  SU2_CFD/src/solvers/CNEMONSSolver.cpp
Labels: PR: unreviewed, changelog:chore

#1428 Set MUSCL Reconstruction for NEMO in Develop to use smallest limiter val for all primitives
  SU2_CFD/src/output/CNEMOCompOutput.cpp
  SU2_CFD/src/solvers/CNEMOEulerSolver.cpp
  TestCases/nonequilibrium/axi_visccone/axi_visccone.cfg
  TestCases/parallel_regression.py
  TestCases/serial_regression.py
Labels: PR: partially-approved

#1451 change kind_solver option to enum class
  Common/include/CConfig.hpp
  Common/include/option_structure.hpp
  Common/include/toolboxes/MMS/CVerificationSolution.hpp
  Common/src/CConfig.cpp
  Common/src/fem/fem_geometry_structure.cpp
  Common/src/geometry/CGeometry.cpp
  Common/src/toolboxes/MMS/CIncTGVSolution.cpp
  Common/src/toolboxes/MMS/CInviscidVortexSolution.cpp
  Common/src/toolboxes/MMS/CMMSIncEulerSolution.cpp
  Common/src/toolboxes/MMS/CMMSIncNSSolution.cpp
  Common/src/toolboxes/MMS/CMMSNSTwoHalfCirclesSolution.cpp
  Common/src/toolboxes/MMS/CMMSNSTwoHalfSpheresSolution.cpp
  Common/src/toolboxes/MMS/CMMSNSUnitQuadSolution.cpp
  Common/src/toolboxes/MMS/CMMSNSUnitQuadSolutionWallBC.cpp
  Common/src/toolboxes/MMS/CNSUnitQuadSolution.cpp
  Common/src/toolboxes/MMS/CRinglebSolution.cpp
  Common/src/toolboxes/MMS/CTGVSolution.cpp
  SU2_CFD/include/integration/CIntegrationFactory.hpp
  SU2_CFD/include/iteration/CDiscAdjFluidIteration.hpp
  SU2_CFD/include/iteration/CIterationFactory.hpp
  SU2_CFD/include/output/COutputFactory.hpp
  SU2_CFD/include/solvers/CDiscAdjMeshSolver.hpp
  SU2_CFD/include/solvers/CSolverFactory.hpp
  SU2_CFD/src/drivers/CDiscAdjMultizoneDriver.cpp
  SU2_CFD/src/drivers/CDiscAdjSinglezoneDriver.cpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/drivers/CMultizoneDriver.cpp
  SU2_CFD/src/integration/CIntegrationFactory.cpp
  SU2_CFD/src/integration/CMultiGridIntegration.cpp
  SU2_CFD/src/iteration/CAdjFluidIteration.cpp
  SU2_CFD/src/iteration/CFEAIteration.cpp
  SU2_CFD/src/iteration/CFEMFluidIteration.cpp
  SU2_CFD/src/iteration/CFluidIteration.cpp
  SU2_CFD/src/iteration/CHeatIteration.cpp
  SU2_CFD/src/iteration/CIterationFactory.cpp
  SU2_CFD/src/numerics/continuous_adjoint/adj_sources.cpp
  SU2_CFD/src/output/CFlowCompFEMOutput.cpp
  SU2_CFD/src/output/CFlowCompOutput.cpp
  SU2_CFD/src/output/CFlowIncOutput.cpp
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_CFD/src/output/CNEMOCompOutput.cpp
  SU2_CFD/src/output/COutputFactory.cpp
  SU2_CFD/src/output/output_physics.cpp
  SU2_CFD/src/output/output_structure_legacy.cpp
  SU2_CFD/src/python_wrapper_structure.cpp
  SU2_CFD/src/solvers/CAdjNSSolver.cpp
  SU2_CFD/src/solvers/CFEASolver.cpp
  SU2_CFD/src/solvers/CFEM_DG_EulerSolver.cpp
  SU2_CFD/src/solvers/CFEM_DG_NSSolver.cpp
  SU2_CFD/src/solvers/CHeatSolver.cpp
  SU2_CFD/src/solvers/CIncEulerSolver.cpp
  SU2_CFD/src/solvers/CRadSolver.cpp
  SU2_CFD/src/solvers/CSolverFactory.cpp
  SU2_SOL/src/SU2_SOL.cpp
  UnitTests/UnitQuadTestCase.hpp
Labels: PR: unreviewed, changelog:chore

#1453 change transition to enum class
  Common/include/CConfig.hpp
  Common/include/option_structure.hpp
  Common/src/CConfig.cpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/iteration/CAdjFluidIteration.cpp
  SU2_CFD/src/iteration/CFluidIteration.cpp
  SU2_CFD/src/numerics/turbulent/turb_sources.cpp
  SU2_CFD/src/output/CFlowIncOutput.cpp
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_CFD/src/output/output_physics.cpp
  SU2_CFD/src/output/output_structure_legacy.cpp
  SU2_CFD/src/python_wrapper_structure.cpp
  SU2_CFD/src/solvers/CTurbSASolver.cpp
Labels: PR: reviewed-approved, changelog:chore

#1457 change to enum class: SGS_MODEL, SHOCK_CAPTURING, VERIFICATION_SOLUTION
  Common/include/CConfig.hpp
  Common/include/option_structure.hpp
  Common/src/CConfig.cpp
  SU2_CFD/src/output/CFlowCompFEMOutput.cpp
  SU2_CFD/src/solvers/CFEM_DG_EulerSolver.cpp
  SU2_CFD/src/solvers/CFEM_DG_NSSolver.cpp
  SU2_CFD/src/solvers/CSolver.cpp
  SU2_CFD/src/solvers/CSolverFactory.cpp
Labels: PR: reviewed-approved, changelog:chore
