Repository su2code/SU2, pull requests merged in 2022-06, with the labels that each got.

#1657 Add name to AUTHORS.md
  AUTHORS.md
Labels: PR: unreviewed, changelog:none

#1656 Fix missing phase angle in calculation of grid velocity for rigid pitching motion
  Common/src/grid_movement/CVolumetricMovement.cpp
Labels: PR: reviewed-approved, changelog:fix

#1659 Build on self hosted aarch64 runner scheduled 2
  .github/workflows/regression.yml
  .github/workflows/scheduled-arm64.yml
  TestCases/TestCase.py
  TestCases/cont_adj_euler/naca0012/of_grad_cd_disc_aarch64.dat.ref
  TestCases/cont_adj_euler/naca0012/of_grad_directdiff_aarch64.dat.ref
  TestCases/disc_adj_fsi/dyn_fsi/grad_dv.opt.ref
  TestCases/disc_adj_fsi/dyn_fsi/grad_dv_aarch64.opt.ref
  TestCases/grad_smooth/naca0012/of_hess_aarch64.dat.ref
  TestCases/hybrid_regression.py
  TestCases/hybrid_regression_AD.py
  TestCases/incomp_navierstokes/streamwise_periodic/chtPinArray_2d/of_grad_findiff.csv.ref
  TestCases/multiple_ffd/naca0012/of_grad_cd.dat_aarch64.ref
  TestCases/multiple_ffd/naca0012/of_grad_directdiff_aarch64.dat.ref
  TestCases/parallel_regression.py
  TestCases/parallel_regression_AD.py
  TestCases/py_wrapper/translating_NACA0012/forces_0_aarch64.csv.ref
  TestCases/serial_regression.py
  TestCases/serial_regression_AD.py
  TestCases/tutorials.py
  TestCases/vandv.py
  externals/cgns/hdf5/meson.build
  externals/cgns/meson.build
  externals/metis/meson.build
  externals/tecio/teciompisrc/meson.build
  externals/tecio/teciosrc/meson.build
  meson.build
Labels: PR: unreviewed

#1660 update xcode
  SU2_CFD/include/numerics/turbulent/turb_sources.hpp
  SU2_IDE/Xcode/SU2_CFD.xcodeproj/project.pbxproj
Labels: PR: reviewed-approved, changelog:chore

#1668 Move of_grad_cd.csv.ref from TestCases repo to TestCases/ folder
  TestCases/radiation/p1adjoint/of_grad_cd.csv.ref
Labels: PR: reviewed-approved, changelog:none

#1664 Small misc fixes
  SU2_CFD/src/output/COutput.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  TestCases/hybrid_regression.py
  TestCases/serial_regression.py
Labels: PR: unreviewed, changelog:none
