Repository su2code/SU2, pull requests merged in 2022-08, with the labels that each got.

#1637 Add look-up table class
  .github/workflows/regression.yml
  Common/include/containers/CFileReaderLUT.hpp
  Common/include/containers/CLookUpTable.hpp
  Common/include/containers/CTrapezoidalMap.hpp
  Common/lib/Makefile.am
  Common/src/containers/CFileReaderLUT.cpp
  Common/src/containers/CLookUpTable.cpp
  Common/src/containers/CTrapezoidalMap.cpp
  Common/src/containers/meson.build
  Common/src/meson.build
  SU2_CFD/obj/Makefile.am
  SU2_CFD/src/solvers/CIncEulerSolver.cpp
  UnitTests/Common/containers/CLookupTable_tests.cpp
  UnitTests/Common/containers/lookuptable.drg
  UnitTests/meson.build
  UnitTests/test_driver.cpp
Labels: PR: unreviewed, changelog:feature

#1705 User defined functions for history outputs
  Common/include/CConfig.hpp
  Common/src/CConfig.cpp
  SU2_CFD/include/output/CFlowOutput.hpp
  SU2_CFD/include/output/COutput.hpp
  SU2_CFD/include/variables/CIncEulerVariable.hpp
  SU2_CFD/include/variables/CNEMOEulerVariable.hpp
  SU2_CFD/src/output/CFlowCompOutput.cpp
  SU2_CFD/src/output/CFlowIncOutput.cpp
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_CFD/src/output/CNEMOCompOutput.cpp
  SU2_CFD/src/output/COutput.cpp
  TestCases/parallel_regression.py
  TestCases/species_transport/passive_transport_validation/passive_transport.cfg
  TestCases/user_defined_functions/lam_flatplate.cfg
  config_template.cfg
Labels: PR: reviewed-approved, changelog:feature

#1682 Included github actions in the dependabot config
  .github/dependabot.yml
Labels: PR: unreviewed, changelog:chore

#1726 Update catch.hpp to v2.13.9
  UnitTests/Common/containers/CLookupTable_tests.cpp
  UnitTests/Common/toolboxes/ndflattener_tests.cpp
  externals/catch2/catch.hpp
Labels: PR: unreviewed, changelog:chore

#1730 Correct type of history field for INVERSE_DESIGN_PRESSURE and update history map
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_PY/SU2/io/historyMap.py
Labels: PR: unreviewed, changelog:fix

#1731 Fix macos build
  Common/include/containers/CLookUpTable.hpp
  Common/src/containers/CTrapezoidalMap.cpp
Labels: PR: unreviewed, changelog:none

#1732 Fix missing include for gcc 11
  SU2_CFD/include/variables/CNEMOEulerVariable.hpp
Labels: PR: unreviewed, changelog:none

#1740 Fix misleading indentation warnings (GCC 11.2)
  Common/include/parallelization/special_vectorization.hpp
  Common/include/parallelization/vectorization.hpp
Labels: PR: reviewed-approved, changelog:chore

#1741 remove frictional wall heating from incompressible wall function model
  SU2_CFD/src/solvers/CIncNSSolver.cpp
  SU2_CFD/src/solvers/CNSSolver.cpp
  TestCases/serial_regression.py
Labels: PR: unreviewed
