Repository su2code/SU2, pull requests merged in 2022-02, with the labels that each got.

#1530 Integrated Heatflux for flow problems
  Common/include/CConfig.hpp
  Common/include/geometry/CGeometry.hpp
  Common/src/CConfig.cpp
  Common/src/geometry/CGeometry.cpp
  Common/src/geometry/meshreader/CSU2ASCIIMeshReaderFVM.cpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/solvers/CHeatSolver.cpp
  SU2_CFD/src/solvers/CIncNSSolver.cpp
  SU2_CFD/src/solvers/CNEMONSSolver.cpp
  SU2_CFD/src/solvers/CNSSolver.cpp
  TestCases/incomp_navierstokes/streamwise_periodic/chtPinArray_3d/configSolid.cfg
  TestCases/parallel_regression.py
Labels: PR: reviewed-approved, changelog:feature

#1532 Specify C standard
  meson.build
Labels: PR: reviewed-approved, changelog:chore

#1527 Streamwise Periodic restarts using flow.meta + Multizone PerSurface output
  Common/include/CConfig.hpp
  Common/src/CConfig.cpp
  SU2_CFD/include/output/CMultizoneOutput.hpp
  SU2_CFD/include/output/COutput.hpp
  SU2_CFD/include/solvers/CHeatSolver.hpp
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_CFD/src/output/CMultizoneOutput.cpp
  SU2_CFD/src/output/COutput.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_CFD/src/solvers/CIncEulerSolver.cpp
  SU2_CFD/src/solvers/CIncNSSolver.cpp
  SU2_CFD/src/solvers/CSolver.cpp
  TestCases/TestCase.py
  TestCases/incomp_navierstokes/streamwise_periodic/chtPinArray_2d/configMaster.cfg
  TestCases/incomp_navierstokes/streamwise_periodic/chtPinArray_3d/configFluid.cfg
  TestCases/incomp_navierstokes/streamwise_periodic/chtPinArray_3d/configMaster.cfg
  TestCases/incomp_navierstokes/streamwise_periodic/chtPinArray_3d/configSolid.cfg
  TestCases/parallel_regression.py
  TestCases/tutorials.py
Labels: PR: unreviewed, changelog:feature

#1535 Update Xcode
  SU2_CFD/include/numerics/NEMO/CNEMONumerics.hpp
  SU2_CFD/include/output/filewriter/CParaviewVTMFileWriter.hpp
  SU2_IDE/Xcode/SU2_CFD.xcodeproj/project.pbxproj
Labels: PR: reviewed-approved, changelog:chore

#1534 Output heatfluxes (total and maximum) per surface
  SU2_CFD/include/output/CFlowOutput.hpp
  SU2_CFD/include/output/COutput.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.hpp
  SU2_CFD/src/output/CFlowCompOutput.cpp
  SU2_CFD/src/output/CFlowIncOutput.cpp
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_CFD/src/output/CHeatOutput.cpp
  SU2_CFD/src/output/CMultizoneOutput.cpp
  SU2_CFD/src/output/CNEMOCompOutput.cpp
  TestCases/hybrid_regression.py
  TestCases/navierstokes/flatplate/lam_flatplate.cfg
  TestCases/parallel_regression.py
  TestCases/serial_regression.py
Labels: PR: unreviewed, changelog:feature

#1544 Fix WALL_TIME for unsteady + some variable index cleanup
  SU2_CFD/include/output/COutput.hpp
  SU2_CFD/src/drivers/CSinglezoneDriver.cpp
  SU2_CFD/src/output/COutput.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_CFD/src/solvers/CIncEulerSolver.cpp
Labels: PR: reviewed-approved, changelog:fix

#1548 Changed time-averaging algorithm to reduce performance impact.
  AUTHORS.md
  SU2_CFD/include/output/tools/CWindowingTools.hpp
  SU2_CFD/src/output/COutput.cpp
  SU2_CFD/src/output/tools/CWindowingTools.cpp
  UnitTests/SU2_CFD/windowing.cpp
  UnitTests/meson.build
Labels: PR: unreviewed, changelog:feature

#1536 Fix adjoint for streamwise periodic massflow + General handling of adjoints of additional solution variables
  Common/include/option_structure.hpp
  Common/src/CConfig.cpp
  SU2_CFD/include/solvers/CIncEulerSolver.hpp
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/include/variables/CDiscAdjVariable.hpp
  SU2_CFD/include/variables/CHeatVariable.hpp
  SU2_CFD/include/variables/CVariable.hpp
  SU2_CFD/src/drivers/CDiscAdjMultizoneDriver.cpp
  SU2_CFD/src/drivers/CMultizoneDriver.cpp
  SU2_CFD/src/output/CAdjFlowIncOutput.cpp
  SU2_CFD/src/solvers/CDiscAdjSolver.cpp
  SU2_CFD/src/solvers/CIncEulerSolver.cpp
  SU2_CFD/src/solvers/CIncNSSolver.cpp
  SU2_CFD/src/solvers/CSolver.cpp
  SU2_CFD/src/variables/CDiscAdjVariable.cpp
  SU2_CFD/src/variables/CVariable.cpp
  TestCases/incomp_navierstokes/streamwise_periodic/dp-adjoint_chtPinArray_2d/configFluid.cfg
  TestCases/incomp_navierstokes/streamwise_periodic/dp-adjoint_chtPinArray_2d/configMaster.cfg
  TestCases/incomp_navierstokes/streamwise_periodic/dp-adjoint_chtPinArray_2d/configSolid.cfg
  TestCases/parallel_regression_AD.py
  TestCases/tutorials.py
Labels: PR: unreviewed, changelog:feature
