Repository su2code/SU2, pull requests merged in 2022-01, with the labels that each got.

#1479 Inform user of possible CGNS memory usage issue
  Common/src/geometry/meshreader/CCGNSMeshReaderFVM.cpp
Labels: PR: reviewed-approved, changelog:chore

#1482 Fix implicit call for NEMO cases
  SU2_CFD/src/numerics/NEMO/CNEMONumerics.cpp
Labels: PR: reviewed-approved, changelog:fix

#1485 Updating remain version numbers
  configure.ac
  preconfigure.py
Labels: PR: reviewed-approved, changelog:chore

#1491 remove cout line for paraviewVTMFileWriter
  Common/src/CConfig.cpp
  SU2_CFD/src/output/filewriter/CParallelFileWriter.cpp
  SU2_CFD/src/output/filewriter/CParaviewVTMFileWriter.cpp
  config_template.cfg
Labels: PR: unreviewed, changelog:none

#1492 Changed the registration of AD input variables in CDiscAdjFluidIteration
  Common/include/CConfig.hpp
  SU2_CFD/src/drivers/CDiscAdjSinglezoneDriver.cpp
  SU2_CFD/src/iteration/CDiscAdjFluidIteration.cpp
Labels: PR: reviewed-approved, changelog:chore

#1497 NEMO: protection for viscous flow with ionization
  SU2_CFD/src/fluid/CMutationTCLib.cpp
Labels: PR: unreviewed, changelog:fix

#1488 Small cleanup of NEMO solver
  Common/src/CConfig.cpp
  SU2_CFD/include/output/CNEMOCompOutput.hpp
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/fluid/CSU2TCLib.cpp
  SU2_CFD/src/output/CNEMOCompOutput.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_CFD/src/solvers/CNEMOEulerSolver.cpp
  SU2_CFD/src/solvers/CNEMONSSolver.cpp
  SU2_CFD/src/variables/CNEMONSVariable.cpp
Labels: PR: unreviewed, changelog:chore

#1508 Fix cross compilation
  externals/cgns/hdf5/meson.build
Labels: PR: reviewed-approved

#1510 Fix still failing cross compilation
  externals/cgns/hdf5/meson.build
Labels: PR: unreviewed

#1512 Use pregenerated files for cross-compilation of hdf5
  externals/cgns/hdf5/H5T_init.cross
  externals/cgns/hdf5/H5lib_settings.cross
  externals/cgns/hdf5/meson.build
Labels: PR: unreviewed, changelog:chore

#1514 Su2 hdf5 cross compile add missing meson keyword
  externals/cgns/hdf5/meson.build
Labels: PR: unreviewed, changelog:none

#1515 Correct generator dependence for hdf5.
  externals/cgns/hdf5/meson.build
Labels: PR: unreviewed

#1516 Use correct target_machine check for hdf5 cross compilation
  externals/cgns/hdf5/meson.build
Labels: PR: unreviewed, changelog:none

#1526 Fixing some version numbers and dates
  Common/doc/docmain.hpp
  Makefile.am
  SU2_CFD/include/CMarkerProfileReaderFVM.hpp
  SU2_CFD/include/output/CAdjFlowOutput.hpp
  SU2_CFD/src/output/output_structure_legacy.cpp
  SU2_PY/FSI_tools/FSI_config.py
  SU2_PY/Makefile.am
  SU2_SOL/obj/Makefile.am
  TestCases/axisymmetric_rans/air_nozzle/air_nozzle.cfg
  TestCases/disc_adj_rans/naca0012/turb_NACA0012_sa.cfg
  TestCases/disc_adj_rans/naca0012/turb_NACA0012_sst.cfg
  TestCases/fixed_cl/naca0012/inv_NACA0012.cfg
  TestCases/fixed_cl/naca0012/inv_NACA0012_ContAdj.cfg
  TestCases/incomp_rans/rough_flatplate/rough_flatplate_incomp.cfg
  TestCases/nicf/LS89/turb_SA_PR.cfg
  TestCases/nicf/LS89/turb_SST_PR.cfg
  TestCases/py_wrapper/disc_adj_fea/flow_load_sens/run_adjoint.py
  TestCases/py_wrapper/disc_adj_flow/mesh_disp_sens/run_adjoint.py
  TestCases/py_wrapper/flatPlate_rigidMotion/launch_flatPlate_rigidMotion.py
  TestCases/py_wrapper/flatPlate_unsteady_CHT/launch_unsteady_CHT_FlatPlate.py
  TestCases/rans/naca0012/turb_NACA0012_sa.cfg
  TestCases/rans/naca0012/turb_NACA0012_sst.cfg
  TestCases/rans/naca0012/turb_NACA0012_sst_sust.cfg
  TestCases/rans_uq/naca0012/turb_NACA0012_uq.cfg
  TestCases/rans_uq/naca0012/turb_NACA0012_uq_1c.cfg
  TestCases/rans_uq/naca0012/turb_NACA0012_uq_2c.cfg
  TestCases/rans_uq/naca0012/turb_NACA0012_uq_3c.cfg
  TestCases/rans_uq/naca0012/turb_NACA0012_uq_p1c1.cfg
  TestCases/rans_uq/naca0012/turb_NACA0012_uq_p1c2.cfg
  configure.ac
  externals/tecio/Makefile.am
  preconfigure.py
Labels: PR: reviewed-approved, changelog:chore
