Repository su2code/SU2, pull requests merged in 2022-03, with the labels that each got.

#1413 Refactor SA source terms to modularize the specification of model variants and correction terms
  SU2_CFD/include/numerics/CNumerics.hpp
  SU2_CFD/include/numerics/turbulent/turb_sources.hpp
  SU2_CFD/obj/Makefile.am
  SU2_CFD/src/meson.build
  SU2_CFD/src/numerics/flow/flow_diffusion.cpp
  SU2_CFD/src/numerics/turbulent/turb_sources.cpp
  SU2_CFD/src/solvers/CTurbSASolver.cpp
  SU2_CFD/src/solvers/CTurbSSTSolver.cpp
  TestCases/incomp_navierstokes/streamwise_periodic/chtPinArray_2d/of_grad_findiff.csv.ref
  TestCases/parallel_regression.py
  TestCases/vandv.py
Labels: PR: reviewed-approved, changelog:feature

#1554 Fix supersonic inflow/outflow for turbulence and passive scalar solvers
  SU2_CFD/include/solvers/CScalarSolver.hpp
Labels: PR: reviewed-approved, changelog:fix

#1556 Fix Newton-Krylov for unsteady problems
  Common/include/CConfig.hpp
  Common/src/CConfig.cpp
  SU2_CFD/include/integration/CNewtonIntegration.hpp
  SU2_CFD/src/integration/CNewtonIntegration.cpp
Labels: PR: reviewed-approved, changelog:fix

#1555 NEMO: Native Air-7 gas model implementation for inviscid flows
  Common/include/CConfig.hpp
  Common/src/CConfig.cpp
  SU2_CFD/src/fluid/CNEMOGas.cpp
  SU2_CFD/src/fluid/CSU2TCLib.cpp
  SU2_CFD/src/numerics/NEMO/convection/ausm.cpp
  SU2_CFD/src/numerics/NEMO/convection/ausmplusup2.cpp
  SU2_CFD/src/output/CNEMOCompOutput.cpp
  SU2_CFD/src/variables/CNEMOEulerVariable.cpp
  TestCases/disc_adj_fsi/dyn_fsi/config.cfg
  TestCases/disc_adj_fsi/dyn_fsi/configFEA.cfg
  TestCases/disc_adj_fsi/dyn_fsi/configFlow.cfg
  TestCases/nonequilibrium/thermalbath/finitechemistry/weakly_ionized.cfg
  TestCases/parallel_regression.py
Labels: PR: unreviewed

#1561 Fix surface output at viscous/inviscid marker intersection
  SU2_CFD/include/output/CFlowCompFEMOutput.hpp
  SU2_CFD/src/output/CFlowCompFEMOutput.cpp
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_CFD/src/output/CHeatOutput.cpp
Labels: PR: reviewed-approved, changelog:fix

#1550 changed limiter to enum class to fix adjoint species bug
  Common/include/CConfig.hpp
  Common/include/basic_types/ad_structure.hpp
  Common/include/option_structure.hpp
  Common/src/CConfig.cpp
  SU2_CFD/include/limiters/CLimiterDetails.hpp
  SU2_CFD/include/limiters/computeLimiters.hpp
  SU2_CFD/include/limiters/computeLimiters_impl.hpp
  SU2_CFD/include/numerics_simd/flow/convection/common.hpp
  SU2_CFD/include/numerics_simd/flow/convection/roe.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/include/solvers/CScalarSolver.inl
  SU2_CFD/src/iteration/CFluidIteration.cpp
  SU2_CFD/src/limiters/CLimiterDetails.cpp
  SU2_CFD/src/output/CFlowCompOutput.cpp
  SU2_CFD/src/output/CFlowIncOutput.cpp
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_CFD/src/output/CNEMOCompOutput.cpp
  SU2_CFD/src/solvers/CAdjEulerSolver.cpp
  SU2_CFD/src/solvers/CAdjNSSolver.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_CFD/src/solvers/CIncEulerSolver.cpp
  SU2_CFD/src/solvers/CIncNSSolver.cpp
  SU2_CFD/src/solvers/CNEMOEulerSolver.cpp
  SU2_CFD/src/solvers/CNEMONSSolver.cpp
  SU2_CFD/src/solvers/CNSSolver.cpp
  SU2_CFD/src/solvers/CSolver.cpp
  SU2_CFD/src/solvers/CTurbSASolver.cpp
  SU2_CFD/src/solvers/CTurbSSTSolver.cpp
  SU2_CFD/src/variables/CFlowVariable.cpp
Labels: PR: unreviewed

#1563 Fix 2D rotational periodicity
  SU2_CFD/src/solvers/CSolver.cpp
  TestCases/hybrid_regression.py
  TestCases/navierstokes/periodic2D/config.cfg
  TestCases/navierstokes/periodic2D/inlet.dat
  TestCases/navierstokes/periodic2D/sector.geo
  TestCases/navierstokes/periodic2D/sector.su2
Labels: PR: unreviewed, changelog:fix

#1559 Improve the configuration file for the SA Neg test case
  TestCases/parallel_regression.py
  TestCases/turbulence_models/sa/rae2822/turb_SA_NEG_RAE2822.cfg
Labels: PR: unreviewed, changelog:chore

#1571 Fix for discrete adjoint: axisymmetry + SST turbulence model
  AUTHORS.md
  Common/src/CConfig.cpp
  SU2_CFD/include/numerics/turbulent/turb_sources.hpp
  TestCases/axisymmetric_rans/air_nozzle/air_nozzle.cfg
  TestCases/parallel_regression_AD.py
Labels: PR: unreviewed, changelog:fix, PR: partially-approved

#1576 Bugfix: temporary config filename
  AUTHORS.md
  SU2_PY/SU2/io/config.py
Labels: PR: unreviewed, changelog:fix

#1578 Clean air-nozzle cfg
  TestCases/axisymmetric_rans/air_nozzle/air_nozzle.cfg
Labels: PR: unreviewed, changelog:chore

#1566 Fix CGNS mesh reader for multizone problems (one CGNS mesh per zone)
  Common/include/geometry/meshreader/CCGNSMeshReaderFVM.hpp
  Common/src/geometry/meshreader/CCGNSMeshReaderFVM.cpp
Labels: PR: reviewed-approved, changelog:fix, PR: partially-approved

#1579 Fix some "resource not released in destructor" warnings
  Common/include/CConfig.hpp
  Common/include/option_structure.inl
  Common/src/CConfig.cpp
Labels: PR: unreviewed, changelog:chore

#1552 Allow different OUTPUT_WRT_FREQ for each output file
  Common/include/CConfig.hpp
  Common/include/adt/CADTElemClass.hpp
  Common/include/grid_movement/CFreeFormDefBox.hpp
  Common/include/option_structure.inl
  Common/src/CConfig.cpp
  Common/src/grid_movement/CSurfaceMovement.cpp
  QuickStart/inv_NACA0012.cfg
  SU2_CFD/include/numerics/CNumerics.hpp
  SU2_CFD/include/output/CFlowOutput.hpp
  SU2_CFD/include/output/COutput.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/src/drivers/CDiscAdjMultizoneDriver.cpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_CFD/src/output/COutput.cpp
  SU2_CFD/src/output/output_structure_legacy.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_SOL/src/SU2_SOL.cpp
  TestCases/incomp_rans/rough_flatplate/rough_flatplate_incomp.cfg
  TestCases/wallfunctions/flatplate/incompressible_SA/turb_SA_flatplate.cfg
  TestCases/wallfunctions/flatplate/incompressible_SST/turb_SST_flatplate.cfg
  config_template.cfg
Labels: PR: reviewed-approved, changelog:feature

#1586 Fix spelling mistakes
  Common/include/CConfig.hpp
  Common/src/CConfig.cpp
  SU2_CFD/include/gradients/computeGradientsLeastSquares.hpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/solvers/CTurbSSTSolver.cpp
  SU2_PY/SU2/eval/design.py
Labels: PR: reviewed-approved, changelog:chore
