Repository su2code/SU2, pull requests merged in 2022-10, with the labels that each got.

#1780 Fix inconsistent mass flow rate for axisymmetry
  SU2_CFD/src/solvers/CIncEulerSolver.cpp
Labels: PR: unreviewed, changelog:fix

#1787 Fixing Schmidt diffusivity model and adding option of Constant Lewis number
  Common/include/CConfig.hpp
  Common/include/option_structure.hpp
  Common/src/CConfig.cpp
  SU2_CFD/include/fluid/CConstantLewisDiffusivity.hpp
  SU2_CFD/include/fluid/CUnityLewisDiffusivity.hpp
  SU2_CFD/src/fluid/CFluidModel.cpp
Labels: PR: reviewed-approved

#1786 Fix initial inlet profile writing for MPI
  SU2_CFD/src/CMarkerProfileReaderFVM.cpp
  SU2_CFD/src/output/CFlowOutput.cpp
Labels: PR: reviewed-approved, changelog:fix

#1785 Source term for axisymmetry in species transport
  Common/src/CConfig.cpp
  SU2_CFD/include/numerics/species/species_sources.hpp
  SU2_CFD/include/solvers/CSpeciesSolver.hpp
  SU2_CFD/src/numerics/species/species_sources.cpp
  SU2_CFD/src/solvers/CSpeciesSolver.cpp
Labels: PR: unreviewed, changelog:feature

#1417 Addition of catalytic isothermal wall boundary conditions in SU2-NEMO
  .github/workflows/regression.yml
  Common/include/CConfig.hpp
  Common/src/CConfig.cpp
  SU2_CFD/include/fluid/CNEMOGas.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/src/fluid/CMutationTCLib.cpp
  SU2_CFD/src/fluid/CSU2TCLib.cpp
  SU2_CFD/src/solvers/CNEMOEulerSolver.cpp
  SU2_CFD/src/solvers/CNEMONSSolver.cpp
  TestCases/nonequilibrium/viscous/axi_visccone.cfg
  TestCases/nonequilibrium/viscous/partial_cat.cfg
  TestCases/nonequilibrium/viscous/super_cat.cfg
  TestCases/parallel_regression.py
  TestCases/serial_regression.py
Labels: PR: unreviewed

#1791 Fix wallfunction variable computation on mpi rank edges
  SU2_CFD/src/solvers/CIncNSSolver.cpp
  SU2_CFD/src/solvers/CTurbSSTSolver.cpp
Labels: PR: reviewed-approved, changelog:fix

#1792 Update LUT routine
  Common/include/containers/CFileReaderLUT.hpp
  Common/src/CConfig.cpp
  Common/src/containers/CFileReaderLUT.cpp
  Common/src/containers/CLookUpTable.cpp
  Common/src/containers/CTrapezoidalMap.cpp
  SU2_CFD/src/solvers/CSpeciesSolver.cpp
  UnitTests/Common/containers/CLookupTable_tests.cpp
  UnitTests/Common/containers/lookuptable.drg
Labels: PR: unreviewed, changelog:chore

#1751 Langtry and Menter transition model
  AUTHORS.md
  Common/include/CConfig.hpp
  Common/include/option_structure.hpp
  Common/src/CConfig.cpp
  SU2_CFD/include/drivers/CDriver.hpp
  SU2_CFD/include/numerics/CNumerics.hpp
  SU2_CFD/include/numerics/transition.hpp
  SU2_CFD/include/numerics/turbulent/transition/trans_convection.hpp
  SU2_CFD/include/numerics/turbulent/transition/trans_diffusion.hpp
  SU2_CFD/include/numerics/turbulent/transition/trans_sources.hpp
  SU2_CFD/include/numerics/turbulent/turb_sources.hpp
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/include/solvers/CSolverFactory.hpp
  SU2_CFD/include/solvers/CTransLMSolver.hpp
  SU2_CFD/include/solvers/CTurbSolver.hpp
  SU2_CFD/include/variables/CTransLMVariable.hpp
  SU2_CFD/include/variables/CTurbSSTVariable.hpp
  SU2_CFD/include/variables/CVariable.hpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/iteration/CFluidIteration.cpp
  SU2_CFD/src/meson.build
  SU2_CFD/src/numerics/transition.cpp
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_CFD/src/solvers/CSolverFactory.cpp
  SU2_CFD/src/solvers/CTransLMSolver.cpp
  SU2_CFD/src/solvers/CTurbSSTSolver.cpp
  SU2_CFD/src/solvers/CTurbSolver.cpp
  SU2_CFD/src/variables/CTransLMVariable.cpp
  SU2_CFD/src/variables/CTurbSSTVariable.cpp
  TestCases/tutorials.py
Labels: PR: unreviewed, changelog:feature
