Repository su2code/SU2, pull requests merged in 2022-04, with the labels that each got.

#1587 Allow field groups in SCREEN_OUTPUT (e.g. RMS_RES like for HISTORY_OUTPUT)
  QuickStart/inv_NACA0012.cfg
  SU2_CFD/include/output/COutput.hpp
  SU2_CFD/src/output/COutput.cpp
  TestCases/navierstokes/periodic2D/config.cfg
Labels: PR: reviewed-approved, changelog:feature, PR: partially-approved

#1595 Fix reference pressure for Cp with moving frames (e.g. ROTATING_FRAME)
  .github/workflows/regression.yml
  SU2_CFD/include/solvers/CFEM_DG_EulerSolver.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.hpp
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/src/output/CFlowCompOutput.cpp
  SU2_CFD/src/output/CFlowIncOutput.cpp
  SU2_CFD/src/output/CNEMOCompOutput.cpp
  SU2_CFD/src/solvers/CSolver.cpp
  TestCases/hybrid_regression.py
  TestCases/py_wrapper/translating_NACA0012/config.cfg
  TestCases/py_wrapper/translating_NACA0012/forces_0.csv.ref
  TestCases/py_wrapper/translating_NACA0012/run_su2.py
Labels: PR: unreviewed, changelog:fix

#1601 Fix running averages for restarted simulations
  Common/src/CConfig.cpp
  TestCases/hybrid_regression.py
  TestCases/parallel_regression.py
  TestCases/serial_regression.py
  TestCases/unsteady/square_cylinder/turb_square.cfg
Labels: PR: unreviewed, changelog:fix

#1612 Update Bug Report and Pull Request templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/pull_request_template.md
Labels: PR: reviewed-approved, changelog:none

#1615 Try to detect wrong meson being used to configure SU2
  meson.build
Labels: PR: reviewed-approved, changelog:none

#1618 Check that SWIG version is at least 3.0.11
  SU2_PY/pySU2/meson.build
Labels: changelog:chore, PR: partially-approved
