Repository su2code/SU2, pull requests merged in 2022-05, with the labels that each got.

#1616 Run the unsteady NACA0012 tutorial for 20 timesteps
  SU2_CFD/src/output/COutput.cpp
  TestCases/tutorials.py
Labels: PR: unreviewed, changelog:chore

#1632 Fixes #1568 - Prefer loading zlib and szip libraries dynamically
  externals/cgns/hdf5/meson.build
Labels: PR: reviewed-approved, changelog:fix

#1621 Free-flying aircraft that translates and rotates about the center of gravity (rotating frame + translation)
  Common/src/geometry/CGeometry.cpp
  TestCases/py_wrapper/translating_NACA0012/config.cfg
  TestCases/py_wrapper/translating_NACA0012/forces_0.csv.ref
  config_template.cfg
Labels: PR: unreviewed, changelog:feature

#1634 2nd try at fixing hdf5 + python wrapper problems
  externals/cgns/hdf5/meson.build
Labels: PR: unreviewed, changelog:none

#1636 3rd try at fixing hdf5 + python wrapper problems
  .github/workflows/release-management.yml
  externals/cgns/hdf5/meson.build
  meson.build
  meson_options.txt
Labels: PR: unreviewed, changelog:none

#1577 Improve cauchy convergence to handle quantities that converge to small values
  SU2_CFD/src/output/COutput.cpp
Labels: PR: unreviewed, changelog:feature

#1362 Solve segmentation faults for FULLMG_CYCLE
  Common/include/CConfig.hpp
  SU2_CFD/include/integration/CIntegration.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/src/solvers/CTurbSSTSolver.cpp
Labels: PR: reviewed-approved, changelog:fix

#1631 Feature inc inlet correction
  Common/include/geometry/dual_grid/CPoint.hpp
  Common/src/geometry/CPhysicalGeometry.cpp
  Common/src/geometry/dual_grid/CPoint.cpp
  SU2_CFD/src/solvers/CIncEulerSolver.cpp
  TestCases/hybrid_regression.py
  TestCases/parallel_regression.py
  TestCases/serial_regression.py
  TestCases/tutorials.py
Labels: PR: reviewed-approved

#1638 Bugfix for a call to LoadUnsteady_Solution in CDiscAdjFluidIteration::Preprocess
  SU2_CFD/src/iteration/CDiscAdjFluidIteration.cpp
Labels: PR: reviewed-approved, changelog:fix

#1643 INCINLET_USENORMALS uses normal of inlet boundary for velocity inlets in addition to pressure inlets
  SU2_CFD/src/solvers/CIncEulerSolver.cpp
Labels: PR: reviewed-approved, changelog:fix

#1627 Newton-Raphson for NEMO temperature computations
  SU2_CFD/include/fluid/CMutationTCLib.hpp
  SU2_CFD/include/fluid/CNEMOGas.hpp
  SU2_CFD/include/fluid/CSU2TCLib.hpp
  SU2_CFD/src/fluid/CMutationTCLib.cpp
  SU2_CFD/src/fluid/CSU2TCLib.cpp
  SU2_CFD/src/variables/CNEMOEulerVariable.cpp
  TestCases/parallel_regression.py
  TestCases/serial_regression.py
Labels: changelog:feature, PR: partially-approved

#1646 New SA version/correction combinations and new way of specifying them in the config (SA_OPTIONS=...)
  Common/include/CConfig.hpp
  Common/include/option_structure.hpp
  Common/src/CConfig.cpp
  SU2_CFD/include/numerics/turbulent/turb_sources.hpp
  SU2_CFD/include/numerics_simd/flow/diffusion/viscous_fluxes.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/numerics/flow/flow_diffusion.cpp
  SU2_CFD/src/output/CFlowIncOutput.cpp
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_CFD/src/output/output_physics.cpp
  SU2_CFD/src/output/output_structure_legacy.cpp
  SU2_CFD/src/solvers/CAdjNSSolver.cpp
  SU2_CFD/src/solvers/CBaselineSolver.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_CFD/src/solvers/CTurbSASolver.cpp
  TestCases/disc_adj_rans/naca0012/turb_NACA0012_sa.cfg
  TestCases/rans/naca0012/turb_NACA0012_sa.cfg
  TestCases/transition/E387_Airfoil/transitional_BC_model_ConfigFile.cfg
  TestCases/transition/Schubauer_Klebanoff/transitional_BC_model_ConfigFile.cfg
  TestCases/transition/T3A_FlatPlate/transitional_BC_model_ConfigFile.cfg
  TestCases/turbulence_models/sa/rae2822/turb_SA_COMP_EDW_RAE2822.cfg
  TestCases/turbulence_models/sa/rae2822/turb_SA_COMP_RAE2822.cfg
  TestCases/turbulence_models/sa/rae2822/turb_SA_EDW_RAE2822.cfg
  TestCases/turbulence_models/sa/rae2822/turb_SA_NEG_RAE2822.cfg
  TestCases/turbulence_models/sa/rae2822/turb_SA_QCR_RAE2822.cfg
  config_template.cfg
Labels: PR: unreviewed, changelog:feature

#1651 Add V&V case, Mach 5 Shock-Wave Boundary-Layer Interaction
  TestCases/vandv.py
  TestCases/vandv/rans/swbli/config_sa.cfg
  TestCases/vandv/rans/swbli/config_sst.cfg
Labels: PR: unreviewed
