Repository su2code/SU2, pull requests merged in 2022-09, with the labels that each got.

#1749 Small cleanup to remove unused code
  Common/include/basic_types/ad_structure.hpp
  SU2_CFD/src/drivers/CMultizoneDriver.cpp
  SU2_CFD/src/numerics/CNumerics.cpp
  SU2_CFD/src/numerics/NEMO/CNEMONumerics.cpp
  SU2_CFD/src/numerics/NEMO/NEMO_sources.cpp
  SU2_CFD/src/output/output_structure_legacy.cpp
  SU2_CFD/src/solvers/CNEMONSSolver.cpp
  TestCases/species_transport/venturi_primitive_3species/species2_primitiveVenturi_mixingmodel_viscosity.cfg
  legacy/configure.ac
  legacy/preconfigure.py
Labels: PR: unreviewed, changelog:chore

#1753 Fix spelling errors and y+ warning message
  Common/include/containers/CTrapezoidalMap.hpp
  Common/src/containers/CTrapezoidalMap.cpp
  SU2_CFD/include/solvers/CScalarSolver.inl
  SU2_CFD/src/solvers/CAdjTurbSolver.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_CFD/src/solvers/CHeatSolver.cpp
  SU2_CFD/src/solvers/CIncNSSolver.cpp
  SU2_CFD/src/solvers/CNSSolver.cpp
  SU2_CFD/src/solvers/CSpeciesSolver.cpp
  SU2_CFD/src/solvers/CTurbSASolver.cpp
  SU2_CFD/src/solvers/CTurbSolver.cpp
Labels: PR: unreviewed, changelog:chore

#1761 Fix LUT and species clipping
  Common/src/CConfig.cpp
  Common/src/containers/CTrapezoidalMap.cpp
  SU2_CFD/src/fluid/CFluidScalar.cpp
Labels: PR: reviewed-approved, changelog:fix

#1742 FFD box fix for nonplanar faces
  Common/src/grid_movement/CFreeFormDefBox.cpp
Labels: PR: unreviewed, changelog:fix

#1766 develop <- master
  .github/workflows/release-management.yml
Labels: PR: unreviewed, dependencies

#1772 Quick fix to a bug in CFlowOutput.cpp that crashes the FEM-DG solver
  AUTHORS.md
  SU2_CFD/src/output/CFlowCompFEMOutput.cpp
Labels: PR: unreviewed, changelog:fix, PR: partially-approved

#1764 Cleanup/fix regression tests and other small fixes
  SU2_CFD/src/fluid/CFluidScalar.cpp
  TestCases/TestCase.py
  TestCases/hybrid_regression.py
  TestCases/hybrid_regression_AD.py
  TestCases/parallel_regression.py
  TestCases/parallel_regression_AD.py
  TestCases/serial_regression.py
  TestCases/serial_regression_AD.py
  TestCases/tutorials.py
  TestCases/vandv.py
  meson.build
Labels: PR: unreviewed, changelog:fix

#1777 Update arm64 regressions
  TestCases/hybrid_regression.py
  TestCases/incomp_navierstokes/streamwise_periodic/chtPinArray_2d/of_grad_findiff_aarch64.csv.ref
  TestCases/parallel_regression.py
  TestCases/serial_regression.py
  TestCases/tutorials.py
  TestCases/vandv.py
Labels: PR: unreviewed, changelog:none
