Repository su2code/SU2, pull requests merged in 2022-07, with the labels that each got.

#1698 Add Heat Flux values to some regressions
  TestCases/axisymmetric_rans/air_nozzle/air_nozzle.cfg
  TestCases/ddes/flatplate/ddes_flatplate.cfg
  TestCases/hybrid_regression.py
  TestCases/incomp_navierstokes/bend/lam_bend.cfg
  TestCases/incomp_navierstokes/cylinder/incomp_cylinder.cfg
  TestCases/incomp_navierstokes/cylinder/poly_cylinder.cfg
  TestCases/incomp_navierstokes/streamwise_periodic/chtPinArray_3d/configMaster.cfg
  TestCases/incomp_rans/naca0012/naca0012.cfg
  TestCases/navierstokes/cylinder/cylinder_lowmach.cfg
  TestCases/navierstokes/cylinder/lam_cylinder.cfg
  TestCases/navierstokes/poiseuille/lam_poiseuille.cfg
  TestCases/nonequilibrium/axi_visccone/axi_visccone.cfg
  TestCases/parallel_regression.py
  TestCases/parallel_regression_AD.py
  TestCases/radiation/p1model/configp1.cfg
  TestCases/rans/naca0012/turb_NACA0012_sa.cfg
  TestCases/rans/naca0012/turb_NACA0012_sst.cfg
  TestCases/rans/naca0012/turb_NACA0012_sst_2003m.cfg
  TestCases/rans/oneram6/turb_ONERAM6.cfg
  TestCases/rans/rae2822/turb_SA_RAE2822.cfg
  TestCases/rans/rae2822/turb_SST_RAE2822.cfg
  TestCases/serial_regression.py
  TestCases/transition/Schubauer_Klebanoff/transitional_BC_model_ConfigFile.cfg
  TestCases/turbulence_models/sa/rae2822/turb_SA_NEG_RAE2822.cfg
  TestCases/unsteady/square_cylinder/turb_square.cfg
  TestCases/wallfunctions/flatplate/incompressible_SST/turb_SST_flatplate.cfg
Labels: PR: unreviewed, changelog:chore

#1702 Add in Sutherland's law for NEMO problems
  Common/include/option_structure.hpp
  Common/src/CConfig.cpp
  SU2_CFD/include/fluid/CSU2TCLib.hpp
  SU2_CFD/src/fluid/CSU2TCLib.cpp
  SU2_CFD/src/numerics/NEMO/CNEMONumerics.cpp
  SU2_CFD/src/numerics/NEMO/NEMO_diffusion.cpp
  SU2_CFD/src/solvers/CNEMOEulerSolver.cpp
  config_template.cfg
Labels: PR: unreviewed, changelog:feature, PR: partially-approved

#1693 Use latest build-su2-cross Docker image for `release-management` Github Actions workflow
  .github/workflows/release-management.yml
Labels: PR: unreviewed

#1678 Fix #1667 Potential crash for the OpenMP multi-thread running.
  Common/src/linear_algebra/CSysMatrix.cpp
Labels: PR: reviewed-approved, changelog:fix
