Repository su2code/SU2, pull requests merged in 2022-12, with the labels that each got.

#1842 Common function for multigrid interpolation
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/include/variables/CVariable.hpp
  SU2_CFD/src/integration/CMultiGridIntegration.cpp
  SU2_CFD/src/integration/CSingleGridIntegration.cpp
  SU2_CFD/src/solvers/CAdjEulerSolver.cpp
  SU2_CFD/src/solvers/CDiscAdjSolver.cpp
  SU2_CFD/src/solvers/CHeatSolver.cpp
  SU2_CFD/src/solvers/CSpeciesSolver.cpp
  SU2_CFD/src/solvers/CTransLMSolver.cpp
  SU2_CFD/src/solvers/CTurbSolver.cpp
  TestCases/hybrid_regression.py
  TestCases/parallel_regression.py
  TestCases/serial_regression.py
Labels: PR: unreviewed, changelog:chore

#1839 Adding thermodynamics pressure as a user value for FLUID_MIXTURE model
  Common/src/CConfig.cpp
  SU2_CFD/src/solvers/CIncEulerSolver.cpp
  TestCases/parallel_regression.py
  TestCases/species_transport/venturi_primitive_3species/species2_primitiveVenturi_mixingmodel.cfg
  TestCases/species_transport/venturi_primitive_3species/species2_primitiveVenturi_mixingmodel_boundedscalar.cfg
  TestCases/species_transport/venturi_primitive_3species/species2_primitiveVenturi_mixingmodel_heatcapacity_H2.cfg
  TestCases/species_transport/venturi_primitive_3species/species2_primitiveVenturi_mixingmodel_heatcapacity_H2_ND.cfg
  TestCases/species_transport/venturi_primitive_3species/species2_primitiveVenturi_mixingmodel_viscosity.cfg
  config_template.cfg
Labels: PR: reviewed-approved

#1843 Adding inlet markers for turbulent intensity and viscosity ratio for SST Model
  Common/include/CConfig.hpp
  Common/src/CConfig.cpp
  SU2_CFD/src/solvers/CTurbSSTSolver.cpp
  TestCases/parallel_regression.py
  TestCases/species_transport/venturi_primitive_3species/species2_primitiveVenturi_mixingmodel_TURBULENT_MARKERS.cfg
  config_template.cfg
Labels: PR: unreviewed

#1810 Implementation of LM model for SA and cross-flow corrections (LM2015)
  Common/include/CConfig.hpp
  Common/include/option_structure.hpp
  Common/src/CConfig.cpp
  SU2_CFD/include/numerics/CNumerics.hpp
  SU2_CFD/include/numerics/turbulent/transition/trans_correlations.hpp
  SU2_CFD/include/numerics/turbulent/transition/trans_sources.hpp
  SU2_CFD/include/numerics/turbulent/turb_sources.hpp
  SU2_CFD/include/solvers/CTransLMSolver.hpp
  SU2_CFD/include/variables/CTurbSAVariable.hpp
  SU2_CFD/include/variables/CTurbVariable.hpp
  SU2_CFD/include/variables/CVariable.hpp
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_CFD/src/solvers/CSolverFactory.cpp
  SU2_CFD/src/solvers/CTransLMSolver.cpp
  SU2_CFD/src/solvers/CTurbSASolver.cpp
  SU2_CFD/src/solvers/CTurbSSTSolver.cpp
  SU2_CFD/src/variables/CTurbSAVariable.cpp
  SU2_CFD/src/variables/CTurbVariable.cpp
  TestCases/tutorials.py
  config_template.cfg
Labels: PR: unreviewed, changelog:feature

#1850 Add release.yml for when release-drafter has issues
  .github/release.yml
Labels: PR: reviewed-approved

#1852 skip CoolProp for non x86
  meson.build
Labels: PR: unreviewed, changelog:none

#1855 update docker images
  .github/workflows/regression.yml
  .github/workflows/release-management.yml
Labels: PR: unreviewed, changelog:none

#1856 Cleanup Linelets and create output to visualize them
  Common/include/geometry/CGeometry.hpp
  Common/include/linear_algebra/CPreconditioner.hpp
  Common/include/linear_algebra/CSysMatrix.hpp
  Common/include/linear_algebra/CSysMatrix.inl
  Common/include/toolboxes/graph_toolbox.hpp
  Common/src/geometry/CGeometry.cpp
  Common/src/linear_algebra/CSysMatrix.cpp
  SU2_CFD/include/numerics_simd/flow/convection/roe.hpp
  SU2_CFD/include/output/CFVMOutput.hpp
  SU2_CFD/src/output/CFVMOutput.cpp
  SU2_CFD/src/solvers/CAdjEulerSolver.cpp
  SU2_CFD/src/solvers/CAdjNSSolver.cpp
  SU2_CFD/src/solvers/CAdjTurbSolver.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_CFD/src/solvers/CHeatSolver.cpp
  SU2_CFD/src/solvers/CIncEulerSolver.cpp
  SU2_CFD/src/solvers/CNEMOEulerSolver.cpp
  SU2_CFD/src/solvers/CSpeciesSolver.cpp
  SU2_CFD/src/solvers/CTransLMSolver.cpp
  SU2_CFD/src/solvers/CTurbSASolver.cpp
  SU2_CFD/src/solvers/CTurbSSTSolver.cpp
Labels: PR: reviewed-approved, changelog:chore

#1858 Fix windows builds and test turning on OpenBLAS in serial tests
  .github/workflows/regression.yml
  Common/src/geometry/CGeometry.cpp
  TestCases/serial_regression.py
Labels: PR: unreviewed, changelog:none
