Repository su2code/SU2, pull requests merged in 2022-11, with the labels that each got.

#1817 Fix regression branch
  .github/workflows/regression.yml
Labels: PR: reviewed-approved, changelog:none

#1784 Fix axisymmetric divergence for SST production
  .github/workflows/regression.yml
  SU2_CFD/include/numerics/turbulent/turb_sources.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/include/variables/CVariable.hpp
  SU2_CFD/src/solvers/CIncNSSolver.cpp
  SU2_CFD/src/solvers/CNEMONSSolver.cpp
  SU2_CFD/src/solvers/CNSSolver.cpp
  TestCases/axisymmetric_rans/air_nozzle/air_nozzle_restart.cfg
  TestCases/hybrid_regression.py
  TestCases/hybrid_regression_AD.py
  TestCases/incomp_navierstokes/streamwise_periodic/chtPinArray_2d/of_grad_findiff.csv.ref
  TestCases/parallel_regression.py
  TestCases/parallel_regression_AD.py
  TestCases/rans/naca0012/turb_NACA0012_sst_2003m.cfg
  TestCases/serial_regression.py
  TestCases/turbomachinery/APU_turbocharger/Jones.cfg
  TestCases/turbomachinery/APU_turbocharger/Jones_restart.cfg
  TestCases/turbomachinery/APU_turbocharger/Jones_rst.cfg
  TestCases/turbomachinery/APU_turbocharger/rotor_restart.cfg
  TestCases/turbomachinery/transonic_stator_2D/transonic_stator.cfg
  TestCases/turbomachinery/transonic_stator_2D/transonic_stator_restart.cfg
  TestCases/turbomachinery/transonic_stator_2D/transonic_stator_rst.cfg
  TestCases/tutorials.py
  TestCases/vandv.py
  TestCases/vandv/rans/bump_in_channel/turb_bump_sst.cfg
  TestCases/vandv/rans/flatplate/turb_flatplate_sst.cfg
Labels: PR: unreviewed, changelog:fix

#1796 BC inlet for SST solver based on local conditions at the Inlet
  Common/src/CConfig.cpp
  SU2_CFD/include/fluid/CFluidModel.hpp
  SU2_CFD/include/variables/CEulerVariable.hpp
  SU2_CFD/include/variables/CPrimitiveIndices.hpp
  SU2_CFD/src/solvers/CTurbSSTSolver.cpp
  TestCases/hybrid_regression.py
  TestCases/parallel_regression.py
  TestCases/parallel_regression_AD.py
  TestCases/serial_regression.py
  TestCases/tutorials.py
  TestCases/vandv.py
Labels: PR: reviewed-approved, changelog:feature

#1821 Multizone with species transport
  Common/src/CConfig.cpp
  SU2_CFD/include/solvers/CScalarSolver.hpp
  SU2_CFD/include/solvers/CSpeciesSolver.hpp
  SU2_CFD/include/solvers/CTurbSSTSolver.hpp
  SU2_CFD/include/solvers/CTurbSolver.hpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/drivers/CMultizoneDriver.cpp
  SU2_CFD/src/output/CMultizoneOutput.cpp
  SU2_CFD/src/solvers/CSpeciesSolver.cpp
  SU2_CFD/src/solvers/CTurbSolver.cpp
  TestCases/parallel_regression.py
  TestCases/species_transport/multizone/configMaster.cfg
  TestCases/species_transport/multizone/zone1.cfg
  TestCases/species_transport/multizone/zone2.cfg
Labels: PR: unreviewed, changelog:feature

#1831 Fix comment RefElemLength
  Common/src/CConfig.cpp
Labels: PR: reviewed-approved, changelog:chore

#1819 Viscosity and conductivity from CoolProp
  Common/include/option_structure.hpp
  SU2_CFD/include/fluid/CCoolProp.hpp
  SU2_CFD/include/fluid/CCoolPropConductivity.hpp
  SU2_CFD/include/fluid/CCoolPropViscosity.hpp
  SU2_CFD/src/fluid/CCoolProp.cpp
  SU2_CFD/src/fluid/CFluidModel.cpp
  SU2_CFD/src/interfaces/cht/CConjugateHeatInterface.cpp
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_CFD/src/output/output_structure_legacy.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_CFD/src/solvers/CFEM_DG_EulerSolver.cpp
  SU2_CFD/src/solvers/CIncEulerSolver.cpp
  TestCases/nicf/coolprop/fluidModel.cfg
  TestCases/nicf/coolprop/transportModel.cfg
  TestCases/parallel_regression.py
Labels: PR: unreviewed
