Repository su2code/SU2, pull requests merged in 2023-03, with the labels that each got.

#1938 Access solution and primitives via python wrapper
  .github/workflows/regression.yml
  .github/workflows/release-management.yml
  Common/include/containers/CPyWrapperMatrixView.hpp
  Common/src/containers/meson.build
  SU2_CFD/include/drivers/CDriverBase.hpp
  SU2_CFD/include/output/CFlowOutput.hpp
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/include/variables/CEulerVariable.hpp
  SU2_CFD/include/variables/CIncEulerVariable.hpp
  SU2_CFD/include/variables/CMeshVariable.hpp
  SU2_CFD/include/variables/CNEMOEulerVariable.hpp
  SU2_CFD/include/variables/CPrimitiveIndices.hpp
  SU2_CFD/include/variables/CVariable.hpp
  SU2_CFD/src/drivers/CDriverBase.cpp
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_CFD/src/solvers/CAdjEulerSolver.cpp
  SU2_CFD/src/solvers/CDiscAdjFEASolver.cpp
  SU2_CFD/src/solvers/CDiscAdjMeshSolver.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_CFD/src/solvers/CFEASolver.cpp
  SU2_CFD/src/solvers/CFEM_DG_EulerSolver.cpp
  SU2_CFD/src/solvers/CHeatSolver.cpp
  SU2_CFD/src/solvers/CIncEulerSolver.cpp
  SU2_CFD/src/solvers/CMeshSolver.cpp
  SU2_CFD/src/solvers/CNEMOEulerSolver.cpp
  SU2_CFD/src/solvers/CRadP1Solver.cpp
  SU2_CFD/src/solvers/CSpeciesSolver.cpp
  SU2_CFD/src/solvers/CTransLMSolver.cpp
  SU2_CFD/src/solvers/CTurbSASolver.cpp
  SU2_CFD/src/solvers/CTurbSSTSolver.cpp
  SU2_PY/FSI_tools/FSIInterface.py
  SU2_PY/pySU2/pySU2.i
  SU2_PY/pySU2/pySU2ad.i
  TestCases/py_wrapper/deforming_bump_in_channel/run.py
  TestCases/py_wrapper/flatPlate_rigidMotion/launch_flatPlate_rigidMotion.py
  meson.build
Labels: PR: reviewed-approved, changelog:feature

#1949 Access solution and primitives **at markers** via python wrapper
  Common/include/containers/CPyWrapperMatrixView.hpp
  SU2_CFD/include/drivers/CDriver.hpp
  SU2_CFD/include/drivers/CDriverBase.hpp
  SU2_CFD/include/variables/CVariable.hpp
  SU2_CFD/src/drivers/CDriverBase.cpp
  SU2_CFD/src/python_wrapper_structure.cpp
  TestCases/py_wrapper/deforming_bump_in_channel/run.py
  TestCases/py_wrapper/disc_adj_fea/flow_load_sens/run_adjoint.py
  TestCases/py_wrapper/flatPlate_rigidMotion/launch_flatPlate_rigidMotion.py
  TestCases/py_wrapper/flatPlate_unsteady_CHT/launch_unsteady_CHT_FlatPlate.py
Labels: PR: unreviewed, changelog:feature

#1947 Bug fix of CoolProp fluid model
  SU2_CFD/include/fluid/CCoolProp.hpp
  SU2_CFD/src/fluid/CCoolProp.cpp
Labels: PR: unreviewed, changelog:fix

#1956 Adding thermal conductivity, heat capacity and diffusivity as outputs.
  Common/src/CConfig.cpp
  SU2_CFD/include/fluid/CConstantDiffusivity.hpp
  SU2_CFD/include/fluid/CConstantLewisDiffusivity.hpp
  SU2_CFD/include/fluid/CConstantSchmidt.hpp
  SU2_CFD/include/fluid/CDiffusivityModel.hpp
  SU2_CFD/include/fluid/CFluidModel.hpp
  SU2_CFD/include/fluid/CFluidScalar.hpp
  SU2_CFD/include/variables/CScalarVariable.hpp
  SU2_CFD/include/variables/CSpeciesVariable.hpp
  SU2_CFD/include/variables/CVariable.hpp
  SU2_CFD/src/fluid/CFluidScalar.cpp
  SU2_CFD/src/output/CFlowIncOutput.cpp
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_CFD/src/solvers/CSpeciesSolver.cpp
  SU2_CFD/src/variables/CSpeciesVariable.cpp
  TestCases/parallel_regression.py
  TestCases/species_transport/venturi_primitive_3species/species2_primitiveVenturi_mixingmodel_TURBULENT_MARKERS.cfg
  TestCases/tutorials.py
Labels: PR: unreviewed, changelog:feature

#1953 BC inlet for SA solver based on local conditions at the Inlet
  Common/src/CConfig.cpp
  SU2_CFD/src/solvers/CTurbSASolver.cpp
  TestCases/hybrid_regression.py
  TestCases/parallel_regression.py
  TestCases/serial_regression.py
  TestCases/species_transport/venturi_primitive_3species/species2_primitiveVenturi_mixingmodel_viscosity.cfg
  config_template.cfg
Labels: PR: unreviewed, changelog:feature

#1963 Require labels on PRs
  .github/workflows/require-labels.yml
Labels: PR: unreviewed, changelog:chore

#1962 Fix use of possibly unsupported compiler warning options
  externals/tecio/teciosrc/meson.build
Labels: PR: unreviewed, changelog:fix

#1951 Make the use of system-wide Meson and Ninja easier
  .gitignore
  AUTHORS.md
  meson.build
  meson.py
  meson_scripts/init.py
  preconfigure.py
Labels: PR: reviewed-approved, changelog:feature

#1969 Fix condition to set penalty function
  SU2_PY/SU2/eval/design.py
Labels: PR: reviewed-approved, changelog:fix

#1966 Fix SU2 initialization when using the python wrapper
  .github/workflows/regression.yml
  SU2_CFD/src/SU2_CFD.cpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/drivers/CDriverBase.cpp
  SU2_DEF/src/drivers/CDeformationDriver.cpp
  SU2_DEF/src/drivers/CDiscAdjDeformationDriver.cpp
  SU2_DOT/src/SU2_DOT.cpp
  TestCases/hybrid_regression_AD.py
  TestCases/parallel_regression.py
  TestCases/parallel_regression_AD.py
  TestCases/py_wrapper/disc_adj_fea/flow_load_sens/run_adjoint.py
  TestCases/py_wrapper/disc_adj_flow/mesh_disp_sens/run_adjoint.py
  TestCases/serial_regression_AD.py
Labels: PR: unreviewed, changelog:fix

#1961 Remove legacy build system
  .lgtm.yml
  .travis.yml
  Common/lib/Makefile.am
  SU2_CFD/bin/.csv
  SU2_CFD/bin/.gitignore
  SU2_CFD/bin/.vtk
  SU2_CFD/obj/Makefile.am
  SU2_DEF/bin/.gitignore
  SU2_DEF/obj/Makefile.am
  SU2_DOT/bin/.gitignore
  SU2_DOT/obj/Makefile.am
  SU2_GEO/bin/.gitignore
  SU2_GEO/obj/Makefile.am
  SU2_PY/Makefile.am
  SU2_PY/pySU2/Makefile.am
  SU2_SOL/bin/.gitignore
  SU2_SOL/obj/Makefile.am
  externals/Makefile.am
  externals/cgns/Makefile.am
  externals/metis/Makefile.am
  externals/parmetis/Makefile.am
  externals/tecio/Makefile.am
  legacy/Makefile.am
  legacy/bootstrap
  legacy/configure.ac
  legacy/preconfigure.py
  m4/ax_tls.m4
  m4/cgns.m4
  m4/codi.m4
  m4/compiler.m4
  m4/metis.m4
  m4/parmetis.m4
  m4/tecio.m4
Labels: PR: unreviewed, changelog:chore

#1976 Rename python Driver method 'Postprocessing' to 'Finalize'
  .gitignore
  SU2_CFD/include/drivers/CDriver.hpp
  SU2_CFD/include/drivers/CDriverBase.hpp
  SU2_CFD/src/SU2_CFD.cpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/drivers/CDriverBase.cpp
  SU2_DEF/include/drivers/CDeformationDriver.hpp
  SU2_DEF/include/drivers/CDiscAdjDeformationDriver.hpp
  SU2_DEF/src/SU2_DEF.cpp
  SU2_DEF/src/drivers/CDeformationDriver.cpp
  SU2_DEF/src/drivers/CDiscAdjDeformationDriver.cpp
  SU2_DOT/src/SU2_DOT.cpp
  SU2_GEO/src/SU2_GEO.cpp
  SU2_PY/SU2_CFD.py
  SU2_PY/fsi_computation.py
  SU2_SOL/src/SU2_SOL.cpp
  TestCases/py_wrapper/deforming_bump_in_channel/run.py
  TestCases/py_wrapper/disc_adj_fea/flow_load_sens/run_adjoint.py
  TestCases/py_wrapper/disc_adj_flow/mesh_disp_sens/run_adjoint.py
  TestCases/py_wrapper/flatPlate_rigidMotion/launch_flatPlate_rigidMotion.py
Labels: PR: reviewed-approved, changelog:chore

#1977 Change serial runs in parallel regression to parallel
  TestCases/parallel_regression.py
Labels: PR: reviewed-approved, changelog:chore

#1978 Consistent python wrapper function names
  SU2_CFD/include/drivers/CDriver.hpp
  SU2_CFD/include/drivers/CDriverBase.hpp
  SU2_CFD/include/solvers/CHeatSolver.hpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/drivers/CDriverBase.cpp
  SU2_CFD/src/python_wrapper_structure.cpp
  SU2_PY/FSI_tools/FSIInterface.py
  TestCases/py_wrapper/deforming_bump_in_channel/run.py
  TestCases/py_wrapper/disc_adj_fea/flow_load_sens/run_adjoint.py
  TestCases/py_wrapper/disc_adj_flow/mesh_disp_sens/run_adjoint.py
  TestCases/py_wrapper/flatPlate_rigidMotion/launch_flatPlate_rigidMotion.py
  TestCases/py_wrapper/flatPlate_unsteady_CHT/launch_unsteady_CHT_FlatPlate.py
  TestCases/py_wrapper/translating_NACA0012/run_su2.py
Labels: PR: reviewed-approved, changelog:feature

#1985 Fix order of transition volume outputs
  SU2_CFD/include/output/CFlowOutput.hpp
  SU2_CFD/src/output/CFlowCompOutput.cpp
  SU2_CFD/src/output/CFlowIncOutput.cpp
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_CFD/src/output/CNEMOCompOutput.cpp
Labels: PR: reviewed-approved, changelog:fix

#1990 Deprecate CUSP scheme and make it an error to use MUSCL_FLOW=YES with centered schemes
  Common/include/option_structure.hpp
  Common/src/CConfig.cpp
  QuickStart/inv_NACA0012.cfg
  SU2_CFD/include/numerics/flow/convection/cusp.hpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/meson.build
  SU2_CFD/src/numerics/flow/convection/cusp.cpp
  SU2_CFD/src/variables/CFlowVariable.cpp
  TestCases/aeroelastic/aeroelastic_NACA64A010.cfg
  TestCases/cont_adj_euler/naca0012/inv_NACA0012.cfg
  TestCases/cont_adj_euler/naca0012/inv_NACA0012_FD.cfg
  TestCases/cont_adj_euler/naca0012/inv_NACA0012_discadj.cfg
  TestCases/cont_adj_euler/oneram6/inv_ONERAM6.cfg
  TestCases/cont_adj_rans/naca0012/turb_nasa.cfg
  TestCases/cont_adj_rans/naca0012/turb_nasa_binary.cfg
  TestCases/cont_adj_rans/oneram6/turb_ONERAM6.cfg
  TestCases/control_surface/inv_ONERAM6_moving.cfg
  TestCases/control_surface/inv_ONERAM6_setting.cfg
  TestCases/coupled_cht/comp_2d/flow_cylinder.cfg
  TestCases/deformation/naca0012/def_NACA0012.cfg
  TestCases/deformation/naca0012/surface_file_NACA0012.cfg
  TestCases/disc_adj_euler/arina2k/Arina2KRS.cfg
  TestCases/disc_adj_euler/cylinder3D/inv_cylinder3D.cfg
  TestCases/disc_adj_heat/disc_adj_heat.cfg
  TestCases/disc_adj_incomp_euler/naca0012/incomp_NACA0012_disc.cfg
  TestCases/euler/CRM/inv_CRM_JST.cfg
  TestCases/euler/biparabolic/BIPARABOLIC.cfg
  TestCases/euler/channel/inv_channel.cfg
  TestCases/euler/channel/inv_channel_RK.cfg
  TestCases/euler/naca0012/inv_NACA0012.cfg
  TestCases/euler/oneram6/inv_ONERAM6.cfg
  TestCases/fixed_cl/naca0012/inv_NACA0012.cfg
  TestCases/fixed_cl/naca0012/inv_NACA0012_ContAdj.cfg
  TestCases/gust/inv_gust_NACA0012.cfg
  TestCases/harmonic_balance/HB.cfg
  TestCases/harmonic_balance/hb_rans_preconditioning/davis.cfg
  TestCases/nonequilibrium/invwedge/invwedge_lax.cfg
  TestCases/optimization_euler/pitching_naca64a010/pitching_NACA64A010.cfg
  TestCases/optimization_euler/pitching_oneram6/pitching_ONERAM6.cfg
  TestCases/optimization_euler/steady_inverse_design/inv_NACA0012.cfg
  TestCases/optimization_rans/pitching_naca64a010/turb_NACA64A010.cfg
  TestCases/optimization_rans/pitching_oneram6/turb_ONERAM6.cfg
  TestCases/optimization_rans/steady_oneram6/turb_ONERAM6.cfg
  TestCases/polar/naca0012/inv_NACA0012.cfg
  TestCases/py_wrapper/flatPlate_unsteady_CHT/unsteady_CHT_FlatPlate_Conf.cfg
  TestCases/rans/naca0012/turb_NACA0012_sst_multigrid_restart.cfg
  TestCases/rans/rae2822/turb_SA_RAE2822.cfg
  TestCases/rans/rae2822/turb_SST_RAE2822.cfg
  TestCases/rans/rae2822/turb_SST_SUST_RAE2822.cfg
  TestCases/rans/s809/trans_s809.cfg
  TestCases/rotating/caradonna_tung/rot_caradonna_tung.cfg
  TestCases/rotating/naca0012/rot_NACA0012.cfg
  TestCases/sliding_interface/bars_SST_2D/bars.cfg
  TestCases/unsteady/pitching_naca0015_rans_inc/config_incomp_turb_sa.cfg
  TestCases/unsteady/pitching_naca64a010_euler/pitching_NACA64A010.cfg
  TestCases/unsteady/pitching_naca64a010_rans/turb_NACA64A010.cfg
  config_template.cfg
Labels: PR: reviewed-approved, changelog:chore

#1986 Expose all history outputs via the python wrapper
  SU2_CFD/include/drivers/CDriver.hpp
  SU2_CFD/include/drivers/CDriverBase.hpp
  SU2_CFD/include/output/COutput.hpp
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_CFD/src/python_wrapper_structure.cpp
  SU2_DEF/src/drivers/CDeformationDriver.cpp
  TestCases/py_wrapper/deforming_bump_in_channel/run.py
Labels: PR: unreviewed, changelog:feature

#1988 Refactor Driver classes method names
  SU2_CFD/include/drivers/CDiscAdjMultizoneDriver.hpp
  SU2_CFD/include/drivers/CDiscAdjSinglezoneDriver.hpp
  SU2_CFD/include/drivers/CDriver.hpp
  SU2_CFD/include/drivers/CDriverBase.hpp
  SU2_CFD/include/drivers/CMultizoneDriver.hpp
  SU2_CFD/include/drivers/CSinglezoneDriver.hpp
  SU2_CFD/src/drivers/CDiscAdjMultizoneDriver.cpp
  SU2_CFD/src/drivers/CDiscAdjSinglezoneDriver.cpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/drivers/CDriverBase.cpp
  SU2_CFD/src/drivers/CMultizoneDriver.cpp
  SU2_CFD/src/drivers/CSinglezoneDriver.cpp
  SU2_CFD/src/python_wrapper_structure.cpp
  SU2_DEF/include/drivers/CDeformationDriver.hpp
  SU2_DEF/src/drivers/CDeformationDriver.cpp
  SU2_DEF/src/drivers/CDiscAdjDeformationDriver.cpp
Labels: PR: unreviewed, changelog:chore
