Repository su2code/SU2, pull requests merged in 2023-05, with the labels that each got.

#2020 Add simple custom outputs (functions of other outputs) to all solvers
  Common/include/CConfig.hpp
  SU2_CFD/include/output/CFlowOutput.hpp
  SU2_CFD/include/output/COutput.hpp
  SU2_CFD/src/output/CAdjElasticityOutput.cpp
  SU2_CFD/src/output/CAdjFlowCompOutput.cpp
  SU2_CFD/src/output/CAdjFlowIncOutput.cpp
  SU2_CFD/src/output/CAdjFlowOutput.cpp
  SU2_CFD/src/output/CAdjHeatOutput.cpp
  SU2_CFD/src/output/CElasticityOutput.cpp
  SU2_CFD/src/output/CFlowCompFEMOutput.cpp
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_CFD/src/output/CHeatOutput.cpp
  SU2_CFD/src/output/COutput.cpp
  TestCases/disc_adj_fsi/Airfoil_2d/config.cfg
  TestCases/disc_adj_fsi/Airfoil_2d/configFEA.cfg
  TestCases/parallel_regression_AD.py
  TestCases/species_transport/venturi_primitive_3species/DAspecies3_primitiveVenturi.cfg
  TestCases/species_transport/venturi_primitive_3species/species3_primitiveVenturi.cfg
  TestCases/tutorials.py
Labels: PR: unreviewed, changelog:feature

#2017 Python wrapper heat solver example + disc adj minor fixes and cleanup
  SU2_CFD/include/drivers/CDriverBase.hpp
  SU2_CFD/include/variables/CVariable.hpp
  SU2_CFD/src/drivers/CDiscAdjSinglezoneDriver.cpp
  SU2_CFD/src/drivers/CSinglezoneDriver.cpp
  SU2_CFD/src/iteration/CDiscAdjFluidIteration.cpp
  SU2_CFD/src/iteration/CDiscAdjHeatIteration.cpp
  SU2_CFD/src/output/CAdjElasticityOutput.cpp
  SU2_CFD/src/output/CAdjHeatOutput.cpp
  TestCases/parallel_regression_AD.py
  TestCases/py_wrapper/custom_heat_flux/run_ad.py
  TestCases/py_wrapper/custom_load_fea/run_ad.py
Labels: PR: unreviewed, changelog:chore

#2021 CoolProp enhancement
  SU2_CFD/include/fluid/CCoolProp.hpp
  SU2_CFD/src/fluid/CCoolProp.cpp
Labels: PR: reviewed-approved, changelog:fix

#2031 Add word-by-word comparison with tolerance and threshold to file diff.
  TestCases/TestCase.py
Labels: PR: unreviewed, changelog:feature

#2032 More helpful messages for FFD setting
  Common/include/geometry/CGeometry.hpp
  Common/include/grid_movement/CFreeFormDefBox.hpp
  Common/include/toolboxes/geometry_toolbox.hpp
  Common/src/geometry/CGeometry.cpp
  Common/src/grid_movement/CFreeFormDefBox.cpp
  Common/src/grid_movement/CSurfaceMovement.cpp
  TestCases/deformation/cylindrical_ffd/def_cylindrical.cfg
  TestCases/py_wrapper/custom_heat_flux/run_ad.py
  TestCases/py_wrapper/custom_load_fea/run_ad.py
Labels: changelog:feature

#2024 Python interface for updating translation and rotation rates of the moving frame
  Common/include/CConfig.hpp
  SU2_CFD/include/drivers/CDriver.hpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/iteration/CIteration.cpp
  SU2_CFD/src/python_wrapper_structure.cpp
  TestCases/hybrid_regression.py
  TestCases/py_wrapper/updated_moving_frame_NACA12/config.cfg
  TestCases/py_wrapper/updated_moving_frame_NACA12/forces_0.csv.ref
  TestCases/py_wrapper/updated_moving_frame_NACA12/run_su2.py
Labels: PR: unreviewed, changelog:feature

#2036 Fix functionality of 'WRT_*_OVERWRITE' flags.
  SU2_CFD/src/output/COutput.cpp
Labels: PR: unreviewed, changelog:fix
