Repository su2code/SU2, pull requests merged in 2023-12, with the labels that each got.

#2179 Upgrade external CGNS library to 4.4 release.
  externals/cgns/adf/ADF_interface.c
  externals/cgns/adf/ADF_internals.c
  externals/cgns/adfh/ADFH.c
  externals/cgns/adfh/ADFH.h
  externals/cgns/cg_hashmap.c
  externals/cgns/cgns_error.c
  externals/cgns/cgns_header.h
  externals/cgns/cgns_internals.c
  externals/cgns/cgns_io.h
  externals/cgns/cgnslib.c
  externals/cgns/cgnslib.h
  externals/cgns/pcgnslib.c
  externals/cgns/pcgnslib.h
Labels: changelog:chore, dependencies

#2178 Fix error in CGNS writing
  SU2_CFD/src/output/filewriter/CCGNSFileWriter.cpp
  TestCases/cgns_writer/config.cfg
  TestCases/parallel_regression.py
Labels: changelog:fix

#2167 Adaptive Edge Color Group Size
  Common/include/CConfig.hpp
  Common/include/geometry/CGeometry.hpp
  Common/include/toolboxes/graph_toolbox.hpp
  Common/src/CConfig.cpp
  Common/src/geometry/CGeometry.cpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/include/solvers/CScalarSolver.inl
  TestCases/hybrid_regression_AD.py
  config_template.cfg
Labels: changelog:feature
