Repository su2code/SU2, pull requests merged in 2023-07, with the labels that each got.

#2062 Make SST-1994m consistent with literature and use 2003m by default
  Common/include/option_structure.hpp
  SU2_CFD/include/numerics/turbulent/turb_sources.hpp
  SU2_CFD/src/solvers/CAdjNSSolver.cpp
  TestCases/axisymmetric_rans/air_nozzle/air_nozzle_restart.cfg
  TestCases/disc_adj_incomp_rans/naca0012/turb_naca0012_sst.cfg
  TestCases/disc_adj_turbomachinery/transonic_stator_2D/transonic_stator.cfg
  TestCases/hybrid_regression.py
  TestCases/hybrid_regression_AD.py
  TestCases/incomp_navierstokes/streamwise_periodic/chtPinArray_2d/of_grad_findiff.csv.ref
  TestCases/parallel_regression.py
  TestCases/parallel_regression_AD.py
  TestCases/rans/naca0012/turb_NACA0012_sst.cfg
  TestCases/serial_regression.py
  TestCases/serial_regression_AD.py
  TestCases/tutorials.py
  TestCases/vandv.py
  TestCases/vandv/rans/bump_in_channel/turb_bump_sst.cfg
  TestCases/vandv/rans/flatplate/turb_flatplate_sst.cfg
Labels: changelog:fix

#2067 Bug fix cht flamelet solver
  Common/src/CConfig.cpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/interfaces/cht/CConjugateHeatInterface.cpp
  SU2_CFD/src/solvers/CSpeciesFlameletSolver.cpp
Labels: changelog:fix

#2072 chmod +x SU2_PY/fsi_computation.py
  SU2_PY/fsi_computation.py
Labels: changelog:none

#2073 Update arm64 regressions
  TestCases/disc_adj_fsi/dyn_fsi/grad_dv_aarch64.opt.ref
  TestCases/hybrid_regression.py
  TestCases/hybrid_regression_AD.py
  TestCases/parallel_regression.py
  TestCases/parallel_regression_AD.py
  TestCases/serial_regression.py
  TestCases/serial_regression_AD.py
  TestCases/tutorials.py
  TestCases/vandv.py
Labels: changelog:none

#2076 More arm64 updates and fix a race condition in a test
  TestCases/hybrid_regression_AD.py
  TestCases/parallel_regression.py
  TestCases/py_wrapper/wavy_wall/run_steady.py
  TestCases/serial_regression.py
Labels: changelog:none

#2066 update QuickStart example
  QuickStart/.gitignore
  QuickStart/inv_NACA0012.cfg
Labels: changelog:chore

#2081 Remove unimplemented TWIST_2D
  Common/include/grid_movement/CSurfaceMovement.hpp
  Common/include/option_structure.hpp
  Common/include/option_structure.inl
  Common/src/CConfig.cpp
  Common/src/grid_movement/CSurfaceMovement.cpp
  QuickStart/inv_NACA0012.cfg
  SU2_DEF/src/drivers/CDiscAdjDeformationDriver.cpp
  SU2_GEO/src/SU2_GEO.cpp
  SU2_PY/SU2/io/config.py
  SU2_PY/SU2/io/config_options.py
  SU2_PY/SU2/io/tools.py
  config_template.cfg
Labels: changelog:fix

#2084 Minor revision of the header file path
  SU2_GEO/include/SU2_GEO.hpp
Labels: changelog:fix

#2068 Thread sanitizer tests in the CI pipeline
  .github/workflows/regression.yml
  .github/workflows/release-management.yml
  Common/src/geometry/CPhysicalGeometry.cpp
  TestCases/TestCase.py
  TestCases/hybrid_regression.py
  TestCases/hybrid_regression_AD.py
  su2omp.syntax.json
Labels: changelog:feature

#2083 Fix wall time for discrete adjoint MZ driver + OpenMP the GMRES orthogonalization when used by MZ driver
  Common/include/linear_algebra/CSysSolve.hpp
  Common/include/linear_algebra/vector_expressions.hpp
  Common/src/linear_algebra/CSysSolve.cpp
  SU2_CFD/src/drivers/CDiscAdjMultizoneDriver.cpp
Labels: changelog:fix

#2093 Fix meson issues
  meson.build
Labels: changelog:fix

#2078 Custom Python wrapper marker BC values appropriately nondimensionalized
  SU2_CFD/src/solvers/CHeatSolver.cpp
  SU2_CFD/src/solvers/CNSSolver.cpp
Labels: changelog:fix

#2096 Add python custom temperature and heat flux to incompressible solver
  SU2_CFD/src/interfaces/cht/CConjugateHeatInterface.cpp
  SU2_CFD/src/solvers/CIncNSSolver.cpp
  TestCases/py_wrapper/custom_heat_flux/run_ad.py
Labels: changelog:feature
