Repository su2code/SU2, pull requests merged in 2023-01, with the labels that each got.

#1876 Fix #1873
  Common/include/geometry/CGeometry.hpp
  Common/src/geometry/CGeometry.cpp
Labels: PR: unreviewed, changelog:none

#1878 Cleanup uses of SetGlobalParam
  Common/src/CConfig.cpp
  SU2_CFD/src/iteration/CAdjFluidIteration.cpp
  SU2_CFD/src/iteration/CFEMFluidIteration.cpp
  SU2_CFD/src/iteration/CFluidIteration.cpp
  SU2_CFD/src/solvers/CSpeciesSolver.cpp
  SU2_CFD/src/solvers/CTransLMSolver.cpp
Labels: PR: unreviewed, changelog:chore

#1854 [Feature / Option] Vorticity Confinement (VC) technique to reduce numerical diffusion
  AUTHORS.md
  Common/include/CConfig.hpp
  Common/src/CConfig.cpp
  Common/src/geometry/CMultiGridGeometry.cpp
  SU2_CFD/include/numerics/CNumerics.hpp
  SU2_CFD/include/numerics/flow/flow_sources.hpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/numerics/flow/flow_sources.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_CFD/src/variables/CEulerVariable.cpp
  TestCases/parallel_regression.py
  TestCases/rans/oneram6/turb_ONERAM6_vc.cfg
  config_template.cfg
Labels: PR: reviewed-approved, changelog:feature

#1844 Heat solver using scalar framework - Part 1
  Common/include/option_structure.hpp
  SU2_CFD/include/numerics/CNumerics.hpp
  SU2_CFD/include/numerics/heat.hpp
  SU2_CFD/include/numerics/scalar/scalar_diffusion.hpp
  SU2_CFD/include/numerics/turbulent/transition/trans_diffusion.hpp
  SU2_CFD/include/numerics/turbulent/turb_diffusion.hpp
  SU2_CFD/include/solvers/CHeatSolver.hpp
  SU2_CFD/include/solvers/CRadP1Solver.hpp
  SU2_CFD/include/solvers/CScalarSolver.hpp
  SU2_CFD/include/solvers/CScalarSolver.inl
  SU2_CFD/include/variables/CHeatVariable.hpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/numerics/heat.cpp
  SU2_CFD/src/solvers/CHeatSolver.cpp
  SU2_CFD/src/variables/CHeatVariable.cpp
  TestCases/incomp_navierstokes/streamwise_periodic/chtPinArray_2d/of_grad_findiff.csv.ref
  TestCases/parallel_regression.py
  TestCases/parallel_regression_AD.py
  TestCases/serial_regression_AD.py
Labels: PR: reviewed-approved, changelog:chore

#1862 Fix NEMO Supersonic Inlet BC & BC Cleanup
  Common/include/CConfig.hpp
  Common/src/CConfig.cpp
  SU2_CFD/src/solvers/CNEMOEulerSolver.cpp
  TestCases/nonequilibrium/invwedge/invwedge_ss_inlet.cfg
  TestCases/parallel_regression.py
  config_template.cfg
Labels: PR: unreviewed, changelog:fix, PR: partially-approved

#1846 OptimalPropeller function cleanup
  AUTHORS.md
  SU2_PY/OptimalPropeller.py
Labels: PR: unreviewed, changelog:chore, PR: partially-approved

#1847 CVE-2007-4559 Patch
  meson_scripts/extract_file.py
Labels: bug, PR: unreviewed, PR: reviewed-approved, changelog:fix

#1889 Adding thermal conductivities to NEMO output
  SU2_CFD/src/output/CNEMOCompOutput.cpp
Labels: enhancement, PR: unreviewed, PR: reviewed-approved

#1885 Add regressions for all convective numerical schemes for NEMO
  SU2_CFD/src/output/output_structure_legacy.cpp
  TestCases/nicf/coolprop/fluidModel.cfg
  TestCases/nicf/coolprop/transportModel.cfg
  TestCases/nonequilibrium/invwedge/invwedge_ausm.cfg
  TestCases/nonequilibrium/invwedge/invwedge_ausmplusup2.cfg
  TestCases/nonequilibrium/invwedge/invwedge_lax.cfg
  TestCases/nonequilibrium/invwedge/invwedge_msw.cfg
  TestCases/nonequilibrium/invwedge/invwedge_roe.cfg
  TestCases/parallel_regression.py
  TestCases/serial_regression.py
  legacy/configure.ac
  legacy/preconfigure.py
Labels: PR: unreviewed, changelog:chore

#1897 Wrap MPI_Allgatherv for NdFlattener
  Common/include/parallelization/mpi_structure.cpp
  Common/include/parallelization/mpi_structure.hpp
  Common/include/toolboxes/ndflattener.hpp
Labels: PR: unreviewed, changelog:chore

#1898 Add turbulent bend to regression tests
  TestCases/tutorials.py
Labels: PR: unreviewed, changelog:chore

#1900 Remove git extension in coolprop download link
  meson_scripts/init.py
Labels: changelog:chore
