Repository su2code/SU2, pull requests merged in 2023-04, with the labels that each got.

#1996 Reduce public interface of drivers
  SU2_CFD/include/drivers/CDiscAdjMultizoneDriver.hpp
  SU2_CFD/include/drivers/CDiscAdjSinglezoneDriver.hpp
  SU2_CFD/include/drivers/CDriver.hpp
  SU2_CFD/include/drivers/CDriverBase.hpp
  SU2_CFD/include/drivers/CMultizoneDriver.hpp
  SU2_CFD/include/drivers/CSinglezoneDriver.hpp
  SU2_CFD/include/integration/CIntegration.hpp
  SU2_CFD/include/iteration/CDiscAdjFluidIteration.hpp
  SU2_CFD/include/iteration/CDiscAdjHeatIteration.hpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/drivers/CMultizoneDriver.cpp
  SU2_CFD/src/drivers/CSinglezoneDriver.cpp
  SU2_CFD/src/integration/CIntegration.cpp
  SU2_CFD/src/integration/CMultiGridIntegration.cpp
  SU2_CFD/src/iteration/CAdjFluidIteration.cpp
  SU2_CFD/src/iteration/CDiscAdjFluidIteration.cpp
  SU2_CFD/src/iteration/CDiscAdjHeatIteration.cpp
  SU2_CFD/src/iteration/CFEAIteration.cpp
  SU2_CFD/src/iteration/CFluidIteration.cpp
  SU2_CFD/src/iteration/CHeatIteration.cpp
  SU2_CFD/src/python_wrapper_structure.cpp
  SU2_DEF/include/drivers/CDeformationDriver.hpp
  SU2_DEF/include/drivers/CDiscAdjDeformationDriver.hpp
  SU2_DEF/src/SU2_DEF.cpp
  SU2_DEF/src/drivers/CDeformationDriver.cpp
  SU2_PY/FSI_tools/FSIInterface.py
Labels: PR: unreviewed, changelog:chore

#1999 Fix writing of multiple inlet profiles when using MPI
  Common/include/option_structure.hpp
  SU2_CFD/include/CMarkerProfileReaderFVM.hpp
  SU2_CFD/src/CMarkerProfileReaderFVM.cpp
Labels: bug, PR: unreviewed, PR: reviewed-approved, changelog:fix

#2006 Nishikawa Rp limiters (AIAA 2022-1473)
  Common/include/option_structure.hpp
  Common/src/CConfig.cpp
  SU2_CFD/include/limiters/CLimiterDetails.hpp
  SU2_CFD/include/limiters/computeLimiters.hpp
  TestCases/euler/ramp/inv_ramp.cfg
  TestCases/parallel_regression.py
  config_template.cfg
Labels: PR: unreviewed, changelog:feature

#2003 Remove the legacy output classes
  Common/include/CConfig.hpp
  Common/include/option_structure.hpp
  Common/src/CConfig.cpp
  SU2_CFD/include/drivers/CDiscAdjSinglezoneDriver.hpp
  SU2_CFD/include/drivers/CDriver.hpp
  SU2_CFD/include/drivers/CMultizoneDriver.hpp
  SU2_CFD/include/output/COutputFactory.hpp
  SU2_CFD/include/output/COutputLegacy.hpp
  SU2_CFD/src/SU2_CFD.cpp
  SU2_CFD/src/drivers/CDiscAdjMultizoneDriver.cpp
  SU2_CFD/src/drivers/CDiscAdjSinglezoneDriver.cpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/drivers/CMultizoneDriver.cpp
  SU2_CFD/src/drivers/CSinglezoneDriver.cpp
  SU2_CFD/src/iteration/CDiscAdjFluidIteration.cpp
  SU2_CFD/src/iteration/CFEAIteration.cpp
  SU2_CFD/src/iteration/CFluidIteration.cpp
  SU2_CFD/src/meson.build
  SU2_CFD/src/output/COutputFactory.cpp
  SU2_CFD/src/output/output_physics.cpp
  SU2_CFD/src/output/output_structure_legacy.cpp
  TestCases/disc_adj_turbomachinery/transonic_stator_2D/transonic_stator.cfg
  TestCases/harmonic_balance/HB.cfg
  TestCases/harmonic_balance/hb_rans_preconditioning/davis.cfg
  TestCases/hybrid_regression.py
  TestCases/hybrid_regression_AD.py
  TestCases/parallel_regression.py
  TestCases/parallel_regression_AD.py
  TestCases/serial_regression.py
  TestCases/turbomachinery/APU_turbocharger/Jones_restart.cfg
  TestCases/turbomachinery/axial_stage_2D/Axial_stage2D.cfg
  TestCases/turbomachinery/transonic_stator_2D/transonic_stator_restart.cfg
  TestCases/tutorials.py
Labels: PR: unreviewed, changelog:chore

#2008 Unify Flow and FEA unsteady options + fix unsteady FEA adjoints + add FEA python wrapper examples
  Common/include/CConfig.hpp
  Common/include/geometry/elements/CElementProperty.hpp
  Common/include/option_structure.hpp
  Common/src/CConfig.cpp
  SU2_CFD/include/drivers/CDriverBase.hpp
  SU2_CFD/include/solvers/CDiscAdjFEASolver.hpp
  SU2_CFD/include/solvers/CFEASolver.hpp
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/include/variables/CDiscAdjVariable.hpp
  SU2_CFD/include/variables/CFEABoundVariable.hpp
  SU2_CFD/include/variables/CVariable.hpp
  SU2_CFD/src/drivers/CDiscAdjMultizoneDriver.cpp
  SU2_CFD/src/drivers/CDiscAdjSinglezoneDriver.cpp
  SU2_CFD/src/integration/CStructuralIntegration.cpp
  SU2_CFD/src/interfaces/fsi/CFlowTractionInterface.cpp
  SU2_CFD/src/iteration/CDiscAdjFEAIteration.cpp
  SU2_CFD/src/iteration/CFEAIteration.cpp
  SU2_CFD/src/numerics/elasticity/CFEAElasticity.cpp
  SU2_CFD/src/output/CAdjElasticityOutput.cpp
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_CFD/src/solvers/CDiscAdjFEASolver.cpp
  SU2_CFD/src/solvers/CDiscAdjSolver.cpp
  SU2_CFD/src/solvers/CFEASolver.cpp
  SU2_CFD/src/variables/CFEABoundVariable.cpp
  SU2_PY/SU2/io/historyMap.py
  TestCases/disc_adj_fsi/Airfoil_2d/config.cfg
  TestCases/disc_adj_fsi/config.cfg
  TestCases/disc_adj_fsi/dyn_fsi/grad_dv.opt.ref
  TestCases/fea_fsi/DynBeam_2d/configBeam_2d.cfg
  TestCases/fea_fsi/MixElemsKnowles/config.cfg
  TestCases/fea_fsi/SquareCyl_Beam/config.cfg
  TestCases/fea_fsi/StatBeam_3d/configBeam_3d.cfg
  TestCases/fea_fsi/stat_fsi/configFEA.cfg
  TestCases/fea_topology/config.cfg
  TestCases/fea_topology/quick_start/settings.cfg
  TestCases/fea_topology/quick_start/settings_compliance.cfg
  TestCases/fea_topology/quick_start/settings_volfrac.cfg
  TestCases/parallel_regression.py
  TestCases/parallel_regression_AD.py
  TestCases/py_wrapper/custom_load_fea/config.cfg
  TestCases/py_wrapper/custom_load_fea/run.py
  TestCases/py_wrapper/custom_load_fea/run_ad.py
  config_template.cfg
Labels: PR: unreviewed, changelog:fix
