Repository su2code/SU2, pull requests merged in 2023-02, with the labels that each got.

#1773 Introduction of AUSM+M and AUSM scheme refactoring in NEMO
  .github/stale.yml
  .github/workflows/release-management.yml
  Common/include/CConfig.hpp
  Common/include/option_structure.hpp
  Common/src/CConfig.cpp
  SU2_CFD/include/numerics/NEMO/CNEMONumerics.hpp
  SU2_CFD/include/numerics/NEMO/convection/ausm.hpp
  SU2_CFD/include/numerics/NEMO/convection/ausm_slau.hpp
  SU2_CFD/include/numerics/NEMO/convection/ausmplusup2.hpp
  SU2_CFD/include/numerics/NEMO/convection/ausmpwplus.hpp
  SU2_CFD/include/solvers/CNEMOEulerSolver.hpp
  SU2_CFD/obj/Makefile.am
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/meson.build
  SU2_CFD/src/numerics/NEMO/convection/ausm.cpp
  SU2_CFD/src/numerics/NEMO/convection/ausm_slau.cpp
  SU2_CFD/src/numerics/NEMO/convection/ausmplusup2.cpp
  SU2_CFD/src/numerics/NEMO/convection/ausmpwplus.cpp
  SU2_CFD/src/numerics/NEMO/convection/lax.cpp
  SU2_CFD/src/numerics/NEMO/convection/msw.cpp
  SU2_CFD/src/solvers/CNEMOEulerSolver.cpp
  TestCases/nonequilibrium/invwedge/invwedge_am.cfg
  TestCases/parallel_regression.py
  TestCases/serial_regression.py
  config_template.cfg
Labels: PR: unreviewed, changelog:feature, PR: partially-approved

#1909 Point probes
  SU2_CFD/include/output/COutput.hpp
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_CFD/src/output/COutput.cpp
  TestCases/parallel_regression.py
  TestCases/user_defined_functions/lam_flatplate.cfg
Labels: PR: unreviewed, changelog:feature

#1918 Address NEMO compile warnings
  Docs/docmain.hpp
  SU2_CFD/include/numerics/NEMO/NEMO_diffusion.hpp
  SU2_CFD/src/numerics/NEMO/NEMO_diffusion.cpp
  TestCases/nicf/coolprop/fluidModel.cfg
  TestCases/nicf/coolprop/transportModel.cfg
  legacy/configure.ac
  legacy/preconfigure.py
Labels: PR: reviewed-approved

#1920 Write Z-Velocity and temperature only when solved
  SU2_CFD/src/output/CAdjFlowCompOutput.cpp
  SU2_CFD/src/output/CAdjFlowIncOutput.cpp
  TestCases/parallel_regression_AD.py
  TestCases/serial_regression_AD.py
Labels: PR: unreviewed, changelog:chore

#1300 Refactorization of SU2 Grid Deformation for Python
  Common/include/geometry/primal_grid/CPrimalGrid.hpp
  Common/include/grid_movement/CSurfaceMovement.hpp
  Common/src/grid_movement/CSurfaceMovement.cpp
  SU2_CFD/include/drivers/CDriver.hpp
  SU2_CFD/include/drivers/CDriverBase.hpp
  SU2_CFD/include/solvers/CMeshSolver.hpp
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/drivers/CDriverBase.cpp
  SU2_CFD/src/iteration/CIteration.cpp
  SU2_CFD/src/meson.build
  SU2_CFD/src/python_wrapper_structure.cpp
  SU2_CFD/src/solvers/CMeshSolver.cpp
  SU2_DEF/include/SU2_DEF.hpp
  SU2_DEF/include/drivers/CDeformationDriver.hpp
  SU2_DEF/include/drivers/CDiscAdjDeformationDriver.hpp
  SU2_DEF/src/SU2_DEF.cpp
  SU2_DEF/src/drivers/CDeformationDriver.cpp
  SU2_DEF/src/drivers/CDiscAdjDeformationDriver.cpp
  SU2_DEF/src/meson.build
  SU2_DOT/include/SU2_DOT.hpp
  SU2_DOT/src/SU2_DOT.cpp
  SU2_DOT/src/meson.build
  SU2_PY/FSI_tools/FSIInterface.py
  SU2_PY/pySU2/Makefile.am
  SU2_PY/pySU2/meson.build
  SU2_PY/pySU2/pySU2.i
  SU2_PY/pySU2/pySU2ad.i
  TestCases/py_wrapper/disc_adj_fea/flow_load_sens/run_adjoint.py
  TestCases/py_wrapper/disc_adj_flow/mesh_disp_sens/run_adjoint.py
  TestCases/py_wrapper/flatPlate_rigidMotion/launch_flatPlate_rigidMotion.py
  TestCases/py_wrapper/flatPlate_unsteady_CHT/launch_unsteady_CHT_FlatPlate.py
  TestCases/py_wrapper/translating_NACA0012/run_su2.py
  meson.build
Labels: PR: unreviewed

#1922 Doxygen module for python wrapper functions and fixed memory errors
  Docs/docmain.hpp
  SU2_CFD/include/drivers/CDriver.hpp
  SU2_CFD/include/drivers/CDriverBase.hpp
  SU2_CFD/src/drivers/CDriverBase.cpp
  SU2_DEF/include/SU2_DEF.hpp
  SU2_DEF/include/drivers/CDeformationDriver.hpp
  SU2_DEF/include/drivers/CDiscAdjDeformationDriver.hpp
  SU2_DEF/obj/Makefile.am
  SU2_DEF/src/SU2_DEF.cpp
  SU2_DEF/src/drivers/CDeformationDriver.cpp
  SU2_DEF/src/drivers/CDiscAdjDeformationDriver.cpp
  SU2_DOT/include/SU2_DOT.hpp
  SU2_DOT/obj/Makefile.am
  SU2_DOT/src/SU2_DOT.cpp
  TestCases/incomp_navierstokes/streamwise_periodic/chtPinArray_2d/configMaster.cfg
Labels: PR: reviewed-approved, changelog:chore

#1930 Align Paraview multiblock filename with other volume output file names.
  SU2_CFD/src/output/COutput.cpp
Labels: PR: unreviewed, changelog:fix, PR: partially-approved

#1933 Fix Symmetry/Euler marker preprocessing logic with deforming markers
  Common/include/CConfig.hpp
  Common/src/CConfig.cpp
  Common/src/geometry/CGeometry.cpp
  TestCases/parallel_regression.py
  TestCases/py_wrapper/deforming_bump_in_channel/config.cfg
  TestCases/py_wrapper/deforming_bump_in_channel/run.py
Labels: PR: unreviewed, changelog:fix

#1887 Adding ionization capabilities for viscous simulations (NEMO)
  Common/include/option_structure.hpp
  Common/src/CConfig.cpp
  SU2_CFD/include/fluid/CSU2TCLib.hpp
  SU2_CFD/src/fluid/CMutationTCLib.cpp
  SU2_CFD/src/fluid/CSU2TCLib.cpp
  SU2_CFD/src/numerics/NEMO/CNEMONumerics.cpp
  TestCases/nonequilibrium/visc_cylinder/cyl_ion_gy.cfg
  TestCases/nonequilibrium/visc_wedge/axi_visccone.cfg
  TestCases/nonequilibrium/visc_wedge/partial_cat.cfg
  TestCases/nonequilibrium/visc_wedge/super_cat.cfg
  TestCases/parallel_regression.py
  TestCases/serial_regression.py
Labels: PR: unreviewed, changelog:feature, PR: partially-approved
