Repository su2code/SU2, pull requests merged in 2023-11, with the labels that each got.

#2161 Further Explicit Adjoints Locking and Lock-Free Adjoints Access
  Common/include/basic_types/ad_structure.hpp
  SU2_CFD/include/variables/CVariable.hpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/solvers/CDiscAdjFEASolver.cpp
  SU2_CFD/src/solvers/CDiscAdjSolver.cpp
  TestCases/hybrid_regression_AD.py
  TestCases/serial_regression.py
Labels: changelog:chore

#2142 Feature actuatordisk bem
  Common/include/CConfig.hpp
  Common/include/option_structure.hpp
  Common/src/CConfig.cpp
  SU2_CFD/include/solvers/CEulerSolver.hpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  TestCases/parallel_regression.py
  TestCases/rans/actuatordisk_bem/actuatordisk_bem.cfg
  TestCases/rans/actuatordisk_bem/prop_geom_alfclcd_data.txt
  TestCases/rans/actuatordisk_bem/readme.txt
  config_template.cfg
Labels: changelog:feature

#2155 Chore cleanup turbo functions
  SU2_CFD/src/solvers/CEulerSolver.cpp
Labels: changelog:chore

#1934 Update config_template.cfg
  Common/include/CConfig.hpp
  Common/include/grid_movement/CSurfaceMovement.hpp
  Common/include/option_structure.inl
  Common/src/CConfig.cpp
  SU2_DEF/include/drivers/CDiscAdjDeformationDriver.hpp
  TestCases/hybrid_regression_AD.py
  config_template.cfg
Labels: changelog:chore

#2163 Fix cpu arch returned value in TestCase.py
  TestCases/TestCase.py
Labels: changelog:fix

#2171 Remove `'U'` mode from Python `open()` function
  TestCases/TestCase.py
Labels: changelog:chore
