Repository su2code/SU2, pull requests merged in 2023-06, with the labels that each got.

#2047 Small fixes for time average outputs
  SU2_CFD/include/output/COutput.hpp
  SU2_CFD/src/output/CFlowCompOutput.cpp
  SU2_CFD/src/output/CFlowIncOutput.cpp
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_CFD/src/output/CNEMOCompOutput.cpp
  SU2_CFD/src/output/COutput.cpp
Labels: changelog:fix

#1954 Implementing the gust encounter for 3D meshes and for free-flying, elastic aircraft
  Common/include/option_structure.hpp
  SU2_CFD/src/iteration/CFluidIteration.cpp
  SU2_CFD/src/numerics/flow/flow_sources.cpp
  TestCases/gust/cosine_gust_zdir.cfg
  TestCases/gust/gust_with_mesh_deformation.cfg
  TestCases/hybrid_regression.py
  config_template.cfg
Labels: PR: unreviewed, changelog:feature

#2014 Corrections to SA-NEG-R and SA model
  SU2_CFD/include/numerics/turbulent/turb_sources.hpp
  SU2_CFD/src/solvers/CTurbSASolver.cpp
  TestCases/hybrid_regression.py
  TestCases/hybrid_regression_AD.py
  TestCases/parallel_regression.py
  TestCases/parallel_regression_AD.py
  TestCases/rans/naca0012/turb_NACA0012_sa.cfg
  TestCases/serial_regression.py
  TestCases/serial_regression_AD.py
  TestCases/tutorials.py
  TestCases/vandv.py
Labels: changelog:fix

#2060 Add local timestep + CFL as volume output
  AUTHORS.md
  SU2_CFD/src/output/CFlowOutput.cpp
Labels: changelog:feature

#2059 Add new example for adjoint fluid flow with custom mesh deformation, fix CGNS issue with compiler flags
  TestCases/parallel_regression_AD.py
  TestCases/py_wrapper/wavy_wall/run_steady.py
  externals/cgns/hdf5/meson.build
  externals/cgns/meson.build
Labels: changelog:chore

#2061 Remove old python scripts
  SU2_PY/compute_multipoint.py
  SU2_PY/compute_stability.py
  SU2_PY/config_gui.py
  SU2_PY/convert_to_csv.py
  SU2_PY/meson.build
  SU2_PY/package_tests.py
Labels: changelog:chore
