Repository su2code/SU2, pull requests merged in 2023-08, with the labels that each got.

#2099 added cstdint header to printing_toolbox.hpp
  Common/include/toolboxes/printing_toolbox.hpp
Labels: changelog:chore

#2100 Adding V&V case compos. dep. model to test cases.
  TestCases/vandv.py
  TestCases/vandv/species_transport/sandia_jet/VALIDATION.cfg
Labels: changelog:chore

#2102 Prepare release scripts for version 8
  .github/workflows/change-version.yml
  Common/src/CConfig.cpp
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_PY/change_version_number.py
  TestCases/aeroelastic/aeroelastic_NACA64A010.cfg
  TestCases/cont_adj_euler/naca0012/inv_NACA0012.cfg
  TestCases/cont_adj_euler/naca0012/inv_NACA0012_FD.cfg
  TestCases/cont_adj_euler/naca0012/inv_NACA0012_discadj.cfg
  TestCases/cont_adj_euler/wedge/inv_wedge_ROE.cfg
  TestCases/cont_adj_euler/wedge/inv_wedge_ROE_multiobj.cfg
  TestCases/cont_adj_navierstokes/cylinder/lam_cylinder.cfg
  TestCases/cont_adj_navierstokes/naca0012_sub/lam_NACA0012.cfg
  TestCases/cont_adj_navierstokes/naca0012_trans/lam_NACA0012.cfg
  TestCases/cont_adj_rans/naca0012/turb_nasa.cfg
  TestCases/cont_adj_rans/naca0012/turb_nasa_binary.cfg
  TestCases/cont_adj_rans/oneram6/turb_ONERAM6.cfg
  TestCases/cont_adj_rans/rae2822/turb_SA_RAE2822.cfg
  TestCases/control_surface/inv_ONERAM6_moving.cfg
  TestCases/control_surface/inv_ONERAM6_setting.cfg
  TestCases/deformation/cylindrical_ffd/def_cylindrical.cfg
  TestCases/deformation/naca0012/def_NACA0012.cfg
  TestCases/deformation/naca0012/surface_file_NACA0012.cfg
  TestCases/deformation/rae2822/def_RAE2822.cfg
  TestCases/deformation/spherical_ffd/def_spherical.cfg
  TestCases/flamelet/05_laminar_premixed_ch4_flame_cfd_axi/lam_prem_ch4_cfd_axi.cfg
  TestCases/hom_navierstokes/UnsteadyCylinder/nPoly4/fem_unst_cylinder_ADER.cfg
  TestCases/nicf/datadriven/datadriven_nozzle.cfg
  TestCases/optimization_euler/multiobjective_wedge/inv_wedge_ROE_multiobj_combo.cfg
  TestCases/optimization_euler/steady_naca0012/inv_NACA0012_basic.cfg
  TestCases/optimization_rans/pitching_naca64a010/turb_NACA64A010.cfg
  TestCases/optimization_rans/pitching_oneram6/turb_ONERAM6.cfg
  TestCases/optimization_rans/steady_rae2822/turb_SA_RAE2822.cfg
  TestCases/polar/naca0012/inv_NACA0012.cfg
  TestCases/rans/flatplate/turb_SA_flatplate.cfg
  TestCases/rans/oneram6/turb_ONERAM6.cfg
  TestCases/rans/oneram6/turb_ONERAM6_vc.cfg
  TestCases/rans/rae2822/turb_SA_RAE2822.cfg
  TestCases/rans/rae2822/turb_SST_RAE2822.cfg
  TestCases/rans/rae2822/turb_SST_SUST_RAE2822.cfg
  TestCases/rans/s809/trans_s809.cfg
  TestCases/rans/s809/turb_S809.cfg
  TestCases/rans/vki_turbine/turb_vki.cfg
  TestCases/unsteady/pitching_naca64a010_euler/pitching_NACA64A010.cfg
  TestCases/unsteady/plunging_naca0012/plunging_NACA0012.cfg
  TestCases/vandv/species_transport/sandia_jet/validation.cfg
Labels: changelog:none

#2077 Add Velocity volume output for compressible flow solvers
  AUTHORS.md
  SU2_CFD/src/output/CFlowCompOutput.cpp
  SU2_CFD/src/output/CNEMOCompOutput.cpp
Labels: changelog:feature

#2019 Allow selecting the zone used by the python wrapper (for multizone drivers)
  SU2_CFD/include/drivers/CDriverBase.hpp
  SU2_CFD/src/drivers/CDriverBase.cpp
  SU2_CFD/src/python_wrapper_structure.cpp
Labels: PR: unreviewed, changelog:feature

#1935 Compile SU2 with Mutation++ for regression tests
  .github/workflows/regression.yml
  .github/workflows/release-management.yml
  Common/src/CConfig.cpp
  SU2_PY/copy_directory.py
  meson.build
  meson_options.txt
Labels: enhancement, PR: unreviewed, changelog:chore

#2113 fix build with mutation++ on Arm architectures
  meson.build
Labels: changelog:none

#2111 Multizone py wrapper example (FSI)
  SU2_CFD/include/drivers/CDriverBase.hpp
  SU2_CFD/include/drivers/CMultizoneDriver.hpp
  SU2_CFD/include/interfaces/fsi/CFlowTractionInterface.hpp
  SU2_CFD/include/variables/CFEABoundVariable.hpp
  SU2_CFD/include/variables/CVariable.hpp
  SU2_CFD/src/drivers/CDriverBase.cpp
  SU2_CFD/src/drivers/CMultizoneDriver.cpp
  SU2_CFD/src/drivers/CSinglezoneDriver.cpp
  SU2_CFD/src/interfaces/fsi/CDiscAdjFlowTractionInterface.cpp
  SU2_CFD/src/interfaces/fsi/CFlowTractionInterface.cpp
  SU2_CFD/src/output/CElasticityOutput.cpp
  SU2_CFD/src/python_wrapper_structure.cpp
  SU2_CFD/src/variables/CFEABoundVariable.cpp
  TestCases/parallel_regression.py
  TestCases/py_wrapper/dyn_fsi/config.cfg
  TestCases/py_wrapper/dyn_fsi/configFEA.cfg
  TestCases/py_wrapper/dyn_fsi/configFlow.cfg
  TestCases/py_wrapper/dyn_fsi/run.py
  TestCases/serial_regression.py
  TestCases/vandv.py
Labels: changelog:feature
