Repository su2code/SU2, pull requests merged in 2024-04, with the labels that each got.

#2158 Update turbomachinery testcases and regression tests
  TestCases/parallel_regression.py
  TestCases/serial_regression.py
  TestCases/turbomachinery/Aachen_turbine/aachen_3D_MP_restart.cfg
  TestCases/turbomachinery/Aachen_turbine/rotor.cfg
  TestCases/turbomachinery/Aachen_turbine/stator1.cfg
  TestCases/turbomachinery/Aachen_turbine/stator2.cfg
Labels: changelog:chore, Testcase

#2260 Fix update of dual-time solver for species transport.
  SU2_CFD/src/iteration/CFluidIteration.cpp
Labels: changelog:fix

#2267 Fix bug in inlet profile writer.
  SU2_CFD/src/CMarkerProfileReaderFVM.cpp
Labels: changelog:fix

#2252 Update to start volume averaging after StartWindowIteration.
  SU2_CFD/src/output/COutput.cpp
Labels: changelog:fix

#2269 adding to history output residuals for multizone for species flamelet solver
  SU2_CFD/src/output/CFlowOutput.cpp
Labels: changelog:chore

#2270 Fix SU2_DOT without DV vars
  Common/include/CConfig.hpp
Labels: changelog:fix
