Repository su2code/SU2, pull requests merged in 2024-07, with the labels that each got.

#2320 Fixes to turbo monitor
  Common/include/CConfig.hpp
  SU2_CFD/include/iteration/CFluidIteration.hpp
  SU2_CFD/src/iteration/CFluidIteration.cpp
  SU2_CFD/src/output/COutput.cpp
Labels: bug, changelog:fix

#2295 Fix CFL Turbulence reduction option for adaptive cfl
  AUTHORS.md
  SU2_CFD/src/solvers/CSolver.cpp
  TestCases/hybrid_regression.py
  TestCases/parallel_regression.py
  TestCases/serial_regression.py
Labels: changelog:fix

#2271 Compressibility correction for SST model
  Common/include/option_structure.hpp
  Common/src/CConfig.cpp
  SU2_CFD/include/numerics/turbulent/turb_sources.hpp
  TestCases/parallel_regression.py
  TestCases/rans/flatplate/turb_SST_flatplate_compressibility_Sarkar.cfg
  TestCases/rans/flatplate/turb_SST_flatplate_compressibility_Wilcox.cfg
  config_template.cfg
Labels: changelog:feature
