Repository su2code/SU2, pull requests merged in 2024-08, with the labels that each got.

#2323 Change lower limit of SST variables
  Common/include/CConfig.hpp
  Common/include/option_structure.hpp
  Common/src/CConfig.cpp
  SU2_CFD/src/solvers/CTurbSSTSolver.cpp
  config_template.cfg
Labels: changelog:feature

#2327 Supersonic inlet profile
  SU2_CFD/include/solvers/CFVMFlowSolverBase.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/include/solvers/CSpeciesSolver.hpp
  SU2_CFD/include/solvers/CTurbSASolver.hpp
  SU2_CFD/include/solvers/CTurbSSTSolver.hpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_CFD/src/solvers/CSolver.cpp
  SU2_CFD/src/solvers/CSpeciesSolver.cpp
  SU2_CFD/src/solvers/CTurbSASolver.cpp
  SU2_CFD/src/solvers/CTurbSSTSolver.cpp
  TestCases/hybrid_regression.py
  TestCases/parallel_regression.py
  TestCases/serial_regression.py
Labels: changelog:feature

#2197 SA 2D axisymmetric source terms
  Common/src/CConfig.cpp
  SU2_CFD/include/numerics/turbulent/turb_sources.hpp
  SU2_CFD/src/solvers/CTurbSASolver.cpp
Labels: changelog:feature

#2339 Fix hllc jacobians
  Common/include/CConfig.hpp
  SU2_CFD/include/numerics/flow/convection/hllc.hpp
  SU2_CFD/src/numerics/flow/convection/hllc.cpp
  SU2_CFD/src/numerics/flow/convection/roe.cpp
  TestCases/hybrid_regression.py
  TestCases/parallel_regression.py
  TestCases/parallel_regression_AD.py
  TestCases/serial_regression.py
  TestCases/tutorials.py
  config_template.cfg
Labels: changelog:fix

#2341 ASLR fix no longer needed
  .github/workflows/regression.yml
Labels: changelog:fix

#2345 Show error message when FLUID_MIXTURE is used with KIND_SCALAR_MODEL = NONE
  Common/src/CConfig.cpp
Labels: bug, changelog:fix

#2152 Solid to solid conjugate heat transfer
  .github/workflows/regression.yml
  Common/include/CConfig.hpp
  Common/include/option_structure.hpp
  Common/src/CConfig.cpp
  SU2_CFD/include/interfaces/CInterface.hpp
  SU2_CFD/include/interfaces/cht/CConjugateHeatInterface.hpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/drivers/CMultizoneDriver.cpp
  SU2_CFD/src/interfaces/CInterface.cpp
  SU2_CFD/src/interfaces/cht/CConjugateHeatInterface.cpp
  TestCases/parallel_regression.py
  TestCases/tutorials.py
Labels: PR: unreviewed, changelog:feature
