Repository su2code/SU2, pull requests merged in 2024-09, with the labels that each got.

#2278 Fix marker engine inflow
  Common/include/CConfig.hpp
  Common/src/CConfig.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  TestCases/engine/marker_engine_inflow/inv_channel_engine_inflow.cfg
  config_template.cfg
Labels: changelog:feature

#2350 Fix loop variable privatization
  SU2_CFD/src/python_wrapper_structure.cpp
Labels: changelog:fix

#2110 Signal handling - SIGTERM will stop calculation and force file saving
  SU2_CFD/src/drivers/CSinglezoneDriver.cpp
  SU2_CFD/src/output/COutput.cpp
Labels: changelog:feature

#2298 Extending CFL adapt to include species transport
  SU2_CFD/src/solvers/CSolver.cpp
Labels: changelog:feature

#2352 Corrections to SA implementation
  SU2_CFD/include/numerics/turbulent/turb_sources.hpp
Labels: changelog:fix

#2357 Removing unnecessary variables for CFluidScalar constructor
  SU2_CFD/include/fluid/CFluidScalar.hpp
  SU2_CFD/src/fluid/CFluidScalar.cpp
  SU2_CFD/src/solvers/CIncEulerSolver.cpp
Labels: changelog:chore

#2349 Feature turbo interfaces
  Common/include/CConfig.hpp
  Common/include/option_structure.hpp
  Common/include/option_structure.inl
  Common/src/CConfig.cpp
  Common/src/geometry/CPhysicalGeometry.cpp
  SU2_CFD/include/interfaces/CInterface.hpp
  SU2_CFD/include/output/CTurboOutput.hpp
  SU2_CFD/include/solvers/CEulerSolver.hpp
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/drivers/CMultizoneDriver.cpp
  SU2_CFD/src/interfaces/CInterface.cpp
  SU2_CFD/src/interfaces/cfd/CMixingPlaneInterface.cpp
  SU2_CFD/src/iteration/CDiscAdjFluidIteration.cpp
  SU2_CFD/src/output/CFlowCompOutput.cpp
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_CFD/src/output/CTurboOutput.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  TestCases/hybrid_regression.py
  TestCases/parallel_regression.py
  TestCases/serial_regression.py
  TestCases/turbomachinery/multi_interface/multi_interface_rst.cfg
  TestCases/turbomachinery/multi_interface/zone_1.cfg
  TestCases/turbomachinery/multi_interface/zone_2.cfg
  TestCases/turbomachinery/multi_interface/zone_3.cfg
Labels: changelog:feature
