Repository su2code/SU2, pull requests merged in 2024-05, with the labels that each got.

#2246 Address sanitizer tests in the CI pipeline
  .github/workflows/regression.yml
  Common/src/grid_movement/CFreeFormDefBox.cpp
  Common/src/grid_movement/CSurfaceMovement.cpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_GEO/src/SU2_GEO.cpp
  TestCases/TestCase.py
  TestCases/parallel_regression.py
  TestCases/serial_regression.py
  TestCases/serial_regression_AD.py
Labels: changelog:feature

#2281 Using free stream tremperature for initialization of wall temperature for pure conjugate heat transfer problems
  Common/src/CConfig.cpp
Labels: changelog:fix

#2279 change MPI_QUANTITIES to enum class
  Common/include/geometry/CGeometry.hpp
  Common/include/linear_algebra/CSysMatrix.hpp
  Common/include/option_structure.hpp
  Common/src/geometry/CGeometry.cpp
  Common/src/geometry/CPhysicalGeometry.cpp
  Common/src/grid_movement/CVolumetricMovement.cpp
  Common/src/linear_algebra/CSysMatrix.cpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/include/solvers/CScalarSolver.inl
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/drivers/CDriverBase.cpp
  SU2_CFD/src/integration/CMultiGridIntegration.cpp
  SU2_CFD/src/integration/CSingleGridIntegration.cpp
  SU2_CFD/src/iteration/CDiscAdjFEAIteration.cpp
  SU2_CFD/src/iteration/CDiscAdjFluidIteration.cpp
  SU2_CFD/src/iteration/CDiscAdjHeatIteration.cpp
  SU2_CFD/src/solvers/CAdjEulerSolver.cpp
  SU2_CFD/src/solvers/CAdjNSSolver.cpp
  SU2_CFD/src/solvers/CAdjTurbSolver.cpp
  SU2_CFD/src/solvers/CBaselineSolver.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_CFD/src/solvers/CFEASolver.cpp
  SU2_CFD/src/solvers/CGradientSmoothingSolver.cpp
  SU2_CFD/src/solvers/CHeatSolver.cpp
  SU2_CFD/src/solvers/CMeshSolver.cpp
  SU2_CFD/src/solvers/CNEMOEulerSolver.cpp
  SU2_CFD/src/solvers/CNEMONSSolver.cpp
  SU2_CFD/src/solvers/CRadP1Solver.cpp
  SU2_CFD/src/solvers/CRadSolver.cpp
  SU2_CFD/src/solvers/CSolver.cpp
  SU2_CFD/src/solvers/CSpeciesFlameletSolver.cpp
  SU2_CFD/src/solvers/CSpeciesSolver.cpp
  SU2_CFD/src/solvers/CTransLMSolver.cpp
  SU2_CFD/src/solvers/CTurbSASolver.cpp
  SU2_CFD/src/solvers/CTurbSSTSolver.cpp
  SU2_CFD/src/solvers/CTurbSolver.cpp
  UnitTests/SU2_CFD/gradients.cpp
Labels: changelog:chore

#2283 Fix CHT boundary problem for flamelet computations
  SU2_CFD/src/integration/CIntegration.cpp
Labels: changelog:fix
