Repository su2code/SU2, pull requests merged in 2024-02, with the labels that each got.

#2011 New turbo ouputs
  .clang-format
  Common/include/CConfig.hpp
  Common/include/geometry/CGeometry.hpp
  Common/include/geometry/CPhysicalGeometry.hpp
  Common/include/option_structure.hpp
  Common/src/CConfig.cpp
  Common/src/geometry/CPhysicalGeometry.cpp
  SU2_CFD/include/drivers/CDriver.hpp
  SU2_CFD/include/drivers/CMultizoneDriver.hpp
  SU2_CFD/include/interfaces/CInterface.hpp
  SU2_CFD/include/interfaces/cfd/CMixingPlaneInterface.hpp
  SU2_CFD/include/iteration/CFluidIteration.hpp
  SU2_CFD/include/iteration/CIteration.hpp
  SU2_CFD/include/iteration/CTurboIteration.hpp
  SU2_CFD/include/output/CFlowCompOutput.hpp
  SU2_CFD/include/output/CFlowOutput.hpp
  SU2_CFD/include/output/COutput.hpp
  SU2_CFD/include/output/CTurboOutput.hpp
  SU2_CFD/include/solvers/CEulerSolver.hpp
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/drivers/CMultizoneDriver.cpp
  SU2_CFD/src/drivers/CSinglezoneDriver.cpp
  SU2_CFD/src/integration/CIntegration.cpp
  SU2_CFD/src/integration/CMultiGridIntegration.cpp
  SU2_CFD/src/interfaces/CInterface.cpp
  SU2_CFD/src/interfaces/cfd/CMixingPlaneInterface.cpp
  SU2_CFD/src/iteration/CFluidIteration.cpp
  SU2_CFD/src/iteration/CTurboIteration.cpp
  SU2_CFD/src/meson.build
  SU2_CFD/src/output/CFlowCompOutput.cpp
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_CFD/src/output/COutput.cpp
  SU2_CFD/src/output/CTurboOutput.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  TestCases/disc_adj_turbomachinery/transonic_stator_2D/transonic_stator.cfg
  TestCases/hybrid_regression.py
  TestCases/parallel_regression.py
  TestCases/parallel_regression_AD.py
  TestCases/serial_regression.py
  TestCases/turbomachinery/APU_turbocharger/Jones_restart.cfg
  TestCases/turbomachinery/axial_stage_2D/Axial_stage2D.cfg
  TestCases/turbomachinery/centrifugal_blade/centrifugal_blade.cfg
  TestCases/turbomachinery/centrifugal_stage/centrifugal_stage.cfg
  TestCases/turbomachinery/transonic_stator_2D/transonic_stator_restart.cfg
  config_template.cfg
Labels: PR: draft, changelog:feature

#2176 Chore cleanup turbo functions
  SU2_CFD/src/solvers/CEulerSolver.cpp
Labels: changelog:chore

#2212 Fix bugs detected by the address sanitizer
  Common/include/CConfig.hpp
  Common/include/geometry/meshreader/CBoxMeshReaderFVM.hpp
  Common/include/geometry/meshreader/CCGNSMeshReaderFVM.hpp
  Common/include/geometry/meshreader/CMeshReaderFVM.hpp
  Common/include/option_structure.inl
  Common/src/CConfig.cpp
  Common/src/basic_types/ad_structure.cpp
  SU2_CFD/include/iteration/CDiscAdjFEAIteration.hpp
  SU2_CFD/include/iteration/CIteration.hpp
  SU2_CFD/include/output/CFlowCompOutput.hpp
  SU2_CFD/include/output/COutput.hpp
  SU2_CFD/include/solvers/CAdjEulerSolver.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/src/iteration/CDiscAdjFEAIteration.cpp
  SU2_CFD/src/iteration/CTurboIteration.cpp
  SU2_CFD/src/numerics/continuous_adjoint/adj_diffusion.cpp
  SU2_CFD/src/numerics/elasticity/CFEANonlinearElasticity.cpp
  SU2_CFD/src/output/CFlowCompOutput.cpp
  SU2_CFD/src/output/COutput.cpp
  SU2_CFD/src/solvers/CAdjEulerSolver.cpp
  SU2_CFD/src/solvers/CAdjNSSolver.cpp
  SU2_CFD/src/solvers/CBaselineSolver.cpp
  SU2_CFD/src/solvers/CBaselineSolver_FEM.cpp
  SU2_CFD/src/solvers/CFEASolver.cpp
  SU2_CFD/src/solvers/CFEM_DG_EulerSolver.cpp
  SU2_CFD/src/solvers/CHeatSolver.cpp
  SU2_CFD/src/solvers/CMeshSolver.cpp
  SU2_CFD/src/solvers/CRadSolver.cpp
  SU2_CFD/src/solvers/CSolver.cpp
  SU2_CFD/src/solvers/CSpeciesSolver.cpp
  SU2_CFD/src/solvers/CTransLMSolver.cpp
  SU2_CFD/src/solvers/CTurbSolver.cpp
Labels: changelog:fix

#2216 Fix double deformation of points shared by multiple markers
  SU2_CFD/include/variables/CMeshBoundVariable.hpp
  SU2_CFD/src/solvers/CMeshSolver.cpp
Labels: changelog:fix

#2221 Fix wall emissivity out of bounds
  Common/src/CConfig.cpp
Labels: changelog:fix

#2214 Improved look-up table query scaling with variable count
  Common/include/containers/CLookUpTable.hpp
  Common/include/containers/CTrapezoidalMap.hpp
  Common/src/containers/CLookUpTable.cpp
  Common/src/containers/CTrapezoidalMap.cpp
  SU2_CFD/include/fluid/CDataDrivenFluid.hpp
  SU2_CFD/include/fluid/CFluidFlamelet.hpp
  SU2_CFD/src/fluid/CDataDrivenFluid.cpp
  SU2_CFD/src/fluid/CFluidFlamelet.cpp
  UnitTests/Common/containers/CLookupTable_tests.cpp
Labels: changelog:fix
