Repository su2code/SU2, pull requests merged in 2025-05, with the labels that each got.

#2429 Coupled thermoelasticity
  SU2_CFD/include/output/CElasticityOutput.hpp
  SU2_CFD/include/output/CHeatOutput.hpp
  SU2_CFD/include/output/COutput.hpp
  SU2_CFD/include/solvers/CFEASolver.hpp
  SU2_CFD/include/solvers/CHeatSolver.hpp
  SU2_CFD/include/solvers/CScalarSolver.inl
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/iteration/CFEAIteration.cpp
  SU2_CFD/src/output/CElasticityOutput.cpp
  SU2_CFD/src/output/CHeatOutput.cpp
  SU2_CFD/src/solvers/CFEASolver.cpp
  SU2_CFD/src/solvers/CHeatSolver.cpp
  SU2_CFD/src/solvers/CSolverFactory.cpp
  TestCases/fea_fsi/ThermalBeam_3d/configBeam_3d.cfg
  TestCases/incomp_navierstokes/streamwise_periodic/chtPinArray_2d/of_grad_findiff.csv.ref
  TestCases/parallel_regression.py
Labels: changelog:feature

#2500 Correct the header file path
  SU2_CFD/src/fluid/CFluidFlamelet.cpp
Labels: changelog:chore

#2506 Consistent names for the variables of the inlet profile
  SU2_CFD/src/solvers/CSolver.cpp
Labels: changelog:fix
