Repository su2code/SU2, pull requests merged in 2025-01, with the labels that each got.

#2372 Write compact restart files
  Common/include/CConfig.hpp
  Common/src/CConfig.cpp
  SU2_CFD/include/output/COutput.hpp
  SU2_CFD/include/output/filewriter/CParallelDataSorter.hpp
  SU2_CFD/src/output/CAdjFlowCompOutput.cpp
  SU2_CFD/src/output/CAdjFlowIncOutput.cpp
  SU2_CFD/src/output/CAdjHeatOutput.cpp
  SU2_CFD/src/output/CElasticityOutput.cpp
  SU2_CFD/src/output/CFlowCompOutput.cpp
  SU2_CFD/src/output/CFlowIncOutput.cpp
  SU2_CFD/src/output/CNEMOCompOutput.cpp
  SU2_CFD/src/output/COutput.cpp
  SU2_CFD/src/output/filewriter/CParallelDataSorter.cpp
  SU2_CFD/src/output/filewriter/CSU2BinaryFileWriter.cpp
  SU2_CFD/src/output/filewriter/CSU2FileWriter.cpp
  TestCases/flamelet/02_laminar_premixed_ch4_flame_hx_ad/lam_prem_ch4_hx_ad.cfg
  TestCases/flamelet/03_laminar_premixed_ch4_flame_cht_cfd/lam_prem_ch4_cht_cfd_fluid.cfg
  TestCases/flamelet/04_laminar_premixed_ch4_flame_cht_ad/lam_prem_ch4_cht_ad_fluid.cfg
  TestCases/py_wrapper/custom_load_fea/run_ad.py
  config_template.cfg
Labels: changelog:feature

#2404 [WIP] Coupled solver for thermoelasticity
  SU2_CFD/include/solvers/CFEASolver.hpp
  SU2_CFD/src/iteration/CFEAIteration.cpp
  SU2_CFD/src/output/CElasticityOutput.cpp
  SU2_CFD/src/solvers/CFEASolver.cpp
  SU2_CFD/src/solvers/CSolverFactory.cpp
Labels: PR: draft, changelog:feature

#2415 Fix FSIInterface python script
  SU2_PY/FSI_tools/FSIInterface.py
Labels: bug, changelog:fix

#2417 Fix Non-dimensionalization to translation velocity
  SU2_CFD/src/solvers/CMeshSolver.cpp
Labels: changelog:fix

#2427 Remove unused option SMOOTH_GEOMETRY
  Common/include/CConfig.hpp
  Common/include/geometry/CGeometry.hpp
  Common/include/geometry/CPhysicalGeometry.hpp
  Common/include/geometry/dual_grid/CPoint.hpp
  Common/src/CConfig.cpp
  Common/src/geometry/CPhysicalGeometry.cpp
  Common/src/geometry/dual_grid/CPoint.cpp
Labels: changelog:chore

#2418 Fix output names of unsteady simulation
  SU2_CFD/src/output/COutput.cpp
Labels: changelog:fix

#2425 CTurbSASolver.cpp changed as mentioned
  SU2_CFD/src/solvers/CTurbSASolver.cpp
Labels: changelog:fix
