Repository su2code/SU2, pull requests merged in 2025-07, with the labels that each got.

#2526 cpp version increase for CoDiPack
  meson.build
Labels: changelog:chore

#2528 Reduce the tapeing overhead in CFVMFlowSolverBase.inl.
  Common/include/basic_types/ad_structure.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
Labels: changelog:fix

#2388 pywrapper - custom source terms for all solvers
  .github/workflows/regression.yml
  Common/include/CConfig.hpp
  Common/include/containers/CPyWrapperMatrixView.hpp
  Common/include/containers/container_decorators.hpp
  Common/include/geometry/dual_grid/CPoint.hpp
  Common/include/option_structure.hpp
  Common/src/CConfig.cpp
  SU2_CFD/include/drivers/CDriver.hpp
  SU2_CFD/include/drivers/CDriverBase.hpp
  SU2_CFD/include/solvers/CSolver.hpp
  SU2_CFD/include/solvers/CSpeciesSolver.hpp
  SU2_CFD/include/variables/CVariable.hpp
  SU2_CFD/src/iteration/CFluidIteration.cpp
  SU2_CFD/src/numerics/flow/flow_sources.cpp
  SU2_CFD/src/output/CFlowOutput.cpp
  SU2_CFD/src/python_wrapper_structure.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_CFD/src/solvers/CIncEulerSolver.cpp
  SU2_CFD/src/solvers/CRadP1Solver.cpp
  SU2_CFD/src/solvers/CSpeciesFlameletSolver.cpp
  SU2_CFD/src/solvers/CSpeciesSolver.cpp
  SU2_CFD/src/solvers/CTransLMSolver.cpp
  SU2_CFD/src/solvers/CTurbSASolver.cpp
  SU2_CFD/src/solvers/CTurbSSTSolver.cpp
  SU2_CFD/src/variables/CVariable.cpp
  TestCases/parallel_regression.py
  TestCases/py_wrapper/custom_source_buoyancy/lam_buoyancy_cavity.cfg
  TestCases/py_wrapper/custom_source_buoyancy/run.py
  TestCases/py_wrapper/turbulent_premixed_psi/psi.cfg
  TestCases/py_wrapper/turbulent_premixed_psi/run.py
Labels: changelog:feature

#2516 Fix damping mass outlet
  Common/include/CConfig.hpp
  SU2_CFD/include/solvers/CIncEulerSolver.hpp
  SU2_CFD/src/solvers/CIncEulerSolver.cpp
  TestCases/hybrid_regression.py
  TestCases/parallel_regression.py
  TestCases/serial_regression.py
Labels: changelog:fix

#2541 Fix sign error in incompressible Spalding wall function
  SU2_CFD/src/solvers/CIncNSSolver.cpp
  TestCases/serial_regression.py
  TestCases/tutorials.py
Labels: changelog:fix

#2536 Tracy profiler integration
  Common/include/tracy_structure.hpp
  meson.build
  meson_options.txt
  subprojects/tracy.wrap
Labels: changelog:feature

#2530 RBF deformation
  .gitignore
  Common/include/CConfig.hpp
  Common/include/grid_movement/CLinearElasticity.hpp
  Common/include/grid_movement/CRadialBasisFunctionInterpolation.hpp
  Common/include/grid_movement/CRadialBasisFunctionNode.hpp
  Common/include/grid_movement/CVolumetricMovement.hpp
  Common/include/grid_movement/CVolumetricMovementFactory.hpp
  Common/include/option_structure.hpp
  Common/src/CConfig.cpp
  Common/src/geometry/CPhysicalGeometry.cpp
  Common/src/grid_movement/CLinearElasticity.cpp
  Common/src/grid_movement/CRadialBasisFunctionInterpolation.cpp
  Common/src/grid_movement/CVolumetricMovement.cpp
  Common/src/grid_movement/CVolumetricMovementFactory.cpp
  Common/src/grid_movement/meson.build
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_DEF/src/drivers/CDeformationDriver.cpp
  SU2_DEF/src/drivers/CDiscAdjDeformationDriver.cpp
  TestCases/deformation/naca0012/def_NACA0012_rbf.cfg
  TestCases/parallel_regression.py
Labels: changelog:feature
