Repository su2code/SU2, pull requests merged in 2025-06, with the labels that each got.

#2346 [GSOC24] Addition of CUDA and GPU Acceleration to FGMRES Linear Solver in SU2
  Common/include/CConfig.hpp
  Common/include/linear_algebra/CMatrixVectorProduct.hpp
  Common/include/linear_algebra/CSysMatrix.hpp
  Common/include/linear_algebra/CSysVector.hpp
  Common/include/linear_algebra/GPUComms.cuh
  Common/include/toolboxes/allocation_toolbox.hpp
  Common/src/CConfig.cpp
  Common/src/linear_algebra/CSysMatrix.cpp
  Common/src/linear_algebra/CSysMatrixGPU.cu
  Common/src/linear_algebra/CSysVector.cpp
  Common/src/linear_algebra/CSysVectorGPU.cu
  Common/src/linear_algebra/meson.build
  config_template.cfg
  doxyfile
  meson.build
  meson_options.txt
Labels: changelog:feature, GSoC

#2520 Fix periodic parallel preprocessing
  Common/src/geometry/CGeometry.cpp
  TestCases/mms/fvm_euler/inv_mms_vortex.cfg
  TestCases/parallel_regression.py
  TestCases/serial_regression.py
Labels: changelog:fix

#2508 Updating SA-Diffusion term Discretisation
  .github/workflows/regression.yml
  Common/include/CConfig.hpp
  Common/src/CConfig.cpp
  SU2_CFD/include/numerics/turbulent/turb_diffusion.hpp
  SU2_CFD/include/numerics/turbulent/turb_sources.hpp
  SU2_CFD/include/solvers/CScalarSolver.hpp
  SU2_CFD/include/solvers/CScalarSolver.inl
  SU2_CFD/src/solvers/CTurbSASolver.cpp
  TestCases/hybrid_regression.py
  TestCases/hybrid_regression_AD.py
  TestCases/parallel_regression.py
  TestCases/parallel_regression_AD.py
  TestCases/serial_regression.py
  TestCases/serial_regression_AD.py
  TestCases/tutorials.py
  TestCases/vandv.py
  config_template.cfg
Labels: changelog:feature
