Repository su2code/SU2, pull requests merged in 2025-03, with the labels that each got.

#2392 Fix cornernode normal
  Common/include/geometry/CMultiGridGeometry.hpp
  Common/include/geometry/CPhysicalGeometry.hpp
  Common/include/geometry/dual_grid/CVertex.hpp
  Common/src/geometry/CGeometry.cpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/include/solvers/CTurbSSTSolver.hpp
  SU2_CFD/include/variables/CFlowVariable.hpp
  SU2_CFD/include/variables/CVariable.hpp
  SU2_CFD/src/drivers/CDriver.cpp
  SU2_CFD/src/solvers/CIncNSSolver.cpp
  SU2_CFD/src/solvers/CNSSolver.cpp
  SU2_CFD/src/solvers/CTurbSASolver.cpp
  SU2_CFD/src/solvers/CTurbSSTSolver.cpp
  TestCases/Tutorials/design/Inc_Turbulent_Bend_Wallfunctions/optim.csv.ref
  TestCases/hybrid_regression.py
  TestCases/hybrid_regression_AD.py
  TestCases/incomp_navierstokes/streamwise_periodic/chtPinArray_2d/of_grad_findiff.csv.ref
  TestCases/parallel_regression.py
  TestCases/parallel_regression_AD.py
  TestCases/serial_regression.py
  TestCases/serial_regression_AD.py
  TestCases/tutorials.py
  TestCases/vandv.py
  TestCases/vandv/rans/swbli/config_sst.cfg
Labels: changelog:fix

#2447 Tutorial unsteady vortex shedding behind a cylinder
  TestCases/tutorials.py
Labels: PR: draft, changelog:chore

#2462 Change regression values for 90 degree bend
  TestCases/tutorials.py
Labels: changelog:fix

#2430 [WIP] Turbulent kinetic energy based on inlet condition for supersonic inlet
  SU2_CFD/src/solvers/CEulerSolver.cpp
Labels: changelog:feature

#2466 Fix Max Residual Output for Incompressible Flow
  SU2_CFD/src/output/CFlowIncOutput.cpp
  TestCases/parallel_regression.py
  TestCases/tutorials.py
Labels: changelog:fix

#2460 Fix curved symmetries
  Common/include/geometry/CGeometry.hpp
  Common/src/geometry/CGeometry.cpp
  TestCases/disc_adj_fsi/dyn_fsi/grad_dv.opt.ref
  TestCases/hybrid_regression.py
  TestCases/hybrid_regression_AD.py
  TestCases/incomp_navierstokes/cylinder_split/cylinder_split.cfg
  TestCases/multiple_ffd/naca0012/of_grad_cd.dat.ref
  TestCases/multiple_ffd/naca0012/of_grad_directdiff.dat.ref
  TestCases/parallel_regression.py
  TestCases/parallel_regression_AD.py
  TestCases/serial_regression.py
  TestCases/serial_regression_AD.py
  TestCases/tutorials.py
Labels: changelog:fix

#2477 Made sure the CGNS reader works again for high order grids
  Common/src/geometry/meshreader/CCGNSMeshReaderBase.cpp
  Common/src/geometry/meshreader/CCGNSMeshReaderFEM.cpp
Labels: bug, changelog:fix

#2458 Correct inconsistency regarding the density used in conservative scalar solver
  SU2_CFD/include/solvers/CScalarSolver.inl
  TestCases/hybrid_regression.py
  TestCases/hybrid_regression_AD.py
  TestCases/parallel_regression.py
  TestCases/parallel_regression_AD.py
  TestCases/serial_regression.py
  TestCases/serial_regression_AD.py
  TestCases/tutorials.py
  TestCases/vandv.py
Labels: changelog:fix

#2484 Fix wall distance computation for points on viscous wall
  Common/src/geometry/CGeometry.cpp
  TestCases/parallel_regression.py
  TestCases/tutorials.py
  TestCases/vandv.py
Labels: changelog:fix
