Repository su2code/SU2, pull requests merged in 2025-09, with the labels that each got.

#2419 Update turbo ramps
  AUTHORS.md
  Common/include/CConfig.hpp
  Common/include/geometry/CGeometry.hpp
  Common/src/CConfig.cpp
  SU2_CFD/include/iteration/CFluidIteration.hpp
  SU2_CFD/include/iteration/CTurboIteration.hpp
  SU2_CFD/src/iteration/CFluidIteration.cpp
  SU2_CFD/src/iteration/CTurboIteration.cpp
  SU2_CFD/src/solvers/CSolver.cpp
  TestCases/disc_adj_turbomachinery/transonic_stator_2D/transonic_stator.cfg
  TestCases/turbomachinery/APU_turbocharger/Jones_restart.cfg
  TestCases/turbomachinery/APU_turbocharger/rotor.cfg
  TestCases/turbomachinery/APU_turbocharger/rotor_restart.cfg
  TestCases/turbomachinery/Aachen_turbine/aachen_3D_MP_restart.cfg
  TestCases/turbomachinery/Aachen_turbine/rotor.cfg
  TestCases/turbomachinery/axial_stage_2D/Axial_stage2D.cfg
  TestCases/turbomachinery/multi_interface/multi_interface_rst.cfg
  TestCases/turbomachinery/transonic_stator_2D/transonic_stator_restart.cfg
  config_template.cfg
Labels: PR: draft, changelog:feature

#2571 FIX: Corrected integer division in set_ffd_design_var.py for Python 3…
  SU2_PY/set_ffd_design_var.py
Labels: changelog:fix

#2420 Enable the use of conductivity models different from CONSTANT_PRANDTL for compressible flows.
  Common/include/CConfig.hpp
  Common/src/CConfig.cpp
  Common/src/geometry/CPhysicalGeometryFEM.cpp
  SU2_CFD/include/numerics/CNumerics.hpp
  SU2_CFD/include/numerics/flow/flow_diffusion.hpp
  SU2_CFD/include/numerics_simd/flow/diffusion/viscous_fluxes.hpp
  SU2_CFD/include/solvers/CEulerSolver.hpp
  SU2_CFD/include/solvers/CFVMFlowSolverBase.inl
  SU2_CFD/include/solvers/CHeatSolver.hpp
  SU2_CFD/src/interfaces/cht/CConjugateHeatInterface.cpp
  SU2_CFD/src/numerics/CNumerics.cpp
  SU2_CFD/src/numerics/continuous_adjoint/adj_diffusion.cpp
  SU2_CFD/src/numerics/continuous_adjoint/adj_sources.cpp
  SU2_CFD/src/numerics/flow/flow_diffusion.cpp
  SU2_CFD/src/solvers/CAdjNSSolver.cpp
  SU2_CFD/src/solvers/CEulerSolver.cpp
  SU2_CFD/src/solvers/CFEM_DG_EulerSolver.cpp
  SU2_CFD/src/solvers/CHeatSolver.cpp
  SU2_CFD/src/solvers/CIncEulerSolver.cpp
  SU2_CFD/src/solvers/CNSSolver.cpp
  TestCases/hybrid_regression.py
  TestCases/hybrid_regression_AD.py
  TestCases/parallel_regression.py
  TestCases/parallel_regression_AD.py
  TestCases/rans/flatplate/turb_SA_flatplate_species.cfg
  TestCases/serial_regression.py
  TestCases/serial_regression_AD.py
  TestCases/tutorials.py
  TestCases/vandv.py
Labels: changelog:feature

#2569 Adding temperature limits for incompressible solver
  Common/include/CConfig.hpp
  Common/src/CConfig.cpp
  SU2_CFD/include/variables/CIncEulerVariable.hpp
  SU2_CFD/src/variables/CIncEulerVariable.cpp
  SU2_CFD/src/variables/CIncNSVariable.cpp
  TestCases/parallel_regression.py
  TestCases/species_transport/passive_transport_validation/active_species_transport_temp_limits.cfg
  config_template.cfg
Labels: changelog:feature
